/**
 * Convex application seed binding — public API on `@angriff36/manifest/seed-pack`.
 *
 * Maps an IR sample seed pack to Convex mutation exports (`Entity_create`) and
 * emits a runner script that inserts rows via `ConvexHttpClient`. This is the
 * Manifest proof that seed-pack integrates into the Convex application contract.
 */

import type { IR, IRCommand } from '../ir.js';
import type { SeedPack, SeedEntityTable } from './types.js';
import { isBlankCell } from './types.js';

export interface ConvexSeedEntityBinding {
  entity: string;
  /** Convex mutations export name: `${entity}_${command}`. */
  createMutation: string | null;
  seedKeys: string[];
  columns: string[];
  rowCount: number;
}

export interface ConvexSeedBinding {
  packId: string;
  version: string;
  entities: ConvexSeedEntityBinding[];
  pathHint: string;
}

export interface GenerateConvexSeedScriptOptions {
  /** Import path for ConvexHttpClient (default `convex/browser`). */
  convexClientImport?: string;
  /** Import path for generated `api` (default `../convex/_generated/api`). */
  apiImportPath?: string;
  /** Output path hint. */
  output?: string;
}

const DEFAULTS = {
  convexClientImport: 'convex/browser',
  apiImportPath: '../convex/_generated/api',
  output: 'scripts/seed-convex.ts',
} as const;

function findCreateCommand(ir: IR, entityName: string): IRCommand | undefined {
  return ir.commands.find((c) => c.entity === entityName && c.name === 'create');
}

function tableBinding(ir: IR, table: SeedEntityTable): ConvexSeedEntityBinding {
  const create = findCreateCommand(ir, table.entity);
  const seedKeys = table.rows
    .map((r) => r.seedKey)
    .filter((k): k is string => typeof k === 'string' && !isBlankCell(k));
  return {
    entity: table.entity,
    createMutation: create ? `${table.entity}_${create.name}` : null,
    seedKeys,
    columns: [...table.columns],
    rowCount: table.rows.length,
  };
}

/**
 * Describe how a seed pack binds to Convex create mutations for this IR.
 */
export function describeConvexSeedBinding(ir: IR, pack: SeedPack): ConvexSeedBinding {
  return {
    packId: pack.meta.packId,
    version: pack.meta.version,
    entities: pack.tables.map((t) => tableBinding(ir, t)),
    pathHint: DEFAULTS.output,
  };
}

function rowToArgsLiteral(row: Record<string, string>, columns: string[]): string {
  const parts: string[] = [];
  for (const col of columns) {
    if (col === 'seedKey') continue;
    const raw = row[col];
    if (isBlankCell(raw)) continue;
    parts.push(`${JSON.stringify(col)}: ${JSON.stringify(raw)}`);
  }
  return `{ ${parts.join(', ')} }`;
}

/**
 * Generate a Convex seed runner that calls create mutations for each pack row.
 * Entities without a `create` command are skipped with a diagnostic comment.
 */
export function generateConvexSeedScript(
  ir: IR,
  pack: SeedPack,
  options?: GenerateConvexSeedScriptOptions,
): { code: string; binding: ConvexSeedBinding } {
  const binding = describeConvexSeedBinding(ir, pack);
  const clientImport = options?.convexClientImport ?? DEFAULTS.convexClientImport;
  const apiImport = options?.apiImportPath ?? DEFAULTS.apiImportPath;
  const pathHint = options?.output ?? DEFAULTS.output;
  binding.pathHint = pathHint;

  const lines: string[] = [];
  lines.push(`/** Generated by Manifest seed-pack Convex binding — do not edit by hand. */`);
  lines.push(`import { ConvexHttpClient } from ${JSON.stringify(clientImport)};`);
  lines.push(`import { api } from ${JSON.stringify(apiImport)};`);
  lines.push('');
  lines.push(`const PACK_ID = ${JSON.stringify(pack.meta.packId)};`);
  lines.push(`const PACK_VERSION = ${JSON.stringify(pack.meta.version)};`);
  lines.push('');
  lines.push(`export async function seedConvex(deploymentUrl: string): Promise<void> {`);
  lines.push(`  const client = new ConvexHttpClient(deploymentUrl);`);
  lines.push(`  void PACK_ID;`);
  lines.push(`  void PACK_VERSION;`);

  for (const table of pack.tables) {
    const b = binding.entities.find((e) => e.entity === table.entity)!;
    if (!b.createMutation) {
      lines.push(
        `  // skip ${table.entity}: no create command in IR (${table.rows.length} rows unused)`,
      );
      continue;
    }
    lines.push(`  // ${table.entity} → api.mutations.${b.createMutation}`);
    for (const row of table.rows) {
      const args = rowToArgsLiteral(row, table.columns);
      lines.push(
        `  await client.mutation(api.mutations.${b.createMutation}, ${args} as any);`,
      );
    }
  }

  lines.push(`}`);
  lines.push('');
  lines.push(
    `export const MANIFEST_CONVEX_SEED_BINDING = ${JSON.stringify(
      {
        packId: binding.packId,
        version: binding.version,
        entities: binding.entities.map((e) => ({
          entity: e.entity,
          createMutation: e.createMutation,
          rowCount: e.rowCount,
        })),
      },
      null,
      2,
    )} as const;`,
  );
  lines.push('');

  return { code: lines.join('\n'), binding };
}
