/**
 * manifest init --ci <provider>
 *
 * Generates a CI workflow file for the specified provider.
 * Currently supports: github
 */

import chalk from 'chalk';
import { access } from 'node:fs/promises';
import { join } from 'node:path';

export interface InitCiOptions {
  force?: boolean;
  nodeVersions?: string;
  dryRun?: boolean;
}

const DEFAULT_NODE_VERSIONS = ['18', '20', '22'];

/**
 * Generate a GitHub Actions workflow YAML string.
 */
export function generateGitHubWorkflow(nodeVersions: string[]): string {
  const matrix = nodeVersions.map((v) => `'${v}'`).join(', ');

  return `# Generated by: manifest init --ci github
# Manifest CI — validates, scans, and tests on every pull request.
# Matrix builds across Node.js versions: ${nodeVersions.join(', ')}

name: Manifest CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-and-test:
    name: Validate & Test (Node \${{ matrix.node-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [${matrix}]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: \${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Manifest validate
        run: npx manifest validate

      - name: Manifest scan
        run: npx manifest scan

      - name: Run tests
        run: npm test

  conformance-regen:
    name: Regenerate conformance fixtures
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [validate-and-test]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: \${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Regenerate conformance fixtures
        run: npm run conformance:regen

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet || echo "has_changes=true" >> "$GITHUB_OUTPUT"

      - name: Commit updated fixtures
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: regenerate conformance fixtures [skip ci]"
          git push
`;
}

/**
 * Init CI command handler
 */
export async function initCiCommand(provider: string, options: InitCiOptions = {}): Promise<void> {
  const supportedProviders = ['github'];

  if (!supportedProviders.includes(provider)) {
    console.error(
      chalk.red(
        `Unsupported CI provider: "${provider}". Supported: ${supportedProviders.join(', ')}`,
      ),
    );
    process.exitCode = 1;
    return;
  }

  const nodeVersions = options.nodeVersions
    ? options.nodeVersions.split(',').map((v) => v.trim())
    : DEFAULT_NODE_VERSIONS;

  const workflowDir = join(process.cwd(), '.github', 'workflows');
  const workflowPath = join(workflowDir, 'manifest-ci.yml');

  // Check if file already exists
  if (!options.force) {
    try {
      await access(workflowPath);
      console.log(chalk.yellow('Workflow file already exists: .github/workflows/manifest-ci.yml'));
      console.log('');
      console.log('Use --force to overwrite:');
      console.log('  manifest init --ci github --force');
      return;
    } catch {
      // File doesn't exist, proceed
    }
  }

  // Generate and write
  const workflow = generateGitHubWorkflow(nodeVersions);

  const { writeTextFile } = await import('../utils/dry-run-fs.js');
  await writeTextFile(workflowPath, workflow, { dryRun: options.dryRun });

  if (options.dryRun) {
    console.log(chalk.cyan('dry-run: would create .github/workflows/manifest-ci.yml'));
    return;
  }

  console.log(chalk.bold.green('✓ GitHub Actions workflow created!'));
  console.log('');
  console.log(chalk.bold('File: .github/workflows/manifest-ci.yml'));
  console.log('');
  console.log(chalk.bold('What it does:'));
  console.log(`  • Runs ${chalk.cyan('manifest validate')} on every PR`);
  console.log(`  • Runs ${chalk.cyan('manifest scan')} on every PR`);
  console.log(`  • Runs ${chalk.cyan('npm test')} on every PR`);
  console.log(`  • Matrix builds: Node.js ${nodeVersions.join(', ')}`);
  console.log(`  • Auto-regenerates conformance fixtures on main`);
  console.log('');
  console.log(chalk.gray('Commit the file and push to enable CI.'));
  console.log('');
}
