/**
 * manifest install-hooks command
 *
 * Installs Husky or simple-git-hooks pre-commit hooks that run
 * manifest fmt --check and manifest validate before each commit.
 */

import chalk from 'chalk';
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { getConfig, type ManifestConfig } from '../utils/config.js';

export type HookProvider = 'husky' | 'simple-git-hooks';

export interface HooksConfig {
  skipInCi?: boolean;
  provider?: HookProvider;
  runFmt?: boolean;
  runValidate?: boolean;
}

export interface InstallHooksOptions {
  force?: boolean;
  provider?: HookProvider;
}

export interface ResolvedHooksConfig {
  skipInCi: boolean;
  provider: HookProvider;
  runFmt: boolean;
  runValidate: boolean;
}

function resolveHooksConfig(config: ManifestConfig | null, options: InstallHooksOptions): ResolvedHooksConfig {
  const hooks = (config?.hooks ?? {}) as HooksConfig;
  return {
    skipInCi: hooks.skipInCi ?? true,
    provider: options.provider ?? hooks.provider ?? 'husky',
    runFmt: hooks.runFmt ?? true,
    runValidate: hooks.runValidate ?? true,
  };
}

/**
 * Generate the pre-commit shell script content.
 */
export function generatePreCommitHookScript(config: ResolvedHooksConfig): string {
  const lines: string[] = [
    '#!/usr/bin/env sh',
    '# Generated by: manifest install-hooks',
    '',
  ];

  if (config.skipInCi) {
    lines.push('# Skip in CI unless MANIFEST_SKIP_HOOKS=0');
    lines.push('if [ -n "$CI" ] && [ "$MANIFEST_SKIP_HOOKS" != "0" ]; then');
    lines.push('  exit 0');
    lines.push('fi');
    lines.push('');
  }

  lines.push('STAGED=$(git diff --cached --name-only --diff-filter=ACM -- "*.manifest")');
  lines.push('if [ -z "$STAGED" ]; then');
  lines.push('  exit 0');
  lines.push('fi');
  lines.push('');
  lines.push('echo "Manifest pre-commit: checking staged .manifest files..."');
  lines.push('');

  if (config.runFmt) {
    lines.push('for file in $STAGED; do');
    lines.push('  if [ ! -f "$file" ]; then');
    lines.push('    continue');
    lines.push('  fi');
    lines.push('  npx manifest fmt --check "$file" || exit 1');
    lines.push('done');
    lines.push('');
  }

  if (config.runValidate) {
    lines.push('npx manifest validate || exit 1');
    lines.push('');
  }

  lines.push('exit 0');
  lines.push('');

  return lines.join('\n');
}

async function installHuskyHook(script: string, options: InstallHooksOptions): Promise<string> {
  const huskyDir = join(process.cwd(), '.husky');
  const hookPath = join(huskyDir, 'pre-commit');

  if (!options.force) {
    try {
      await access(hookPath);
      console.log(chalk.yellow('Pre-commit hook already exists: .husky/pre-commit'));
      console.log('');
      console.log('Use --force to overwrite:');
      console.log('  manifest install-hooks --force');
      return hookPath;
    } catch {
      // proceed
    }
  }

  await mkdir(huskyDir, { recursive: true });
  await writeFile(hookPath, script, { mode: 0o755 });
  return hookPath;
}

async function installSimpleGitHooks(script: string, options: InstallHooksOptions): Promise<string> {
  const packageJsonPath = join(process.cwd(), 'package.json');
  let pkg: Record<string, unknown>;

  try {
    const raw = await readFile(packageJsonPath, 'utf-8');
    pkg = JSON.parse(raw) as Record<string, unknown>;
  } catch {
    console.error(chalk.red('package.json not found. simple-git-hooks requires a Node.js project.'));
    process.exitCode = 1;
    return packageJsonPath;
  }

  const existing = pkg['simple-git-hooks'] as Record<string, string> | undefined;
  if (existing?.['pre-commit'] && !options.force) {
    console.log(chalk.yellow('simple-git-hooks pre-commit entry already exists in package.json'));
    console.log('');
    console.log('Use --force to overwrite:');
    console.log('  manifest install-hooks --provider simple-git-hooks --force');
    return packageJsonPath;
  }

  pkg['simple-git-hooks'] = {
    ...(existing ?? {}),
    'pre-commit': script.replace(/\n/g, ' ').trim(),
  };

  await writeFile(packageJsonPath, `${JSON.stringify(pkg, null, 2)}\n`, 'utf-8');
  return packageJsonPath;
}

export async function installHooksCommand(options: InstallHooksOptions = {}): Promise<void> {
  const config = await getConfig();
  const hooksConfig = resolveHooksConfig(config, options);
  const script = generatePreCommitHookScript(hooksConfig);

  if (hooksConfig.provider === 'husky') {
    const hookPath = await installHuskyHook(script, options);
    if (process.exitCode === 1) {
      return;
    }

    console.log(chalk.bold.green('✓ Husky pre-commit hook installed!'));
    console.log('');
    console.log(chalk.bold(`File: ${hookPath.replace(process.cwd(), '.')}`));
    console.log('');
    console.log(chalk.bold('Next steps:'));
    console.log('  1. npm install -D husky');
    console.log('  2. npx husky init   # if .husky/_/husky.sh is missing');
    console.log('  3. Commit a .manifest change to verify the hook');
    return;
  }

  const packageJsonPath = await installSimpleGitHooks(script, options);
  if (process.exitCode === 1) {
    return;
  }

  console.log(chalk.bold.green('✓ simple-git-hooks pre-commit entry installed!'));
  console.log('');
  console.log(chalk.bold(`File: ${packageJsonPath.replace(process.cwd(), '.')}`));
  console.log('');
  console.log(chalk.bold('Next steps:'));
  console.log('  1. npm install -D simple-git-hooks');
  console.log('  2. npx simple-git-hooks');
  console.log('  3. Commit a .manifest change to verify the hook');
}
