/**
 * manifest preflight command
 *
 * Pre-flight checks for Manifest applications.
 * Validates environment variables, configuration, and dependencies before runtime.
 *
 * Primary goal: "If preflight passes, the app will start without config errors."
 */

import chalk from 'chalk';
import path from 'node:path';
import { loadAllConfigs, type EnvMapping, type EnvVarDefinition } from '../utils/config.js';
import { getActiveConfigPath } from '../utils/config.js';

export interface PreflightOptions {
  /** Preview .env.example write when --generate-example is set. */
  dryRun?: boolean;
  /**
   * Output format: 'text' (human-readable) or 'json' (machine-readable)
   */
  format?: 'text' | 'json';

  /**
   * Generate .env.example file instead of checking
   */
  generateExample?: boolean;

  /**
   * Output path for .env.example (default: .env.example in project root)
   */
  output?: string;

  /**
   * Working directory (defaults to process.cwd())
   */
  cwd?: string;
}

interface EnvVarStatus {
  name: string;
  category: string;
  key: string;
  isSet: boolean;
  isRequired: boolean;
  hasDefault: boolean;
  description?: string;
  example?: string;
}

interface PreflightResult {
  ok: boolean;
  configPath: string | null;
  envMapping: EnvMapping | null;
  checked: EnvVarStatus[];
  missing: EnvVarStatus[];
  present: EnvVarStatus[];
  optionalMissing: EnvVarStatus[];
}

/**
 * Get all environment variable definitions from the env mapping
 */
function getAllEnvVars(
  envMapping: EnvMapping | undefined,
): Array<{ category: string; key: string; def: EnvVarDefinition }> {
  if (!envMapping) return [];

  const result: Array<{ category: string; key: string; def: EnvVarDefinition }> = [];

  for (const [category, section] of Object.entries(envMapping)) {
    if (section && typeof section === 'object') {
      for (const [key, def] of Object.entries(section)) {
        if (def && typeof def === 'object' && 'name' in def) {
          result.push({ category, key, def: def as EnvVarDefinition });
        }
      }
    }
  }

  return result;
}

/**
 * Check environment variable status
 */
function checkEnvVar(category: string, key: string, def: EnvVarDefinition): EnvVarStatus {
  const envVarName = def.name;
  const isSet = envVarName in process.env;
  const isRequired = def.required !== false; // default is true
  const hasDefault = def.default !== undefined;

  return {
    name: envVarName,
    category,
    key,
    isSet,
    isRequired,
    hasDefault,
    description: def.description,
    example: def.example,
  };
}

/**
 * Run preflight checks on environment variables
 */
async function runEnvChecks(cwd: string): Promise<PreflightResult> {
  const configPath = await getActiveConfigPath(cwd);
  const { build } = await loadAllConfigs(cwd);
  const envMapping = build.env;

  const allVars = getAllEnvVars(envMapping);
  const checked = allVars.map(({ category, key, def }) => checkEnvVar(category, key, def));

  const missing = checked.filter((s) => !s.isSet && s.isRequired && !s.hasDefault);
  const present = checked.filter((s) => s.isSet);
  const optionalMissing = checked.filter((s) => !s.isSet && !s.isRequired);

  return {
    ok: missing.length === 0,
    configPath,
    envMapping: envMapping ?? null,
    checked,
    missing,
    present,
    optionalMissing,
  };
}

/**
 * Generate .env.example file content
 */
function generateEnvExampleContent(result: PreflightResult): string {
  const lines: string[] = [];

  lines.push('# Environment variables for Manifest application');
  lines.push('# Generated by: manifest preflight --generate-example');
  lines.push('#');

  if (result.configPath) {
    lines.push(`# Source: ${result.configPath}`);
  }
  lines.push('#');

  // Group by category
  const categories = new Map<string, EnvVarStatus[]>();
  for (const status of result.checked) {
    if (!categories.has(status.category)) {
      categories.set(status.category, []);
    }
    categories.get(status.category)!.push(status);
  }

  // Order categories logically
  const categoryOrder = ['stores', 'auth', 'adapters', 'custom'];
  for (const category of categoryOrder) {
    const vars = categories.get(category);
    if (!vars || vars.length === 0) continue;

    lines.push('');
    lines.push(`# ${category.charAt(0).toUpperCase() + category.slice(1)}`);

    for (const status of vars) {
      lines.push('');
      if (status.description) {
        lines.push(`# ${status.description}`);
      }
      if (!status.isRequired) {
        lines.push('# Optional');
      }
      if (status.example) {
        lines.push(`# Example: ${status.example}`);
      }
      if (status.hasDefault) {
        lines.push('# Has a default value');
      }

      const value = status.example || 'your-value-here';
      lines.push(`${status.name}=${value}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Format preflight results as text
 */
function formatTextResult(result: PreflightResult): string {
  const lines: string[] = [];

  if (result.configPath) {
    lines.push(chalk.gray(`Config: ${result.configPath}`));
  } else {
    lines.push(chalk.gray('Config: defaults only (no config file found)'));
  }
  lines.push('');

  if (result.checked.length === 0) {
    lines.push(chalk.yellow('No environment variables configured.'));
    lines.push('');
    lines.push(
      chalk.gray('Add an "env" section to manifest.config.yaml to define environment variables:'),
    );
    lines.push('');
    lines.push(chalk.gray('  env:'));
    lines.push(chalk.gray('    stores:'));
    lines.push(chalk.gray('      database:'));
    lines.push(chalk.gray('        name: DATABASE_URL'));
    lines.push(chalk.gray('        description: "PostgreSQL connection string"'));
    lines.push(chalk.gray('        required: true'));
    return lines.join('\n');
  }

  // Summary
  if (result.ok) {
    lines.push(chalk.green.bold('✓ All required environment variables are set.'));
  } else {
    lines.push(
      chalk.red.bold(`✗ ${result.missing.length} required environment variable(s) missing.`),
    );
  }
  lines.push('');

  // Present variables
  if (result.present.length > 0) {
    lines.push(chalk.bold('Set variables:'));
    for (const status of result.present) {
      const categoryLabel = chalk.gray(`[${status.category}]`);
      lines.push(`  ${chalk.green('✓')} ${chalk.cyan(status.name)} ${categoryLabel}`);
      if (status.description) {
        lines.push(`      ${chalk.gray(status.description)}`);
      }
    }
    lines.push('');
  }

  // Missing required variables
  if (result.missing.length > 0) {
    lines.push(chalk.bold.red('Missing required variables:'));
    for (const status of result.missing) {
      const categoryLabel = chalk.gray(`[${status.category}]`);
      lines.push(`  ${chalk.red('✗')} ${chalk.cyan(status.name)} ${categoryLabel}`);
      if (status.description) {
        lines.push(`      ${chalk.gray(status.description)}`);
      }
    }
    lines.push('');
  }

  // Optional variables
  if (result.optionalMissing.length > 0) {
    lines.push(chalk.bold('Optional variables not set:'));
    for (const status of result.optionalMissing) {
      const categoryLabel = chalk.gray(`[${status.category}]`);
      lines.push(
        `  ${chalk.yellow('○')} ${chalk.cyan(status.name)} ${categoryLabel} ${chalk.gray('(optional)')}`,
      );
      if (status.description) {
        lines.push(`      ${chalk.gray(status.description)}`);
      }
    }
    lines.push('');
  }

  // Instructions
  if (result.missing.length > 0) {
    lines.push(chalk.bold('To fix:'));
    lines.push(`  1. Set the missing environment variables, or`);
    lines.push(
      `  2. Run ${chalk.cyan('manifest preflight --generate-example')} to create a .env.example file`,
    );
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Preflight command handler
 */
export async function preflightCommand(options: PreflightOptions = {}): Promise<void> {
  const cwd = options.cwd ?? process.cwd();

  // Run the checks
  const result = await runEnvChecks(cwd);

  // Handle --generate-example
  if (options.generateExample) {
    const content = generateEnvExampleContent(result);
    const outputPath = options.output
      ? path.isAbsolute(options.output)
        ? options.output
        : path.join(cwd, options.output)
      : path.join(cwd, '.env.example');

    const { writeTextFile } = await import('../utils/dry-run-fs.js');
    await writeTextFile(outputPath, content, { dryRun: options.dryRun, cwd });

    if (options.dryRun) {
      console.log(chalk.cyan('dry-run: would create environment example file (not written)'));
      return;
    }

    console.log(chalk.bold.green('✓ Environment example file created!'));
    console.log('');
    console.log(chalk.bold(`File: ${outputPath}`));
    console.log('');
    console.log(chalk.gray('Copy this file to .env and fill in the values.'));
    console.log('');

    if (result.missing.length > 0) {
      console.log(
        chalk.yellow(`Note: ${result.missing.length} required variable(s) are currently missing.`),
      );
      console.log('');
    }

    return;
  }

  // Handle normal output
  if (options.format === 'json') {
    process.stdout.write(JSON.stringify(result, null, 2) + '\n');
  } else {
    console.log(formatTextResult(result));
  }

  // Exit with error code if check failed
  if (!result.ok) {
    process.exitCode = 1;
  }
}
