/**
 * DynamoDB Infrastructure Projection for Manifest IR.
 *
 * Generates CloudFormation and AWS CDK (TypeScript) table definitions from
 * the IR's `stores` declarations. Supports both per-entity tables and
 * single-table design patterns.
 *
 * Surfaces:
 *   - dynamodb.cloudformation → CloudFormation YAML template with table
 *     definitions, GSIs, and DynamoDB Streams configuration for the
 *     transactional outbox.
 *   - dynamodb.cdk            → AWS CDK TypeScript code (aws-cdk-lib) that
 *     provisions the same tables in a CDK Stack.
 *   - dynamodb.terraform      → Terraform HCL for the same resources.
 *
 * Design philosophy:
 *   - One table per entity by default (simplest, most common pattern)
 *   - Single-table design: detected when `config.singleTable` is true; all
 *     entities are mapped to one table with composite (pk, sk) keys.
 *   - Streams: the outbox table always gets NEW_AND_OLD_IMAGES stream
 *     specification. The data table gets KEYS_ONLY streams unless the IR
 *     has event reactions that need full item context.
 */

import type { IR, IRStore, IREntity } from '../../ir';
import { DYNAMODB_DESCRIPTOR_META } from './descriptor-meta.js';
import type {
  ProjectionTarget,
  ProjectionRequest,
  ProjectionResult,
  ProjectionArtifact,
  ProjectionDiagnostic,
} from '../interface';

// ============================================================================
// Surface constants
// ============================================================================

export const SURFACE_CLOUDFORMATION = 'dynamodb.cloudformation' as const;
export const SURFACE_CDK = 'dynamodb.cdk' as const;
export const SURFACE_TERRAFORM = 'dynamodb.terraform' as const;
export const SURFACES = [SURFACE_CLOUDFORMATION, SURFACE_CDK, SURFACE_TERRAFORM] as const;

export interface DynamoDBProjectionOptions {
  /**
   * When true, emit a single-table design (all entities share one table).
   * Detected automatically when any store config sets `singleTable: true`.
   * Default: false.
   */
  singleTable?: boolean;
  /** Billing mode for provisioned tables. Default: PAY_PER_REQUEST. */
  billingMode?: 'PAY_PER_REQUEST' | 'PROVISIONED';
  /** Stack/app name for resource naming. Default: 'manifest'. */
  stackName?: string;
}

// ============================================================================
// Helpers
// ============================================================================

function isDynamoDBTarget(target: string): boolean {
  return target === 'dynamodb';
}

function getDynamoDBStores(ir: IR): IRStore[] {
  return (ir.stores ?? []).filter((s) => isDynamoDBTarget(s.target));
}

function hasSingleTableConfig(ir: IR): boolean {
  return (ir.stores ?? []).some(
    (s) => isDynamoDBTarget(s.target) && (s.config?.singleTable as unknown) === true,
  );
}

function entityFromIR(ir: IR, entityName: string): IREntity | undefined {
  return ir.entities.find((e) => e.name === entityName);
}

// ============================================================================
// CloudFormation generator
// ============================================================================

function generateCloudFormation(ir: IR, opts: DynamoDBProjectionOptions): string {
  const dynStores = getDynamoDBStores(ir);
  const singleTable = opts.singleTable ?? hasSingleTableConfig(ir);
  const stackName = opts.stackName ?? 'manifest';
  const billingMode = opts.billingMode ?? 'PAY_PER_REQUEST';

  const lines: string[] = [];
  lines.push(`AWSTemplateFormatVersion: '2010-09-09'`);
  lines.push(`Description: DynamoDB tables for ${stackName} (generated by Manifest)`);
  lines.push(`Resources:`);

  if (singleTable) {
    // Single-table design: one table for all entities
    const tableName = `${stackName}-main-table`;
    lines.push(`  ${stackName.replace(/[^a-zA-Z0-9]/g, '')}MainTable:`);
    lines.push(`    Type: AWS::DynamoDB::Table`);
    lines.push(`    Properties:`);
    lines.push(`      TableName: ${tableName}`);
    lines.push(`      BillingMode: ${billingMode}`);
    lines.push(`      AttributeDefinitions:`);
    lines.push(`        - AttributeName: pk`);
    lines.push(`          AttributeType: S`);
    lines.push(`        - AttributeName: sk`);
    lines.push(`          AttributeType: S`);
    lines.push(`      KeySchema:`);
    lines.push(`        - AttributeName: pk`);
    lines.push(`          KeyType: HASH`);
    lines.push(`        - AttributeName: sk`);
    lines.push(`          KeyType: RANGE`);
    lines.push(`      StreamSpecification:`);
    lines.push(`        StreamViewType: NEW_AND_OLD_IMAGES`);
    lines.push(``);
  } else {
    // One table per entity
    for (const store of dynStores) {
      const entity = entityFromIR(ir, store.entity);
      const resourceName = `${store.entity}Table`.replace(/[^a-zA-Z0-9]/g, '');
      const tableName = `${stackName}-${store.entity.toLowerCase()}-table`;
      lines.push(`  ${resourceName}:`);
      lines.push(`    Type: AWS::DynamoDB::Table`);
      lines.push(`    Properties:`);
      lines.push(`      TableName: ${tableName}`);
      lines.push(`      BillingMode: ${billingMode}`);
      lines.push(`      AttributeDefinitions:`);
      lines.push(`        - AttributeName: id`);
      lines.push(`          AttributeType: S`);
      lines.push(`      KeySchema:`);
      lines.push(`        - AttributeName: id`);
      lines.push(`          KeyType: HASH`);
      lines.push(`      StreamSpecification:`);
      lines.push(`        StreamViewType: KEYS_ONLY`);
      lines.push(``);
      // Entity reference for clarity (not enforced)
      if (entity) {
        lines.push(`  # Entity: ${entity.name} (${entity.properties.length} properties)`);
      }
    }
  }

  // Outbox table for transactional outbox pattern
  lines.push(`  ${stackName.replace(/[^a-zA-Z0-9]/g, '')}OutboxTable:`);
  lines.push(`    Type: AWS::DynamoDB::Table`);
  lines.push(`    Properties:`);
  lines.push(`      TableName: ${stackName}-outbox-table`);
  lines.push(`      BillingMode: ${billingMode}`);
  lines.push(`      AttributeDefinitions:`);
  lines.push(`        - AttributeName: pk`);
  lines.push(`          AttributeType: S`);
  lines.push(`        - AttributeName: sk`);
  lines.push(`          AttributeType: S`);
  lines.push(`      KeySchema:`);
  lines.push(`        - AttributeName: pk`);
  lines.push(`          KeyType: HASH`);
  lines.push(`        - AttributeName: sk`);
  lines.push(`          KeyType: RANGE`);
  lines.push(`      StreamSpecification:`);
  lines.push(`        StreamViewType: NEW_AND_OLD_IMAGES`);
  lines.push(``);

  lines.push(`Outputs:`);
  if (singleTable) {
    lines.push(`  MainTableName:`);
    lines.push(`    Value: !Ref ${stackName.replace(/[^a-zA-Z0-9]/g, '')}MainTable`);
    lines.push(`    Export:`);
    lines.push(`      Name: ${stackName}-main-table-name`);
  } else {
    for (const store of dynStores) {
      const resourceName = `${store.entity}Table`.replace(/[^a-zA-Z0-9]/g, '');
      lines.push(`  ${store.entity}TableName:`);
      lines.push(`    Value: !Ref ${resourceName}`);
      lines.push(`    Export:`);
      lines.push(`      Name: ${stackName}-${store.entity.toLowerCase()}-table-name`);
    }
  }
  lines.push(`  OutboxTableName:`);
  lines.push(`    Value: !Ref ${stackName.replace(/[^a-zA-Z0-9]/g, '')}OutboxTable`);
  lines.push(`    Export:`);
  lines.push(`      Name: ${stackName}-outbox-table-name`);

  return lines.join('\n') + '\n';
}

// ============================================================================
// AWS CDK generator
// ============================================================================

function generateCDK(ir: IR, opts: DynamoDBProjectionOptions): string {
  const dynStores = getDynamoDBStores(ir);
  const singleTable = opts.singleTable ?? hasSingleTableConfig(ir);
  const stackName = opts.stackName ?? 'manifest';
  const billingMode = opts.billingMode ?? 'PAY_PER_REQUEST';

  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * AWS CDK stack for ${stackName} DynamoDB tables.`);
  lines.push(` * Generated by Manifest — do not edit by hand.`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`import { Stack, StackProps } from 'aws-cdk-lib';`);
  lines.push(`import { Construct } from 'constructs';`);
  lines.push(`import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';`);
  lines.push(``);
  lines.push(`export class ${capitalize(stackName)}DynamoDBStack extends Stack {`);
  lines.push(`  constructor(scope: Construct, id: string, props?: StackProps) {`);
  lines.push(`    super(scope, id, props);`);
  lines.push(``);

  if (singleTable) {
    lines.push(`    // Single-table design: all entities share one table`);
    lines.push(`    this.mainTable = new dynamodb.Table(this, 'MainTable', {`);
    lines.push(`      tableName: '${stackName}-main-table',`);
    lines.push(`      partitionKey: { name: 'pk', type: dynamodb.AttributeType.STRING },`);
    lines.push(`      sortKey: { name: 'sk', type: dynamodb.AttributeType.STRING },`);
    lines.push(`      billingMode: dynamodb.BillingMode.${billingMode},`);
    lines.push(`      stream: dynamodb.StreamViewType.NEW_AND_OLD_IMAGES,`);
    lines.push(`    });`);
  } else {
    for (const store of dynStores) {
      const varName = `${store.entity.toLowerCase()}Table`;
      lines.push(`    // ${store.entity} entity table`);
      lines.push(`    this.${varName} = new dynamodb.Table(this, '${store.entity}Table', {`);
      lines.push(`      tableName: '${stackName}-${store.entity.toLowerCase()}-table',`);
      lines.push(`      partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },`);
      lines.push(`      billingMode: dynamodb.BillingMode.${billingMode},`);
      lines.push(`      stream: dynamodb.StreamViewType.KEYS_ONLY,`);
      lines.push(`    });`);
      lines.push(``);
    }
  }

  lines.push(`    // Transactional outbox table (DynamoDB Streams enabled)`);
  lines.push(`    this.outboxTable = new dynamodb.Table(this, 'OutboxTable', {`);
  lines.push(`      tableName: '${stackName}-outbox-table',`);
  lines.push(`      partitionKey: { name: 'pk', type: dynamodb.AttributeType.STRING },`);
  lines.push(`      sortKey: { name: 'sk', type: dynamodb.AttributeType.STRING },`);
  lines.push(`      billingMode: dynamodb.BillingMode.${billingMode},`);
  lines.push(`      stream: dynamodb.StreamViewType.NEW_AND_OLD_IMAGES,`);
  lines.push(`    });`);
  lines.push(`  }`);
  lines.push(``);

  // Property declarations
  if (singleTable) {
    lines.push(`  public readonly mainTable: dynamodb.Table;`);
  } else {
    for (const store of dynStores) {
      const varName = `${store.entity.toLowerCase()}Table`;
      lines.push(`  public readonly ${varName}: dynamodb.Table;`);
    }
  }
  lines.push(`  public readonly outboxTable: dynamodb.Table;`);
  lines.push(`}`);
  lines.push(``);

  return lines.join('\n');
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ============================================================================
// Terraform generator
// ============================================================================

function generateTerraform(ir: IR, opts: DynamoDBProjectionOptions): string {
  const dynStores = getDynamoDBStores(ir);
  const singleTable = opts.singleTable ?? hasSingleTableConfig(ir);
  const stackName = opts.stackName ?? 'manifest';

  const lines: string[] = [];
  lines.push(`# Terraform HCL for ${stackName} DynamoDB tables.`);
  lines.push(`# Generated by Manifest - do not edit by hand.`);
  lines.push(``);
  lines.push(`terraform {`);
  lines.push(`  required_providers {`);
  lines.push(`    aws = { source = "hashicorp/aws" }`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`provider "aws" { region = var.aws_region }`);
  lines.push(``);
  lines.push(`variable "aws_region" { default = "us-east-1" }`);
  lines.push(``);

  if (singleTable) {
    lines.push(`resource "aws_dynamodb_table" "main" {`);
    lines.push(`  name         = "${stackName}-main-table"`);
    lines.push(`  billing_mode = "PAY_PER_REQUEST"`);
    lines.push(`  hash_key     = "pk"`);
    lines.push(`  range_key    = "sk"`);
    lines.push(`  stream_enabled   = true`);
    lines.push(`  stream_view_type = "NEW_AND_OLD_IMAGES"`);
    lines.push(`  attribute { name = "pk" type = "S" }`);
    lines.push(`  attribute { name = "sk" type = "S" }`);
    lines.push(`}`);
    lines.push(``);
  } else {
    for (const store of dynStores) {
      lines.push(`resource "aws_dynamodb_table" "${store.entity.toLowerCase()}" {`);
      lines.push(`  name         = "${stackName}-${store.entity.toLowerCase()}-table"`);
      lines.push(`  billing_mode = "PAY_PER_REQUEST"`);
      lines.push(`  hash_key     = "id"`);
      lines.push(`  stream_enabled   = true`);
      lines.push(`  stream_view_type = "KEYS_ONLY"`);
      lines.push(`  attribute { name = "id" type = "S" }`);
      lines.push(`}`);
      lines.push(``);
    }
  }

  lines.push(`resource "aws_dynamodb_table" "outbox" {`);
  lines.push(`  name         = "${stackName}-outbox-table"`);
  lines.push(`  billing_mode = "PAY_PER_REQUEST"`);
  lines.push(`  hash_key     = "pk"`);
  lines.push(`  range_key    = "sk"`);
  lines.push(`  stream_enabled   = true`);
  lines.push(`  stream_view_type = "NEW_AND_OLD_IMAGES"`);
  lines.push(`  attribute { name = "pk" type = "S" }`);
  lines.push(`  attribute { name = "sk" type = "S" }`);
  lines.push(`}`);

  return lines.join('\n') + '\n';
}

// ============================================================================
// Projection target
// ============================================================================

export class DynamoDBProjection implements ProjectionTarget {
  readonly name = 'dynamodb';
  readonly description =
    'Generates AWS DynamoDB infrastructure (CloudFormation, CDK, Terraform) from Manifest IR stores';
  readonly surfaces = SURFACES;
  readonly descriptorMeta = DYNAMODB_DESCRIPTOR_META;

  generate(ir: IR, request: ProjectionRequest): ProjectionResult {
    const artifacts: ProjectionArtifact[] = [];
    const diagnostics: ProjectionDiagnostic[] = [];
    const opts = (request.options ?? {}) as DynamoDBProjectionOptions;

    const dynStores = getDynamoDBStores(ir);
    if (dynStores.length === 0) {
      diagnostics.push({
        severity: 'info',
        code: 'dynamodb.no-stores',
        message: 'No dynamodb store targets found in IR; emitting outbox table only',
      });
    }

    switch (request.surface) {
      case SURFACE_CLOUDFORMATION: {
        artifacts.push({
          id: 'dynamodb.cloudformation',
          pathHint: 'infrastructure/dynamodb.yaml',
          contentType: 'yaml',
          code: generateCloudFormation(ir, opts),
        });
        break;
      }
      case SURFACE_CDK: {
        artifacts.push({
          id: 'dynamodb.cdk',
          pathHint: 'infrastructure/dynamodb-stack.ts',
          contentType: 'typescript',
          code: generateCDK(ir, opts),
        });
        break;
      }
      case SURFACE_TERRAFORM: {
        artifacts.push({
          id: 'dynamodb.terraform',
          pathHint: 'infrastructure/dynamodb.tf',
          contentType: 'hcl',
          code: generateTerraform(ir, opts),
        });
        break;
      }
      default: {
        diagnostics.push({
          severity: 'error',
          code: 'dynamodb.unknown-surface',
          message: `Unknown surface "${request.surface}". Valid surfaces: ${SURFACES.join(', ')}`,
        });
      }
    }

    return { artifacts, diagnostics };
  }
}
