/**
 * Tests for the GraphQL SDL projection.
 *
 * Verifies:
 * - Projection metadata (name, surfaces, description)
 * - Entity type generation with typed fields
 * - Query type with list and detail resolvers
 * - Mutation type mapped to commands
 * - Subscription type mapped to events
 * - Input type generation for command parameters
 * - @auth directive generation from policies
 * - Custom scalar detection (DateTime, UUID, etc.)
 * - Enum type generation
 * - Computed properties in entity types
 * - Relationship fields
 * - Resolver stub generation
 * - Deterministic output
 * - Edge cases (empty IR, unknown surfaces)
 */

import { describe, it, expect } from 'vitest';
import { compileToIR } from '../../ir-compiler';
import { GraphQLProjection } from './generator';
// Static import: pulling the full registry graph through a dynamic import
// inside a test body can exceed the 5s test timeout under full-suite load.
// Registration stays lazy — it happens inside getProjection(), not at import.
import { getProjection } from '../registry';

describe('GraphQLProjection', () => {
  const projection = new GraphQLProjection();

  function firstCode(result: ReturnType<typeof projection.generate>): string {
    expect(result.artifacts.length).toBeGreaterThan(0);
    return result.artifacts[0].code;
  }

  function makeMinimalIR(overrides: Record<string, unknown> = {}) {
    return {
      version: '1.0' as const,
      provenance: {
        contentHash: 'abc123',
        compilerVersion: '0.3.21',
        schemaVersion: '1.0',
        compiledAt: '2026-01-01T00:00:00.000Z',
      },
      modules: [],
      values: [],
      entities: [],
      enums: [],
      stores: [],
      events: [],
      commands: [],
      policies: [],
      ...overrides,
    };
  }

  // ========================================================================
  // Projection metadata
  // ========================================================================

  describe('projection metadata', () => {
    it('has correct name, description, and surfaces', () => {
      expect(projection.name).toBe('graphql');
      expect(projection.description).toContain('GraphQL');
      expect(projection.surfaces).toContain('graphql.schema');
      expect(projection.surfaces).toContain('graphql.resolvers');
    });

    it('is registered as a built-in projection', () => {
      const p = getProjection('graphql');
      expect(p).toBeDefined();
      expect(p!.name).toBe('graphql');
    });
  });

  // ========================================================================
  // graphql.schema surface — basic structure
  // ========================================================================

  describe('graphql.schema surface — basic structure', () => {
    it('generates SDL with header comment', async () => {
      const source = `entity Widget { property required id: string }`;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('# Generated by Manifest GraphQL Projection');
      expect(sdl).toContain('# Do not edit manually');
    });

    it('generates entity type with fields', async () => {
      const source = `
        entity Widget {
          property required id: string
          property required name: string
          property description: string?
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('type Widget {');
      expect(sdl).toContain('id: String!');
      expect(sdl).toContain('name: String!');
      expect(sdl).toContain('description: String');
    });

    it('generates Query type with list and detail operations', async () => {
      const source = `
        entity Widget {
          property required id: string
          property required name: string
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('type Query {');
      expect(sdl).toContain('widgets: [Widget!]!');
      expect(sdl).toContain('widget(id: ID!): Widget');
    });

    it('returns correct artifact metadata', async () => {
      const source = `entity Widget { property id: string }`;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      expect(schemaResult.artifacts).toHaveLength(1);

      const artifact = schemaResult.artifacts[0];
      expect(artifact.id).toBe('graphql.schema');
      expect(artifact.pathHint).toBe('schema.graphql');
      expect(artifact.contentType).toBe('graphql');
    });
  });

  // ========================================================================
  // Type mapping
  // ========================================================================

  describe('type mapping', () => {
    it('maps IR scalar types to GraphQL types', async () => {
      const source = `
        entity TypeTest {
          property str: string
          property num: number
          property bool: boolean
          property intVal: int
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('str: String!');
      expect(sdl).toContain('num: Float!');
      expect(sdl).toContain('bool: Boolean!');
      expect(sdl).toContain('intVal: Int!');
    });

    it('handles nullable types', async () => {
      const source = `
        entity NullableTest {
          property name: string?
          property count: number?
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      // Nullable fields should NOT have !
      expect(sdl).toMatch(/name: String\b[^!]/);
      expect(sdl).toMatch(/count: Float\b[^!]/);
    });

    it('detects custom scalars and declares them', async () => {
      const source = `
        entity EventRecord {
          property required id: uuid
          property createdAt: datetime
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('scalar DateTime');
      expect(sdl).toContain('scalar UUID');
    });

    it('maps array types to GraphQL lists', () => {
      const ir = makeMinimalIR({
        entities: [{
          name: 'Widget',
          properties: [{
            name: 'tags',
            type: { name: 'array', generic: { name: 'string', nullable: false }, nullable: false },
            modifiers: [],
          }],
          computedProperties: [],
          relationships: [],
          commands: [],
          constraints: [],
          policies: [],
        }],
      });

      const schemaResult = projection.generate(ir, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('tags: [String!]!');
    });
  });

  // ========================================================================
  // Command → Mutation mapping
  // ========================================================================

  describe('command to mutation mapping', () => {
    it('generates Mutation type for entity commands', async () => {
      const source = `
        entity Widget {
          property required id: string
          property status: string = "draft"
          command release() {
            guard self.status == "draft"
            mutate status = "released"
          }
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('type Mutation {');
      expect(sdl).toContain('widgetRelease: Widget');
    });

    it('generates input types for commands with parameters', async () => {
      const source = `
        entity Widget {
          property required id: string
          command assign(userId: string, priority: number) {
            mutate status = "assigned"
          }
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('input WidgetAssignInput {');
      expect(sdl).toContain('userId: String!');
      expect(sdl).toContain('priority: Float!');
      expect(sdl).toContain('widgetAssign(input: WidgetAssignInput!): Widget');
    });

    it('includes guard info in mutation descriptions', async () => {
      const source = `
        entity Widget {
          property required id: string
          property status: string = "pending"
          command complete() {
            guard self.status == "in_progress"
            mutate status = "completed"
          }
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('Guards: 1 guard');
    });

    it('warns about commands without entities', () => {
      const ir = makeMinimalIR({
        commands: [{
          name: 'orphanCommand',
          module: undefined,
          entity: undefined,
          parameters: [],
          guards: [],
          actions: [],
          emits: [],
        }],
      });

      const schemaResult = projection.generate(ir, { surface: 'graphql.schema' });
      expect(schemaResult.diagnostics.some(d => d.code === 'COMMAND_NO_ENTITY')).toBe(true);
    });
  });

  // ========================================================================
  // Event → Subscription mapping
  // ========================================================================

  describe('event to subscription mapping', () => {
    it('generates Subscription type from events', () => {
      const ir = makeMinimalIR({
        events: [
          {
            name: 'widgetCreated',
            channel: 'widget.created',
            payload: [
              { name: 'widgetId', type: { name: 'string', nullable: false }, required: true },
              { name: 'name', type: { name: 'string', nullable: false }, required: true },
            ],
          },
        ],
      });

      const schemaResult = projection.generate(ir, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('type Subscription {');
      expect(sdl).toContain('widgetCreated: WidgetCreatedPayload!');
    });

    it('generates event payload types', () => {
      const ir = makeMinimalIR({
        events: [
          {
            name: 'widgetUpdated',
            channel: 'widget.updated',
            payload: [
              { name: 'widgetId', type: { name: 'string', nullable: false }, required: true },
              { name: 'changes', type: { name: 'string', nullable: true }, required: false },
            ],
          },
        ],
      });

      const schemaResult = projection.generate(ir, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('type WidgetUpdatedPayload {');
      expect(sdl).toContain('widgetId: String!');
      expect(sdl).toContain('changes: String');
    });

    it('omits subscriptions when option is disabled', () => {
      const ir = makeMinimalIR({
        events: [
          {
            name: 'widgetCreated',
            channel: 'widget.created',
            payload: [
              { name: 'widgetId', type: { name: 'string', nullable: false }, required: true },
            ],
          },
        ],
      });

      const schemaResult = projection.generate(ir, {
        surface: 'graphql.schema',
        options: { includeSubscriptions: false },
      });
      const sdl = firstCode(schemaResult);

      expect(sdl).not.toContain('type Subscription');
      expect(sdl).not.toContain('WidgetCreatedPayload');
    });
  });

  // ========================================================================
  // Policy → @auth directive
  // ========================================================================

  describe('policy to auth directive', () => {
    it('generates @auth directive on entities with policies', async () => {
      const source = `
        entity Widget {
          property required id: string
          policy canView read: true
          policy canEdit write: user.role == "admin"
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('@auth(requires:');
    });

    it('generates auth directive definition when policies exist', async () => {
      const source = `
        entity Widget {
          property required id: string
          policy canView read: true
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('directive @auth(requires: [String!]!) on OBJECT | FIELD_DEFINITION');
    });

    it('omits auth directives when option is disabled', async () => {
      const source = `
        entity Widget {
          property required id: string
          policy canView read: true
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, {
        surface: 'graphql.schema',
        options: { includeAuthDirectives: false },
      });
      const sdl = firstCode(schemaResult);

      expect(sdl).not.toContain('@auth');
      expect(sdl).not.toContain('directive @auth');
    });
  });

  // ========================================================================
  // Enum types
  // ========================================================================

  describe('enum types', () => {
    it('generates enum type definitions', () => {
      const ir = makeMinimalIR({
        enums: [{
          name: 'Status',
          values: [
            { name: 'DRAFT' },
            { name: 'PUBLISHED' },
            { name: 'ARCHIVED' },
          ],
        }],
      });

      const schemaResult = projection.generate(ir, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('enum Status {');
      expect(sdl).toContain('DRAFT');
      expect(sdl).toContain('PUBLISHED');
      expect(sdl).toContain('ARCHIVED');
    });

    it('includes labels as descriptions on enum values', () => {
      const ir = makeMinimalIR({
        enums: [{
          name: 'Priority',
          values: [
            { name: 'LOW', label: 'Low priority' },
            { name: 'HIGH', label: 'High priority' },
          ],
        }],
      });

      const schemaResult = projection.generate(ir, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('"Low priority"');
      expect(sdl).toContain('"High priority"');
    });

    it('omits enums when option is disabled', () => {
      const ir = makeMinimalIR({
        enums: [{
          name: 'Status',
          values: [{ name: 'DRAFT' }],
        }],
      });

      const schemaResult = projection.generate(ir, {
        surface: 'graphql.schema',
        options: { includeEnums: false },
      });
      const sdl = firstCode(schemaResult);

      expect(sdl).not.toContain('enum Status');
    });
  });

  // ========================================================================
  // Computed properties
  // ========================================================================

  describe('computed properties', () => {
    it('includes computed properties in entity type', async () => {
      const source = `
        entity OrderItem {
          property required id: string
          property price: number = 0
          property quantity: number = 1
          computed subtotal: number = price * quantity
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('subtotal: Float!');
      expect(sdl).toContain('Computed:');
    });

    it('omits computed properties when option is disabled', async () => {
      const source = `
        entity OrderItem {
          property required id: string
          property price: number = 0
          property quantity: number = 1
          computed subtotal: number = price * quantity
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, {
        surface: 'graphql.schema',
        options: { includeComputedProperties: false },
      });
      const sdl = firstCode(schemaResult);

      expect(sdl).not.toContain('subtotal');
    });
  });

  // ========================================================================
  // Resolver stubs (graphql.resolvers surface)
  // ========================================================================

  describe('graphql.resolvers surface', () => {
    it('generates resolver stubs with correct imports', async () => {
      const source = `
        entity Widget {
          property required id: string
          property required name: string
          command activate() {
            mutate status = "active"
          }
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const resolverResult = projection.generate(result.ir!, { surface: 'graphql.resolvers' });
      const code = firstCode(resolverResult);

      expect(code).toContain("import { createManifestRuntime } from '@/lib/manifest-runtime'");
      expect(code).toContain("import { database } from '@/lib/database'");
    });

    it('generates query resolvers with direct DB access', async () => {
      const source = `
        entity Widget {
          property required id: string
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const resolverResult = projection.generate(result.ir!, { surface: 'graphql.resolvers' });
      const code = firstCode(resolverResult);

      expect(code).toContain('database.widget.findMany()');
      expect(code).toContain('database.widget.findUnique');
    });

    it('generates mutation resolvers using runtime.runCommand', async () => {
      const source = `
        entity Widget {
          property required id: string
          command release() {
            mutate status = "released"
          }
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const resolverResult = projection.generate(result.ir!, { surface: 'graphql.resolvers' });
      const code = firstCode(resolverResult);

      // Writes MUST use runtime.runCommand
      expect(code).toContain("runtime.runCommand('Widget', 'release'");
      expect(code).not.toContain('database.widget.update');
    });

    it('generates subscription resolvers for events', () => {
      const ir = makeMinimalIR({
        entities: [{
          name: 'Widget',
          properties: [{ name: 'id', type: { name: 'string', nullable: false }, modifiers: ['required'] }],
          computedProperties: [],
          relationships: [],
          commands: [],
          constraints: [],
          policies: [],
        }],
        events: [{
          name: 'widgetCreated',
          channel: 'widget.created',
          payload: [
            { name: 'widgetId', type: { name: 'string', nullable: false }, required: true },
          ],
        }],
      });

      const resolverResult = projection.generate(ir, { surface: 'graphql.resolvers' });
      const code = firstCode(resolverResult);

      expect(code).toContain('subscriptionResolvers');
      expect(code).toContain("'widget.created'");
      expect(code).toContain('PubSub');
    });

    it('uses custom import paths', async () => {
      const source = `entity Widget { property id: string }`;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const resolverResult = projection.generate(result.ir!, {
        surface: 'graphql.resolvers',
        options: {
          runtimeImportPath: '@/custom/runtime',
          databaseImportPath: '@/custom/db',
        },
      });
      const code = firstCode(resolverResult);

      expect(code).toContain("from '@/custom/runtime'");
      expect(code).toContain("from '@/custom/db'");
    });

    it('returns correct artifact metadata', async () => {
      const source = `entity Widget { property id: string }`;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const resolverResult = projection.generate(result.ir!, { surface: 'graphql.resolvers' });
      expect(resolverResult.artifacts).toHaveLength(1);

      const artifact = resolverResult.artifacts[0];
      expect(artifact.id).toBe('graphql.resolvers');
      expect(artifact.pathHint).toBe('resolvers.ts');
      expect(artifact.contentType).toBe('typescript');
    });

    it('returns info diagnostic when resolvers disabled', () => {
      const ir = makeMinimalIR();
      const resolverResult = projection.generate(ir, {
        surface: 'graphql.resolvers',
        options: { includeResolverStubs: false },
      });

      expect(resolverResult.artifacts).toHaveLength(0);
      expect(resolverResult.diagnostics).toHaveLength(1);
      expect(resolverResult.diagnostics[0].code).toBe('RESOLVERS_DISABLED');
    });
  });

  // ========================================================================
  // Determinism
  // ========================================================================

  describe('determinism', () => {
    it('produces identical output for identical IR', () => {
      const ir = makeMinimalIR({
        entities: [
          {
            name: 'Widget',
            properties: [
              { name: 'id', type: { name: 'string', nullable: false }, modifiers: ['required'] },
              { name: 'name', type: { name: 'string', nullable: false }, modifiers: [] },
            ],
            computedProperties: [],
            relationships: [],
            commands: ['publish'],
            constraints: [],
            policies: [],
          },
          {
            name: 'Gadget',
            properties: [
              { name: 'id', type: { name: 'string', nullable: false }, modifiers: ['required'] },
            ],
            computedProperties: [],
            relationships: [],
            commands: [],
            constraints: [],
            policies: [],
          },
        ],
        commands: [{
          name: 'publish',
          entity: 'Widget',
          parameters: [],
          guards: [],
          actions: [
            { kind: 'mutate', target: 'self.status', expression: { kind: 'literal', value: { kind: 'string', value: 'published' } } },
          ],
          emits: [],
        }],
      });

      const result1 = projection.generate(ir, { surface: 'graphql.schema' });
      const result2 = projection.generate(ir, { surface: 'graphql.schema' });

      expect(firstCode(result1)).toBe(firstCode(result2));
    });

    it('sorts entities deterministically', async () => {
      const source = `
        entity Zebra { property id: string }
        entity Alpha { property id: string }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      const alphaIdx = sdl.indexOf('type Alpha');
      const zebraIdx = sdl.indexOf('type Zebra');
      expect(alphaIdx).toBeLessThan(zebraIdx);
    });
  });

  // ========================================================================
  // Edge cases
  // ========================================================================

  describe('edge cases', () => {
    it('handles empty IR', () => {
      const ir = makeMinimalIR();
      const schemaResult = projection.generate(ir, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('# Generated by Manifest GraphQL Projection');
      // No Query, Mutation, or Subscription types for empty IR
      expect(sdl).not.toContain('type Query');
      expect(sdl).not.toContain('type Mutation');
      expect(sdl).not.toContain('type Subscription');
    });

    it('returns error for unknown surface', () => {
      const ir = makeMinimalIR();
      const result = projection.generate(ir, { surface: 'unknown.surface' });

      expect(result.artifacts).toHaveLength(0);
      expect(result.diagnostics).toHaveLength(1);
      expect(result.diagnostics[0].severity).toBe('error');
      expect(result.diagnostics[0].code).toBe('UNKNOWN_SURFACE');
    });

    it('handles entity with no properties', async () => {
      const source = `entity Empty { }`;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('type Empty {');
    });

    it('handles command with no parameters', async () => {
      const source = `
        entity Widget {
          property required id: string
          command activate() {
            mutate status = "active"
          }
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      // Should not have an input type for parameterless command
      expect(sdl).not.toContain('WidgetActivateInput');
      expect(sdl).toContain('widgetActivate: Widget');
    });

    it('handles multiple entities and commands', async () => {
      const source = `
        entity Widget {
          property required id: string
          property required name: string
          command release() { mutate status = "released" }
        }
        entity Gadget {
          property required id: string
          command activate(userId: string) { mutate status = "active" }
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('type Widget {');
      expect(sdl).toContain('type Gadget {');
      expect(sdl).toContain('widgetRelease: Widget');
      expect(sdl).toContain('gadgetActivate(input: GadgetActivateInput!): Gadget');
    });

    it('handles entity with default values', async () => {
      const source = `
        entity Widget {
          property required id: string
          property count: number = 42
          property label: string = "untitled"
        }
      `;
      const result = await compileToIR(source);
      expect(result.ir).not.toBeNull();

      const schemaResult = projection.generate(result.ir!, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('Default: 42');
      expect(sdl).toContain('Default: "untitled"');
    });
  });

  // ========================================================================
  // Relationships
  // ========================================================================

  describe('relationships', () => {
    it('generates relationship fields', () => {
      const ir = makeMinimalIR({
        entities: [{
          name: 'Widget',
          properties: [
            { name: 'id', type: { name: 'string', nullable: false }, modifiers: ['required'] },
          ],
          computedProperties: [],
          relationships: [
            { name: 'parts', kind: 'hasMany', target: 'Part' },
            { name: 'owner', kind: 'belongsTo', target: 'User' },
          ],
          commands: [],
          constraints: [],
          policies: [],
        }],
      });

      const schemaResult = projection.generate(ir, { surface: 'graphql.schema' });
      const sdl = firstCode(schemaResult);

      expect(sdl).toContain('parts: [Part!]!');
      expect(sdl).toContain('owner: User');
    });
  });
});
