/**
 * Config G6 — Prisma multiSchema.splitFiles.
 *
 * When enabled, emit a root schema (datasource + generator) plus one `.prisma`
 * file per database schema containing that schema's models/enums. Prisma merges
 * every `.prisma` file under the schema folder (no import statements).
 */

import type { ProjectionArtifact, ProjectionDiagnostic } from '../interface.js';
import type { PrismaProjectionOptions } from './options.js';

export interface SchemaTaggedBlock {
  schemaName: string;
  code: string;
}

export interface SplitFilesPlan {
  enabled: boolean;
  dir: string;
}

const DEFAULT_SPLIT_DIR = 'prisma/schemas';

/** Sanitize a DB schema name into a stable relative filename stem. */
export function schemaFileStem(schemaName: string): string {
  const cleaned = schemaName
    .trim()
    .replace(/[^A-Za-z0-9_-]+/g, '_')
    .replace(/^_+|_+$/g, '');
  return cleaned.length > 0 ? cleaned : 'schema';
}

export function resolveSplitFilesPlan(
  options: PrismaProjectionOptions,
): { plan: SplitFilesPlan | undefined; diagnostics: ProjectionDiagnostic[] } {
  const split = options.multiSchema?.splitFiles;
  if (!split || split.enabled !== true) {
    return { plan: undefined, diagnostics: [] };
  }
  if (!options.multiSchema?.enabled) {
    return {
      plan: undefined,
      diagnostics: [
        {
          severity: 'error',
          code: 'PRISMA_SPLITFILES_REQUIRES_MULTISCHEMA',
          message:
            'multiSchema.splitFiles.enabled is true but multiSchema.enabled is not. ' +
            'Enable multiSchema first, or remove splitFiles.',
        },
      ],
    };
  }
  const dir =
    typeof split.dir === 'string' && split.dir.trim().length > 0
      ? split.dir.trim().replace(/\\/g, '/').replace(/\/+$/, '')
      : DEFAULT_SPLIT_DIR;
  return { plan: { enabled: true, dir }, diagnostics: [] };
}

function joinDir(dir: string, fileName: string): string {
  return `${dir.replace(/\/+$/, '')}/${fileName}`;
}

/**
 * Build root + per-schema artifacts. Root keeps datasource/generator; each
 * schema file holds models/enums for that schema (still carrying @@schema).
 */
export function buildSplitPrismaArtifacts(args: {
  headerStr: string;
  rootPathHint: string;
  modelBlocks: SchemaTaggedBlock[];
  enumBlocks: SchemaTaggedBlock[];
  splitDir: string;
}): ProjectionArtifact[] {
  const bySchema = new Map<string, string[]>();
  const ensure = (schema: string): string[] => {
    let list = bySchema.get(schema);
    if (!list) {
      list = [];
      bySchema.set(schema, list);
    }
    return list;
  };
  for (const block of args.modelBlocks) {
    ensure(block.schemaName).push(block.code);
  }
  for (const block of args.enumBlocks) {
    ensure(block.schemaName).push(block.code);
  }

  const schemaNames = [...bySchema.keys()].sort((a, b) => a.localeCompare(b));
  const rootHeader = [
    args.headerStr.trimEnd(),
    '',
    '// Multi-file Prisma schema (multiSchema.splitFiles).',
    `// Sibling files under ${args.splitDir}/ are merged by Prisma.`,
    ...(schemaNames.length === 0
      ? ['// No persistent entities found in IR.']
      : schemaNames.map((s) => `//   - ${schemaFileStem(s)}.prisma  (@@schema("${s}"))`)),
    '',
  ].join('\n');

  const artifacts: ProjectionArtifact[] = [
    {
      id: 'prisma.schema',
      pathHint: args.rootPathHint,
      contentType: 'prisma',
      code: rootHeader,
    },
  ];

  for (const schemaName of schemaNames) {
    const blocks = bySchema.get(schemaName) ?? [];
    const stem = schemaFileStem(schemaName);
    const body =
      blocks.length > 0 ? `${blocks.join('\n\n')}\n` : '// Empty schema partition.\n';
    artifacts.push({
      id: `prisma.schema.${stem}`,
      pathHint: joinDir(args.splitDir, `${stem}.prisma`),
      contentType: 'prisma',
      code:
        '// Auto-generated by @manifest/projection-prisma\n' +
        `// Schema partition: ${schemaName}\n` +
        '// DO NOT EDIT — regenerate with the projection.\n\n' +
        body,
    });
  }

  return artifacts;
}
