import type { IR, IRSchedule } from '../../ir.js';
import type { ProjectionArtifact, ProjectionDiagnostic } from '../interface.js';
export type ScheduleGeneratorOptions = {
  runtimeImportPath: string;
};

function cronSchedules(ir: IR): IRSchedule[] {
  return (ir.schedules ?? []).filter(s => s.trigger.kind === 'cron' && s.trigger.cron);
}

function scheduleRoutePath(scheduleName: string): string {
  const segment = scheduleName.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
  return `app/api/cron/${segment}/route.ts`;
}

export function generateScheduleCronRoutes(
  ir: IR,
  options: ScheduleGeneratorOptions,
): { artifacts: ProjectionArtifact[]; diagnostics: ProjectionDiagnostic[] } {
  const diagnostics: ProjectionDiagnostic[] = [];
  const schedules = cronSchedules(ir);

  if (schedules.length === 0) {
    diagnostics.push({
      severity: 'info',
      code: 'NEXTJS_NO_CRON_SCHEDULES',
      message: 'No cron schedules in IR; skipping nextjs.schedule surface.',
    });
    return { artifacts: [], diagnostics };
  }

  const runtimeImport = options.runtimeImportPath ?? '@/lib/manifest-runtime';
  const artifacts: ProjectionArtifact[] = [];

  for (const schedule of schedules) {
    const cron = schedule.trigger.cron!;
    const code = [
      '// Auto-generated by @manifest/projection-nextjs (nextjs.schedule)',
      '// DO NOT EDIT — regenerate with the projection.',
      '',
      `import { createManifestRuntime } from "${runtimeImport}";`,
      '',
      'export const runtime = "nodejs";',
      '',
      `export async function GET(request: Request) {`,
      '  const auth = request.headers.get("authorization");',
      '  const secret = process.env.CRON_SECRET;',
      '  if (secret && auth !== `Bearer ${secret}`) {',
      '    return new Response("Unauthorized", { status: 401 });',
      '  }',
      '  const runtime = await createManifestRuntime({ source: "cron" });',
      `  const result = await runtime.runSchedule("${schedule.name}");`,
      '  return Response.json(result);',
      '}',
      '',
      `// vercel.json cron: { "path": "/api/cron/${schedule.name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()}", "schedule": "${cron}" }`,
      '',
    ].join('\n');

    artifacts.push({
      id: `nextjs.schedule.${schedule.name}`,
      pathHint: scheduleRoutePath(schedule.name),
      contentType: 'typescript',
      code,
    });
  }

  return { artifacts, diagnostics };
}
