import type { IR, IRSchedule } from '../../ir.js';
import type { ProjectionArtifact, ProjectionDiagnostic } from '../interface.js';

/** Import specifier for the async-job drain helper (a package subpath, app-provided). */
const JOBS_WORKER_IMPORT = '@angriff36/manifest/jobs/worker';
/** Fixed cadence for the maintenance routes (approval expiry, job drain). */
const MAINTENANCE_CRON = '*/5 * * * *';
const APPROVAL_EXPIRY_SEGMENT = 'manifest-approval-expiry';
const JOBS_DRAIN_SEGMENT = 'manifest-jobs-drain';

export type ScheduleGeneratorOptions = {
  runtimeImportPath: string;
  /** Next.js app dir (e.g. 'app/api'); cron routes land under `${appDir}/cron/...`. */
  appDir: string;
};

/** A single entry in the emitted vercel.json `crons` array. */
interface CronRegistration {
  path: string;
  schedule: string;
}

function cronSchedules(ir: IR): IRSchedule[] {
  return (ir.schedules ?? []).filter((s) => s.trigger.kind === 'cron' && s.trigger.cron);
}

/** True when any entity declares an approval with a timeout (⇒ approvals can expire). */
function hasExpiringApprovals(ir: IR): boolean {
  return (ir.entities ?? []).some((e) =>
    (e.approvals ?? []).some((a) => typeof a.timeout === 'number'),
  );
}

/** True when any command is declared `async` (⇒ its jobs need draining). */
function hasAsyncCommands(ir: IR): boolean {
  return (ir.commands ?? []).some((c) => c.async === true);
}

/** kebab-case a schedule name for its route segment. */
function toSegment(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

/** File path (pathHint) for a cron route under the configured app dir. */
function cronRoutePath(appDir: string, segment: string): string {
  return `${appDir}/cron/${segment}/route.ts`;
}

/**
 * URL path Vercel invokes for a cron route under `appDir`. Next.js maps files
 * under the `app` directory to routes by stripping everything up to and
 * including `app`, so `app/api/cron/x/route.ts` → `/api/cron/x` and
 * `src/app/api/cron/x/route.ts` → `/api/cron/x`.
 */
function cronRouteUrl(appDir: string, segment: string): string {
  const segs = appDir.split('/').filter(Boolean);
  const appIdx = segs.lastIndexOf('app');
  const prefix = appIdx >= 0 ? segs.slice(appIdx + 1) : segs;
  return ['', ...prefix, 'cron', segment].join('/');
}

/** Shared CRON_SECRET bearer guard lines for every generated cron route. */
function authGuardLines(): string[] {
  return [
    '  const auth = request.headers.get("authorization");',
    '  const secret = process.env.CRON_SECRET;',
    '  if (secret && auth !== `Bearer ${secret}`) {',
    '    return new Response("Unauthorized", { status: 401 });',
    '  }',
  ];
}

function scheduleRouteCode(runtimeImport: string, scheduleName: string): string {
  return [
    '// Auto-generated by @manifest/projection-nextjs (nextjs.schedule)',
    '// DO NOT EDIT — regenerate with the projection.',
    '// Registered in the generated vercel.json crons array.',
    '',
    `import { createManifestRuntime } from "${runtimeImport}";`,
    '',
    'export const runtime = "nodejs";',
    '',
    'export async function GET(request: Request) {',
    ...authGuardLines(),
    '  const runtime = await createManifestRuntime({ source: "cron" });',
    `  const result = await runtime.runSchedule("${scheduleName}");`,
    '  return Response.json(result);',
    '}',
    '',
  ].join('\n');
}

function approvalExpiryRouteCode(runtimeImport: string): string {
  return [
    '// Auto-generated by @manifest/projection-nextjs (nextjs.schedule)',
    '// DO NOT EDIT — regenerate with the projection.',
    '// Sweeps approvals whose timeout has elapsed. Registered in vercel.json.',
    '//',
    '// NOTE: expireApprovals() sweeps the requests the runtime holds in memory.',
    '// For durable expiry across processes, back createManifestRuntime with an',
    '// approvalStore and expire from it here.',
    '',
    `import { createManifestRuntime } from "${runtimeImport}";`,
    '',
    'export const runtime = "nodejs";',
    '',
    'export async function GET(request: Request) {',
    ...authGuardLines(),
    '  const runtime = await createManifestRuntime({ source: "cron" });',
    '  const expired = await runtime.expireApprovals();',
    '  return Response.json({ expired: expired.length });',
    '}',
    '',
  ].join('\n');
}

function jobsDrainRouteCode(runtimeImport: string): string {
  return [
    '// Auto-generated by @manifest/projection-nextjs (nextjs.schedule)',
    '// DO NOT EDIT — regenerate with the projection.',
    '// Drains queued async-command jobs in one pass. Registered in vercel.json.',
    '',
    `import { createManifestRuntime } from "${runtimeImport}";`,
    `import { drainJobsOnce } from "${JOBS_WORKER_IMPORT}";`,
    '',
    'export const runtime = "nodejs";',
    '',
    'export async function GET(request: Request) {',
    ...authGuardLines(),
    '  const runtime = await createManifestRuntime({ source: "cron" });',
    '  const drained = await drainJobsOnce(runtime);',
    '  return Response.json({ drained: drained.length });',
    '}',
    '',
  ].join('\n');
}

/** Serialize the crons registrations to a strict vercel.json (no comments — Vercel rejects them). */
function vercelJson(crons: CronRegistration[]): string {
  return `${JSON.stringify({ crons }, null, 2)}\n`;
}

/**
 * Emit the Next.js cron routes for a program's schedules plus the maintenance
 * routes it needs (approval expiry, async-job drain), and a single vercel.json
 * that registers them all so Vercel invokes them on schedule — no separate cron
 * script to host. Non-Vercel hosts run `startScheduleWorker` from
 * `@angriff36/manifest/schedule-worker` instead.
 */
export function generateScheduleCronRoutes(
  ir: IR,
  options: ScheduleGeneratorOptions,
): { artifacts: ProjectionArtifact[]; diagnostics: ProjectionDiagnostic[] } {
  const diagnostics: ProjectionDiagnostic[] = [];
  const artifacts: ProjectionArtifact[] = [];
  const runtimeImport = options.runtimeImportPath ?? '@/lib/manifest-runtime';
  const appDir = options.appDir ?? 'app/api';
  const crons: CronRegistration[] = [];

  for (const schedule of cronSchedules(ir)) {
    const segment = toSegment(schedule.name);
    artifacts.push({
      id: `nextjs.schedule.${schedule.name}`,
      pathHint: cronRoutePath(appDir, segment),
      contentType: 'typescript',
      code: scheduleRouteCode(runtimeImport, schedule.name),
    });
    crons.push({ path: cronRouteUrl(appDir, segment), schedule: schedule.trigger.cron! });
  }

  if (hasExpiringApprovals(ir)) {
    artifacts.push({
      id: 'nextjs.schedule.__approval_expiry__',
      pathHint: cronRoutePath(appDir, APPROVAL_EXPIRY_SEGMENT),
      contentType: 'typescript',
      code: approvalExpiryRouteCode(runtimeImport),
    });
    crons.push({ path: cronRouteUrl(appDir, APPROVAL_EXPIRY_SEGMENT), schedule: MAINTENANCE_CRON });
  }

  if (hasAsyncCommands(ir)) {
    artifacts.push({
      id: 'nextjs.schedule.__jobs_drain__',
      pathHint: cronRoutePath(appDir, JOBS_DRAIN_SEGMENT),
      contentType: 'typescript',
      code: jobsDrainRouteCode(runtimeImport),
    });
    crons.push({ path: cronRouteUrl(appDir, JOBS_DRAIN_SEGMENT), schedule: MAINTENANCE_CRON });
  }

  if (artifacts.length === 0) {
    diagnostics.push({
      severity: 'info',
      code: 'NEXTJS_NO_SCHEDULE_ARTIFACTS',
      message:
        'No cron schedules, expiring approvals, or async commands in IR; skipping nextjs.schedule surface.',
    });
    return { artifacts, diagnostics };
  }

  artifacts.push({
    id: 'nextjs.schedule.vercel-json',
    pathHint: 'vercel.json',
    contentType: 'json',
    code: vercelJson(crons),
  });
  diagnostics.push({
    severity: 'info',
    code: 'NEXTJS_VERCEL_CRON_REGISTRATION',
    message:
      `Emitted vercel.json with ${crons.length} cron registration(s). Merge its "crons" array into your existing vercel.json if you already have one. ` +
      'Non-Vercel hosts: run startScheduleWorker() from @angriff36/manifest/schedule-worker instead.',
  });

  return { artifacts, diagnostics };
}
