import type { IR, IRWebhook } from '../../ir.js';
import type { ProjectionArtifact, ProjectionDiagnostic } from '../interface.js';

/** Package subpath for the runtime webhook handler (owned by src/manifest/webhooks). */
const WEBHOOKS_IMPORT = '@angriff36/manifest/webhooks';

export type WebhookGeneratorOptions = {
  /** Import specifier for the createManifestRuntime companion (same as the cron/dispatcher routes). */
  runtimeImportPath: string;
  /** Next.js app dir (e.g. 'app/api'). Only its `app` root matters here — see appRouterRoot. */
  appDir: string;
};

/**
 * Resolve the Next.js App Router root directory from a configured `appDir`.
 *
 * Webhook paths are ABSOLUTE and are registered with external providers (Stripe,
 * GitHub, …), so a webhook declared at `/webhooks/stripe` MUST be served at that
 * exact URL — it cannot move under the api `appDir` (typically `app/api`). The
 * App Router derives a URL from a file by stripping everything up to and
 * including the `app` directory, so a route served at `/webhooks/stripe` must
 * live at `<appRoot>/webhooks/stripe/route.ts` where `<appRoot>` ends at `app`:
 *   appDir 'app/api'      → appRoot 'app'      → app/webhooks/stripe/route.ts
 *   appDir 'src/app/api'  → appRoot 'src/app'  → src/app/webhooks/stripe/route.ts
 * An appDir with no `app` segment falls back to the conventional `app/` root.
 */
function appRouterRoot(appDir: string): string {
  const segs = appDir.split('/').filter(Boolean);
  const appIdx = segs.lastIndexOf('app');
  if (appIdx >= 0) return segs.slice(0, appIdx + 1).join('/');
  return 'app';
}

/** File path (pathHint) for a webhook route so its served URL equals the declared path. */
function webhookRoutePath(appDir: string, declaredPath: string): string {
  const rel = declaredPath.replace(/^\/+/, '');
  return `${appRouterRoot(appDir)}/${rel}/route.ts`;
}

/** The HTTP method the route handler must export (webhooks default to POST). */
function webhookMethod(webhook: IRWebhook): string {
  return (webhook.method ?? 'POST').toUpperCase();
}

function webhookRouteCode(runtimeImport: string, webhook: IRWebhook): string {
  const method = webhookMethod(webhook);
  return [
    `// Auto-generated by @manifest/projection-nextjs (nextjs.webhook)`,
    `// Webhook "${webhook.name}" — ${method} ${webhook.path}`,
    '// DO NOT EDIT — regenerate with the projection.',
    '//',
    '// Webhooks authenticate via their signature (HMAC over the RAW request',
    "// body), NOT the app's auth middleware. handleWebhookRequest verifies the",
    '// signature per the IR webhook declaration before dispatching the command,',
    '// so this route is intentionally emitted without an auth guard.',
    '',
    `import { createManifestRuntime } from "${runtimeImport}";`,
    `import { handleWebhookRequest } from "${WEBHOOKS_IMPORT}";`,
    'import { NextResponse } from "next/server";',
    '',
    'export const runtime = "nodejs";',
    '',
    `export async function ${method}(request: Request) {`,
    // RAW body: HMAC is computed over the exact bytes, so read text() before any
    // JSON parsing. request.text() consumes the stream once — do not also call json().
    '  const rawBody = await request.text();',
    '  const manifestRuntime = await createManifestRuntime({ source: "webhook" });',
    '  const result = await handleWebhookRequest(manifestRuntime, {',
    '    method: request.method,',
    `    path: ${JSON.stringify(webhook.path)},`,
    '    headers: Object.fromEntries(request.headers),',
    '    rawBody,',
    '    query: Object.fromEntries(new URL(request.url).searchParams),',
    '  });',
    '  return NextResponse.json(result.body, { status: result.status });',
    '}',
    '',
  ].join('\n');
}

/**
 * Emit one Next.js App Router route per declared webhook, each served at the
 * webhook's DECLARED absolute path (independent of the api appDir). The route
 * bridges the framework Request into the frozen WebhookHttpRequest shape (raw
 * body, headers, query) and delegates to handleWebhookRequest, which owns
 * signature verification, idempotency, payload transform, and command dispatch.
 *
 * Emits nothing (with an info diagnostic) when the IR declares no webhooks, so
 * the common program does not get an empty surface.
 */
export function generateWebhookRoutes(
  ir: IR,
  options: WebhookGeneratorOptions,
): { artifacts: ProjectionArtifact[]; diagnostics: ProjectionDiagnostic[] } {
  const diagnostics: ProjectionDiagnostic[] = [];
  const artifacts: ProjectionArtifact[] = [];
  const runtimeImport = options.runtimeImportPath ?? '@/lib/manifest-runtime';
  const appDir = options.appDir ?? 'app/api';

  for (const webhook of ir.webhooks ?? []) {
    artifacts.push({
      id: `nextjs.webhook.${webhook.name}`,
      pathHint: webhookRoutePath(appDir, webhook.path),
      contentType: 'typescript',
      code: webhookRouteCode(runtimeImport, webhook),
    });
  }

  if (artifacts.length === 0) {
    diagnostics.push({
      severity: 'info',
      code: 'NEXTJS_NO_WEBHOOK_ARTIFACTS',
      message: 'No webhooks declared in IR; skipping nextjs.webhook surface.',
    });
  }

  return { artifacts, diagnostics };
}
