/**
 * Computed-property emission for the Convex projection.
 *
 * Strategy (see docs/internal/proposals/2026-07-14-convex-computed-properties.md):
 *   - `helpers` (default): emit convex/computed.ts of pure functions per entity.
 *   - `inline`: materialize self-only computeds into get/list returns.
 *
 * Unresolved expressions always emit CONVEX_UNRESOLVED_COMPUTED — never silent drop.
 */

import type { IR, IRComputedProperty, IREntity } from '../../ir';
import type { ProjectionDiagnostic } from '../interface';
import { renderExpression, type RenderScope } from './expression.js';
import { isPersistentEntity } from './persist.js';
import type { NormalizedOptions } from './generator.js';

export interface ComputedResult {
  code: string;
  diagnostics: ProjectionDiagnostic[];
}

const GENERATED_HEADER = '// GENERATED by the Manifest → Convex projection. DO NOT EDIT.';

/**
 * Emit a `convex/computed.ts` module of pure helper functions.
 * One export per entity that has at least one fully-resolved computed:
 *   `export function computeOrder(doc: Record<string, any>): Record<string, any>`
 */
export function generateComputedHelpers(
  ir: IR,
  _options: NormalizedOptions,
): ComputedResult {
  const diagnostics: ProjectionDiagnostic[] = [];
  const blocks: string[] = [];
  const scope: RenderScope = { selfVar: 'doc' };

  for (const entity of ir.entities) {
    if (!isPersistentEntity(entity, ir)) continue;
    if (!entity.computedProperties.length) continue;

    const fields: { name: string; code: string }[] = [];
    for (const cp of entity.computedProperties) {
      const rendered = renderComputed(entity, cp, scope);
      diagnostics.push(...rendered.diagnostics);
      if (rendered.code) fields.push({ name: cp.name, code: rendered.code });
    }
    if (fields.length === 0) continue;

    const assigns = fields.map((f) => `    ${f.name}: ${f.code},`).join('\n');
    blocks.push(
      `/** Self-only computed fields for ${entity.name}. Pass the stored document. */\n` +
        `export function compute${entity.name}(doc: Record<string, any>): Record<string, any> {\n` +
        `  return {\n${assigns}\n  };\n` +
        `}`,
    );
  }

  const code =
    `${GENERATED_HEADER}\n` +
    `// Computed property helpers (${blocks.length} entit(y/ies)).\n` +
    `// Call from queries/mutations or app code; never stored.\n\n` +
    (blocks.length ? blocks.join('\n\n') + '\n' : `// No resolvable computed properties.\n`);

  return { code, diagnostics };
}

/**
 * Inline computed field assignments for a single-doc return (get path).
 * Returns empty when strategy is not inline or no fields resolve.
 */
export function renderInlineComputedFields(
  entity: IREntity,
  docVar: string,
): { fields: { name: string; code: string }[]; diagnostics: ProjectionDiagnostic[] } {
  const diagnostics: ProjectionDiagnostic[] = [];
  const fields: { name: string; code: string }[] = [];
  const scope: RenderScope = { selfVar: docVar };
  for (const cp of entity.computedProperties) {
    const rendered = renderComputed(entity, cp, scope);
    diagnostics.push(...rendered.diagnostics);
    if (rendered.code) fields.push({ name: cp.name, code: rendered.code });
  }
  return { fields, diagnostics };
}

function renderComputed(
  entity: IREntity,
  cp: IRComputedProperty,
  scope: RenderScope,
): { code: string | null; diagnostics: ProjectionDiagnostic[] } {
  const { code, unresolved } = renderExpression(cp.expression, scope);
  if (unresolved.length) {
    return {
      code: null,
      diagnostics: [
        {
          severity: 'warning',
          code: 'CONVEX_UNRESOLVED_COMPUTED',
          entity: entity.name,
          message:
            `Computed '${entity.name}.${cp.name}' unresolved (${unresolved.join('; ')}); ` +
            `omitted from Convex helpers. Prefer self-only expressions, or declare ` +
            `relation aggregates via reaction count params.`,
        },
      ],
    };
  }
  return { code, diagnostics: [] };
}
