/**
 * Computed-property emission for the Convex projection.
 *
 * Strategy (see docs/internal/proposals/2026-07-14-convex-computed-properties.md):
 *   - `helpers` (default): emit convex/computed.ts of pure functions per entity.
 *   - `inline`: materialize self-only computeds into get/list returns.
 *
 * Unresolved expressions always emit CONVEX_UNRESOLVED_COMPUTED — never silent drop.
 * Multi-hop aggregates also emit an async hydrate helper that preloads every
 * relationship depth onto the document before the sync compute helper runs.
 */

import type { IR, IRComputedProperty, IREntity, IRExpression } from '../../ir';
import type { ProjectionDiagnostic } from '../interface';
import { planAndRenderAggregateHydration } from './aggregate-hydrate.js';
import { codeUsesDocType, resolveHasManyDocElementType } from './count-of-preload.js';
import { renderExpression, type RenderScope } from './expression.js';
import type { NormalizedOptions } from './generator.js';
import { isPersistentEntity } from './persist.js';

export interface ComputedResult {
  code: string;
  diagnostics: ProjectionDiagnostic[];
}

const GENERATED_HEADER = '// GENERATED by the Manifest → Convex projection. DO NOT EDIT.';

/**
 * Emit a `convex/computed.ts` module of pure helper functions.
 * One export per entity that has at least one fully-resolved computed:
 *   `export function computeOrder(doc: Record<string, any>): Record<string, any>`
 * When computeds need nested relation graphs, also emit:
 *   `export async function hydrateComputedRelationsForOrder(ctx, doc): Promise<void>`
 */
export function generateComputedHelpers(ir: IR, options: NormalizedOptions): ComputedResult {
  const diagnostics: ProjectionDiagnostic[] = [];
  const blocks: string[] = [];
  let entityCount = 0;

  for (const entity of ir.entities) {
    if (!isPersistentEntity(entity, ir)) continue;
    if (!entity.computedProperties.length) continue;

    const scope: RenderScope = {
      selfVar: 'doc',
      resolveCollectionElementType: (collection) =>
        resolveHasManyDocElementType(entity, collection, options),
    };
    const fields: { name: string; code: string }[] = [];
    for (const cp of entity.computedProperties) {
      const rendered = renderComputed(entity, cp, scope);
      diagnostics.push(...rendered.diagnostics);
      if (rendered.code) fields.push({ name: cp.name, code: rendered.code });
    }
    if (fields.length === 0) continue;
    entityCount += 1;

    const hydrate = renderEntityComputedHydration(
      ir,
      entity,
      options,
      '(doc as any)',
      'docId',
      '  ',
    );
    if (hydrate.lines.length > 0) {
      blocks.push(
        `/** Preload nested relations for ${entity.name} computeds (mutates doc in place). */\n` +
          `export async function hydrateComputedRelationsFor${entity.name}(ctx: any, doc: Record<string, any>): Promise<void> {\n` +
          `  const docId = doc._id;\n` +
          `${hydrate.lines.join('\n')}\n` +
          `}`,
      );
    }

    const assigns = fields.map((f) => `    ${f.name}: ${f.code},`).join('\n');
    blocks.push(
      `/** Self-only computed fields for ${entity.name}. Pass the stored document. */\n` +
        `export function compute${entity.name}(doc: Record<string, any>): Record<string, any> {\n` +
        `  return {\n${assigns}\n  };\n` +
        `}`,
    );
  }

  const body = blocks.length
    ? blocks.join('\n\n') + '\n'
    : `// No resolvable computed properties.\n`;
  const docImport = codeUsesDocType(body)
    ? `import type { Doc } from "./_generated/dataModel";\n\n`
    : '';
  const code =
    `${GENERATED_HEADER}\n` +
    `// Computed property helpers (${entityCount} entit(y/ies)).\n` +
    `// Call from queries/mutations or app code; never stored.\n\n` +
    docImport +
    body;

  return { code, diagnostics };
}

/** Hydration lines for an entity's computed expressions (empty when none need relations). */
export function renderEntityComputedHydration(
  ir: IR,
  entity: IREntity,
  options: NormalizedOptions,
  docExpr = '(doc as any)',
  docIdExpr = 'docId',
  baseIndent = '    ',
): { lines: string[]; exprs: IRExpression[] } {
  const exprs = entity.computedProperties.map((cp) => cp.expression);
  const planned = planAndRenderAggregateHydration(
    ir,
    entity,
    exprs,
    options,
    docIdExpr,
    docExpr,
    baseIndent,
  );
  return { lines: planned.lines, exprs };
}

/**
 * Inline computed field assignments for a single-doc return (get path).
 * Returns empty when strategy is not inline or no fields resolve.
 */
export function renderInlineComputedFields(
  entity: IREntity,
  docVar: string,
  options?: NormalizedOptions,
): { fields: { name: string; code: string }[]; diagnostics: ProjectionDiagnostic[] } {
  const diagnostics: ProjectionDiagnostic[] = [];
  const fields: { name: string; code: string }[] = [];
  const scope: RenderScope = {
    selfVar: docVar,
    resolveCollectionElementType: options
      ? (collection) => resolveHasManyDocElementType(entity, collection, options)
      : undefined,
  };
  for (const cp of entity.computedProperties) {
    const rendered = renderComputed(entity, cp, scope);
    diagnostics.push(...rendered.diagnostics);
    if (rendered.code) fields.push({ name: cp.name, code: rendered.code });
  }
  return { fields, diagnostics };
}

function renderComputed(
  entity: IREntity,
  cp: IRComputedProperty,
  scope: RenderScope,
): { code: string | null; diagnostics: ProjectionDiagnostic[] } {
  const { code, unresolved } = renderExpression(cp.expression, scope);
  if (unresolved.length) {
    return {
      code: null,
      diagnostics: [
        {
          severity: 'warning',
          code: 'CONVEX_UNRESOLVED_COMPUTED',
          entity: entity.name,
          message:
            `Computed '${entity.name}.${cp.name}' unresolved (${unresolved.join('; ')}); ` +
            `omitted from Convex helpers. Prefer self-only expressions, or declare ` +
            `relation aggregates via reaction count params.`,
        },
      ],
    };
  }
  return { code, diagnostics: [] };
}
