/**
 * Convex functions surfaces: `convex.queries` and `convex.mutations`.
 *
 * Queries are reactive reads over `ctx.db` (reads are not governed). Mutations
 * are governed writes: each IR command becomes a Convex `mutation` that runs the
 * command's policies → guards → constraints (rendered from IR via the
 * fail-closed expression resolver), applies the command's mutate actions,
 * appends an event row, and fires matched reactions.
 *
 * Governance is rendered FAIL CLOSED: any guard/policy/constraint the resolver
 * cannot fully map produces a hard diagnostic AND a denying `throw`, never a
 * silent pass.
 */

import type { IR, IRCommand, IRConstraint, IREntity, IRExpression, IRPolicy, IRReactionRule, IRValue } from '../../ir';
import type { ProjectionDiagnostic } from '../interface';
import { normalizeOptions } from './options.js';
import {
  resolveConvexTableName,
  collectFkTargets,
  buildValidator,
  isPersistentEntity,
  resolveEventsTableName,
  type NormalizedOptions,
} from './generator.js';
import { resolveConvexValidator } from './type-mapping.js';
import { renderExpression, type RenderScope } from './expression.js';

type Normalized = NormalizedOptions;

export interface FunctionsResult {
  code: string;
  diagnostics: ProjectionDiagnostic[];
}

const GENERATED_HEADER = '// GENERATED by the Manifest → Convex projection. DO NOT EDIT.';

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function persistentEntities(ir: IR): IREntity[] {
  return ir.entities.filter(e => isPersistentEntity(e, ir));
}

/**
 * Render an IR default value to a TS literal that satisfies a Convex validator.
 *
 * Two of the projection's type mappings are *representational*: `int`/`bigint`
 * map to `v.int64()` (a JS `bigint`) and `decimal`/`money` map to `v.string()`
 * (lossless decimal transport — Convex has no native Decimal). A structurally
 * faithful render of an IR `number` default (`1`) is the WRONG runtime type for
 * those validators — Convex rejects a JS number where it expects a bigint or a
 * string — so the create-mutation default fill would fail schema validation at
 * insert time. Coerce numeric leaves to the validator's representation.
 *
 * `validator` is the field's resolved expression (possibly `v.optional`/
 * `v.array`-wrapped); detection is structural so per-property `typeMappings`
 * overrides are honored. Arrays share their element validator, so it propagates
 * to elements; objects carry heterogeneous members the field validator does not
 * describe, so their members are rendered structurally (no coercion).
 */
function defaultToTs(value: IRValue, validator?: string): string {
  switch (value.kind) {
    case 'string': return JSON.stringify(value.value);
    case 'number':
      // int64 wants a bigint literal; a non-integer default on an int field is
      // an authoring contradiction — surface it as a type error, don't truncate.
      if (validator && /\bv\.int64\(\)/.test(validator) && Number.isInteger(value.value)) {
        return `${value.value}n`;
      }
      // decimal/money (and stringId FKs) transport as strings.
      if (validator && /\bv\.string\(\)/.test(validator)) {
        return JSON.stringify(String(value.value));
      }
      return String(value.value);
    case 'boolean': return String(value.value);
    case 'null': return 'null';
    case 'array': return `[${value.elements.map(el => defaultToTs(el, validator)).join(', ')}]`;
    case 'object': return `{${Object.entries(value.properties).map(([k, v]) => `${JSON.stringify(k)}: ${defaultToTs(v)}`).join(', ')}}`;
  }
}

/** Validator expression for a command parameter (FK-aware, no optional wrap). */
function paramValidator(typeName: string): string {
  return resolveConvexValidator(typeName, undefined, '') ?? 'v.any()';
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

export function generateQueries(ir: IR, rawOptions: Record<string, unknown> | undefined): FunctionsResult {
  const options = normalizeOptions(rawOptions);
  const diagnostics: ProjectionDiagnostic[] = [];
  const blocks: string[] = [];

  for (const entity of persistentEntities(ir)) {
    const table = resolveConvexTableName(entity.name, options);
    const fkTargets = collectFkTargets(entity, ir, options);

    // list<Entity>
    blocks.push(
      `export const list${entity.name} = query({\n` +
      `  args: {},\n` +
      `  handler: async (ctx) => {\n` +
      `    return await ctx.db.query("${table}").collect();\n` +
      `  },\n});`,
    );

    // get<Entity> by Convex _id
    blocks.push(
      `export const get${entity.name} = query({\n` +
      `  args: { id: v.id("${table}") },\n` +
      `  handler: async (ctx, { id }) => {\n` +
      `    return await ctx.db.get(id);\n` +
      `  },\n});`,
    );

    // list<Entity>By<Field> for indexed + reference fields
    const tenantProp = ir.tenant?.property;
    const indexFields = new Set<string>();
    for (const p of entity.properties) {
      if (p.name !== 'id' && p.modifiers.includes('indexed')) indexFields.add(p.name);
    }
    if (tenantProp && entity.properties.some(p => p.name === tenantProp)) indexFields.add(tenantProp);
    for (const fk of fkTargets.keys()) indexFields.add(fk);

    for (const field of indexFields) {
      const cap = field.charAt(0).toUpperCase() + field.slice(1);
      const target = fkTargets.get(field);
      const argType = target ? `v.id("${target}")` : 'v.string()';
      blocks.push(
        `export const list${entity.name}By${cap} = query({\n` +
        `  args: { ${field}: ${argType} },\n` +
        `  handler: async (ctx, { ${field} }) => {\n` +
        `    return await ctx.db.query("${table}").withIndex("by_${field}", (q) => q.eq("${field}", ${field})).collect();\n` +
        `  },\n});`,
      );
    }
  }

  // Convenience: recent rows from the system events table (when emitted).
  if (options.emitEventsTable) {
    blocks.push(
      `export const listRecentEvents = query({\n` +
      `  args: {},\n` +
      `  handler: async (ctx) => {\n` +
      `    return await ctx.db.query("${resolveEventsTableName(ir, options)}").order("desc").take(50);\n` +
      `  },\n});`,
    );
  }

  const code =
    `${GENERATED_HEADER}\n// ${blocks.length} query function(s).\n\n` +
    `import { query } from "./_generated/server";\n` +
    `import { v } from "convex/values";\n\n` +
    `${blocks.join('\n\n')}\n`;

  return { code, diagnostics };
}

// ---------------------------------------------------------------------------
// Mutations
// ---------------------------------------------------------------------------

/** Build the ROLE_PERMISSIONS map literal from IR roles' effective permissions. */
function roleMapLiteral(ir: IR): string {
  const map: Record<string, string[]> = {};
  for (const role of ir.roles ?? []) {
    const actions = new Set<string>();
    for (const perm of role.effectivePermissions ?? []) actions.add(perm.action);
    map[role.name] = [...actions].sort();
  }
  return JSON.stringify(map, null, 2);
}

interface CheckSpec {
  expr: IRExpression | undefined;
  /** denial message */
  message: string;
  /** diagnostic code emitted when unresolved */
  code: 'CONVEX_UNRESOLVED_POLICY' | 'CONVEX_UNRESOLVED_GUARD' | 'CONVEX_UNRESOLVED_CONSTRAINT';
  label: string;
}

/** Render governance checks fail-closed. Returns TS lines + diagnostics. */
function renderChecks(
  entityName: string,
  checks: CheckSpec[],
  scope: RenderScope,
): { lines: string[]; diagnostics: ProjectionDiagnostic[] } {
  const lines: string[] = [];
  const diagnostics: ProjectionDiagnostic[] = [];
  for (const c of checks) {
    const { code, unresolved } = renderExpression(c.expr, scope);
    if (unresolved.length > 0) {
      diagnostics.push({
        severity: 'error',
        code: c.code,
        entity: entityName,
        message: `${c.label}: could not resolve expression (${unresolved.join('; ')}). Emitted a denying throw (fail-closed).`,
      });
      lines.push(`    throw new Error(${JSON.stringify(`${c.label} unresolved — denied`)});`);
    } else {
      lines.push(`    if (!(${code})) throw new Error(${JSON.stringify(c.message)});`);
    }
  }
  return { lines, diagnostics };
}

/** Collect the policy/guard/constraint checks for a command, in runtime order. */
function commandChecks(ir: IR, cmd: IRCommand, policyMode: 'enforce' | 'skip'): CheckSpec[] {
  const checks: CheckSpec[] = [];
  if (policyMode !== 'skip') {
    for (const pName of cmd.policies ?? []) {
      const policy: IRPolicy | undefined = ir.policies.find(p => p.name === pName);
      if (!policy) continue;
      checks.push({ expr: policy.expression, message: policy.message ?? `Policy ${pName} denied`, code: 'CONVEX_UNRESOLVED_POLICY', label: `policy '${pName}'` });
    }
  }
  for (let i = 0; i < cmd.guards.length; i++) {
    checks.push({ expr: cmd.guards[i], message: `Guard ${i} failed`, code: 'CONVEX_UNRESOLVED_GUARD', label: `guard[${i}]` });
  }
  for (const c of (cmd.constraints ?? []) as IRConstraint[]) {
    if (c.severity && c.severity !== 'block') continue;
    checks.push({ expr: c.expression, message: c.message ?? c.messageTemplate ?? `Constraint ${c.code} failed`, code: 'CONVEX_UNRESOLVED_CONSTRAINT', label: `constraint '${c.code}'` });
  }
  return checks;
}

/** Render reaction fan-out for the events a command emits. */
function renderReactions(ir: IR, options: Normalized, emits: string[]): { lines: string[]; diagnostics: ProjectionDiagnostic[] } {
  const lines: string[] = [];
  const diagnostics: ProjectionDiagnostic[] = [];
  const matched = (ir.reactions ?? []).filter((r: IRReactionRule) => emits.includes(r.event));
  if (matched.length === 0) return { lines, diagnostics };
  lines.push('    // Reactions');
  const tenantProp = ir.tenant?.property;
  matched.forEach((reaction, idx) => {
    const targetTable = resolveConvexTableName(reaction.targetEntity, options);
    const targetEntity = ir.entities.find(e => e.name === reaction.targetEntity);
    const scope: RenderScope = { selfVar: 'doc', globals: ['payload', 'user', 'context', 'args'] };
    const paramEntries: string[] = [];
    const paramNamesSeen = new Set<string>();
    for (const p of reaction.params ?? []) {
      const { code, unresolved } = renderExpression(p.expression, scope);
      if (unresolved.length) {
        diagnostics.push({ severity: 'warning', code: 'CONVEX_UNRESOLVED_REACTION_PARAM', message: `reaction ${reaction.event}→${reaction.targetEntity}.${reaction.targetCommand} param '${p.name}' unresolved (${unresolved.join('; ')}); omitted.` });
        continue;
      }
      paramEntries.push(`${p.name}: ${code}`);
      paramNamesSeen.add(p.name);
    }
    // Tenant propagation: a reaction fires within the source entity's tenant, so
    // when it creates a tenant-scoped target, thread the source tenantId
    // (available as payload.<tenantProp>) unless an explicit param already set it.
    const targetIsTenantScoped = !!tenantProp && !!targetEntity?.properties.some(p => p.name === tenantProp);
    if (reaction.targetCommand === 'create' && targetIsTenantScoped && !paramNamesSeen.has(tenantProp!)) {
      paramEntries.unshift(`${tenantProp}: payload.${tenantProp}`);
    }
    if (reaction.targetCommand === 'create') {
      lines.push(`    await ctx.db.insert("${targetTable}", { ${paramEntries.join(', ')} });`);
    } else {
      const resolve = renderExpression(reaction.resolve, { selfVar: 'doc', globals: ['payload', 'user', 'context', 'args'] });
      const varName = `reactionTarget${idx}`;
      if (reaction.resolve?.kind === 'literal' && reaction.resolve.value.kind === 'null') {
        lines.push(`    // reaction ${reaction.event} → ${reaction.targetEntity}.${reaction.targetCommand} (resolve: null — no target id)`);
      } else if (resolve.unresolved.length) {
        diagnostics.push({ severity: 'warning', code: 'CONVEX_UNRESOLVED_REACTION_TARGET', message: `reaction ${reaction.event}→${reaction.targetEntity}.${reaction.targetCommand} target unresolved; skipped.` });
      } else {
        lines.push(`    const ${varName} = ${resolve.code};`);
        lines.push(`    if (${varName}) await ctx.db.patch(${varName}, { ${paramEntries.join(', ')} });`);
      }
    }
  });
  return { lines, diagnostics };
}

/** Render the event-row inserts for a command's emits. */
function renderEvents(eventsTable: string, entityName: string, emits: string[], idVar: string): string[] {
  return emits.map(ev =>
    `    await ctx.db.insert("${eventsTable}", { type: ${JSON.stringify(ev)}, entity: ${JSON.stringify(entityName)}, entityId: ${idVar}, payload: {}, createdAt: Date.now() });`,
  );
}

/**
 * Auth/context/payload bindings a handler needs, derived by scanning the body
 * for the identifiers it actually references (avoids both undefined-name and
 * unused-var errors). `payloadValue` is the expression `payload` binds to.
 */
function authBindings(bodyText: string): string[] {
  const lines: string[] = [];
  const refs = (token: string) => new RegExp(`\\b${token}\\b`).test(bodyText);
  if (refs('userRole')) lines.push(`    const userRole = (ctx as any).auth?.role ?? "anonymous";`);
  if (refs('user')) lines.push(`    const user = (ctx as any).auth ?? {};`);
  if (refs('context')) lines.push(`    const context = (ctx as any);`);
  return lines;
}

function generateMutation(ir: IR, options: Normalized, cmd: IRCommand): { code: string; diagnostics: ProjectionDiagnostic[] } | null {
  if (!cmd.entity) return null;
  const entity = ir.entities.find(e => e.name === cmd.entity);
  if (!entity || !isPersistentEntity(entity, ir)) return null;

  const diagnostics: ProjectionDiagnostic[] = [];
  const table = resolveConvexTableName(entity.name, options);
  const name = `${entity.name}_${cmd.name}`;
  const fkTargets = collectFkTargets(entity, ir, options);
  const isCreate = cmd.name === 'create';
  const paramNames = (cmd.parameters ?? []).map(p => p.name);

  if (isCreate) {
    // Unified create model. Every stored field must be reachable so the insert
    // satisfies the schema: it is either (a) set by a `mutate` action, (b) filled
    // from its default, or (c) exposed as a mutation argument the caller provides.
    // Command parameters that feed actions (and are not themselves fields) are
    // also exposed as args. All expressions resolve against `args`.
    const params = cmd.parameters ?? [];
    const scope: RenderScope = { selfVar: 'args' };
    const argLines: string[] = [];
    const argNames = new Set<string>();
    const docLines: string[] = [];

    // Fields set by mutate actions (mapped from params); not exposed as args.
    const mutates = (cmd.actions ?? []).filter(a => a.kind === 'mutate' && a.target);
    const targetSet = new Set(mutates.map(a => a.target as string));

    // Entity properties → args (unless action-set) + doc lines (with defaults).
    for (const p of entity.properties) {
      if (p.name === 'id' || targetSet.has(p.name)) continue;
      const { validator, diagnostics: vd } = buildValidator(entity, p, ir, options, fkTargets.get(p.name));
      diagnostics.push(...vd);
      if (!validator) continue;
      // Required AND no default → required arg; otherwise optional (caller may
      // omit; default fills in).
      const required = p.modifiers.includes('required') && !p.defaultValue;
      if (!argNames.has(p.name)) {
        argLines.push(`    ${p.name}: ${required ? validator : `v.optional(${validator})`}`);
        argNames.add(p.name);
      }
      docLines.push(`      ${p.name}: args.${p.name}${p.defaultValue ? ` ?? ${defaultToTs(p.defaultValue, validator)}` : ''}`);
    }

    // Command params that are not entity fields (they feed actions) → args.
    for (const p of params) {
      if (argNames.has(p.name)) continue;
      const validator = paramValidator(p.type.name);
      argLines.push(`    ${p.name}: ${p.required ? validator : `v.optional(${validator})`}`);
      argNames.add(p.name);
    }

    // mutate actions → doc fields (param → field mapping).
    for (const a of mutates) {
      const { code, unresolved } = renderExpression(a.expression, scope);
      if (unresolved.length) {
        diagnostics.push({ severity: 'warning', code: 'CONVEX_UNRESOLVED_ACTION', entity: entity.name, message: `create action '${a.target}' unresolved (${unresolved.join('; ')}); omitted.` });
        continue;
      }
      docLines.push(`      ${a.target}: ${code}`);
    }

    const checks = renderChecks(entity.name, commandChecks(ir, cmd, options.policyMode), scope);
    diagnostics.push(...checks.diagnostics);
    const events = renderEvents(resolveEventsTableName(ir, options), entity.name, cmd.emits ?? [], '_id');
    const reactions = renderReactions(ir, options, cmd.emits ?? []);
    diagnostics.push(...reactions.diagnostics);
    const tail = [...events, ...reactions.lines].join('\n');
    const payloadBinding = /\bpayload\b/.test(tail) ? `    const payload: Record<string, any> = { _id, ...doc };\n` : '';
    const bodyText = [...checks.lines, tail].join('\n');

    const body =
      `export const ${name} = mutation({\n` +
      `  args: {\n${argLines.join(',\n')}\n  },\n` +
      `  handler: async (ctx, args) => {\n` +
      (authBindings(bodyText).join('\n') ? authBindings(bodyText).join('\n') + '\n' : '') +
      `    const doc: Record<string, any> = {\n${docLines.join(',\n')}\n    };\n` +
      (checks.lines.length ? checks.lines.join('\n') + '\n' : '') +
      `    const _id = await ctx.db.insert("${table}", doc as any);\n` +
      payloadBinding +
      (tail ? tail + '\n' : '') +
      `    return { _id, ...doc };\n` +
      `  },\n});`;
    return { code: body, diagnostics };
  }

  // Non-create mutation
  const argLines = [`    docId: v.id("${table}")`];
  for (const p of cmd.parameters ?? []) {
    argLines.push(`    ${p.name}: ${p.required ? paramValidator(p.type.name) : `v.optional(${paramValidator(p.type.name)})`}`);
  }

  // Non-create: command params are destructured locals; self.x → doc.x.
  const checks = renderChecks(entity.name, commandChecks(ir, cmd, options.policyMode), { selfVar: 'doc', locals: paramNames });
  diagnostics.push(...checks.diagnostics);

  const updateLines: string[] = [];
  for (const a of cmd.actions ?? []) {
    if (a.kind !== 'mutate' || !a.target) continue;
    const { code, unresolved } = renderExpression(a.expression, { selfVar: 'doc', locals: paramNames });
    if (unresolved.length) {
      diagnostics.push({ severity: 'warning', code: 'CONVEX_UNRESOLVED_ACTION', entity: entity.name, message: `action mutate '${a.target}' unresolved (${unresolved.join('; ')}); omitted.` });
      continue;
    }
    updateLines.push(`      ${a.target}: ${code}`);
  }

  const events = renderEvents(resolveEventsTableName(ir, options), entity.name, cmd.emits ?? [], 'docId');
  const reactions = renderReactions(ir, options, cmd.emits ?? []);
  diagnostics.push(...reactions.diagnostics);

  const tail = [...events, ...reactions.lines].join('\n');
  const payloadBinding = /\bpayload\b/.test(tail) ? `    const payload: Record<string, any> = { ...doc, ...updates };\n` : '';
  const argDestructure = paramNames.length ? `, ${paramNames.join(', ')}` : '';
  const bodyText = [...checks.lines, ...updateLines, tail].join('\n');

  const body =
    `export const ${name} = mutation({\n` +
    `  args: {\n${argLines.join(',\n')}\n  },\n` +
    `  handler: async (ctx, { docId${argDestructure} }) => {\n` +
    (authBindings(bodyText).join('\n') ? authBindings(bodyText).join('\n') + '\n' : '') +
    `    const doc = await ctx.db.get(docId);\n` +
    `    if (!doc) throw new Error(${JSON.stringify(`${entity.name} not found`)});\n` +
    (checks.lines.length ? checks.lines.join('\n') + '\n' : '') +
    `    const updates = {\n${updateLines.join(',\n')}${updateLines.length ? '\n' : ''}    };\n` +
    `    await ctx.db.patch(docId, updates);\n` +
    payloadBinding +
    (tail ? tail + '\n' : '') +
    `    return { ...doc, ...updates };\n` +
    `  },\n});`;
  return { code: body, diagnostics };
}

export function generateMutations(ir: IR, rawOptions: Record<string, unknown> | undefined): FunctionsResult {
  const options = normalizeOptions(rawOptions);
  const diagnostics: ProjectionDiagnostic[] = [];
  const blocks: string[] = [];

  for (const cmd of ir.commands) {
    const m = generateMutation(ir, options, cmd);
    if (!m) continue;
    blocks.push(m.code);
    diagnostics.push(...m.diagnostics);
  }

  // Emit helpers only when the generated mutations actually reference them
  // (a policyMode:'skip' build may use neither), so there is no dead code.
  const body = blocks.join('\n\n');
  const helpers: string[] = [];
  if (/\bcheckRole\(/.test(body)) {
    helpers.push(
      `// Role hierarchy from IR (effective permissions after inheritance).\n` +
      `const ROLE_PERMISSIONS: Record<string, string[]> = ${roleMapLiteral(ir)};\n\n` +
      `function checkRole(userRole: string, action: string): boolean {\n` +
      `  const perms = ROLE_PERMISSIONS[userRole];\n` +
      `  return perms ? (perms.includes(action) || perms.includes("all")) : false;\n` +
      `}`,
    );
  }
  if (/\bflag\(/.test(body)) {
    helpers.push(`// Feature toggle (configurable). Not an authorization gate.\nfunction flag(_name?: string): boolean { return true; }`);
  }

  const policyNote = options.policyMode === 'skip' ? ' (policyMode: skip — authorization policies omitted)' : '';
  const code =
    `${GENERATED_HEADER}\n// ${blocks.length} mutation(s); roles: ${(ir.roles ?? []).length}; policies: ${ir.policies.length}.${policyNote}\n\n` +
    `import { mutation } from "./_generated/server";\n` +
    `import { v } from "convex/values";\n\n` +
    (helpers.length ? helpers.join('\n\n') + '\n\n' : '') +
    `${body}\n`;

  return { code, diagnostics };
}
