/**
 * Convex functions surfaces: `convex.queries` and `convex.mutations`.
 *
 * Queries are reactive reads over `ctx.db` (reads are not governed). Mutations
 * are governed writes: each IR command becomes a Convex `mutation` that runs the
 * command's policies → guards → constraints (rendered from IR via the
 * fail-closed expression resolver), applies the command's mutate actions,
 * appends an event row, and fires matched reactions.
 *
 * Governance is rendered FAIL CLOSED: any guard/policy/constraint the resolver
 * cannot fully map produces a hard diagnostic AND a denying `throw`, never a
 * silent pass.
 */

import type {
  IR,
  IRCommand,
  IRConstraint,
  IREntity,
  IRExpression,
  IRPolicy,
  IRReactionParam,
  IRReactionRule,
  IRValue,
} from '../../ir';
import type { ProjectionDiagnostic } from '../interface';
import { normalizeOptions } from './options.js';
import {
  resolveConvexTableName,
  collectFkTargets,
  collectReferenceFields,
  indexEntryToDef,
  buildValidator,
  isPersistentEntity,
  resolveEventsTableName,
  type NormalizedOptions,
} from './generator.js';
import { resolveConvexValidator } from './type-mapping.js';
import { ReactionPayloadCollisionPlanner } from './reactionPayloadCollision.js';
import { planAndRenderAggregateHydration } from './aggregate-hydrate.js';
import {
  codeUsesDocType,
  collectCountOfHasManyRels,
  resolveHasManyDocElementType,
} from './count-of-preload.js';
import { renderEntityComputedHydration, renderInlineComputedFields } from './computed.js';
import {
  renderExpression,
  isNullLiteral,
  type RenderScope,
  type RenderResult,
} from './expression.js';
import { renderTransitionChecks } from './transitions.js';
import {
  commandCreationEntry,
  commandCreationExportName,
  commandRunnerName,
} from './creation-entry.js';
import {
  convexCreateVersionDocLines,
  isConvexVersionManagedField,
  renderConvexUpdateVersionOcc,
} from './version-occ.js';
import { renderReadPolicies, resolveConvexReadVisibility } from './read-policies.js';
import {
  encryptedFieldNames,
  privateFieldNames,
  stripPrivateFromDoc,
  stripPrivateFromReturn,
  stripPrivateFromRows,
} from './privacy.js';
import {
  commandNeedsAfterSnapshot,
  computeBindingLines,
  renderCommandComputeBindings,
  renderEvents,
  unionEmitPayloadFields,
} from './event-payload.js';
import {
  appendCommandIdempotencyArg,
  commandIdempotencyEnabled,
  renderCommandIdempotencyEpilogue,
  renderCommandIdempotencyHelpers,
  renderCommandIdempotencyPrologue,
  renderCommandIdempotencyWrappedRunnerHandler,
} from './command-idempotency.js';
import { buildRelationDependencyPlan, type RelationDependency } from '../../relation-plan.js';

type Normalized = NormalizedOptions;

const reactionPayloadCollisionPlanner = new ReactionPayloadCollisionPlanner();

export interface FunctionsResult {
  code: string;
  diagnostics: ProjectionDiagnostic[];
}

const GENERATED_HEADER = '// GENERATED by the Manifest → Convex projection. DO NOT EDIT.';

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function persistentEntities(ir: IR): IREntity[] {
  return ir.entities.filter((e) => isPersistentEntity(e, ir));
}

const ENCRYPT_HELPER = `async function __encryptDoc(ctx: any, entity: string, fields: readonly string[], doc: Record<string, any>): Promise<Record<string, any>> {
  const out = { ...doc };
  for (const property of fields) {
    const value = out[property];
    if (value == null) continue;
    const { ciphertext, keyId } = await encrypt(String(value), { ctx, entity, property });
    out[property] = JSON.stringify({ v: 1, kid: keyId, ct: ciphertext });
  }
  return out;
}`;

const DECRYPT_HELPER = `async function __decryptDoc(ctx: any, entity: string, fields: readonly string[], doc: any): Promise<any> {
  if (!doc) return doc;
  const out = { ...doc } as Record<string, any>;
  for (const property of fields) {
    const raw = out[property];
    if (typeof raw !== "string") continue;
    let envelope: any;
    try { envelope = JSON.parse(raw); } catch { continue; }
    const looksEncrypted = envelope && typeof envelope === "object" && "v" in envelope && "kid" in envelope && "ct" in envelope;
    if (!looksEncrypted) continue;
    if (envelope.v !== 1) throw new Error(\`Unsupported Manifest encryption envelope version: \${String(envelope.v)}\`);
    out[property] = await decrypt(envelope.ct, envelope.kid, { ctx, entity, property });
  }
  return out;
}`;

const READ_POLICY_HELPER = `function __allowsRead(policy: string, entity: string, check: () => unknown): boolean {
  try {
    return !!check();
  } catch (error) {
    console.warn(\`[Manifest Convex] read policy '\${policy}' evaluation error for '\${entity}' (read denied)\`, error);
    return false;
  }
}`;

const RELATION_HELPER = `async function __resolveRelation(
  ctx: any,
  table: string,
  localValues: readonly unknown[],
  targetFields: readonly string[],
  tenantField?: string,
  tenantValue?: unknown,
): Promise<any | null> {
  if (localValues.some((value) => value == null)) return null;
  const identityIndex = targetFields.indexOf("id");
  let target: any | null;
  if (identityIndex >= 0) {
    target = await ctx.db.get(localValues[identityIndex] as any);
  } else {
    target = await ctx.db
      .query(table)
      .filter((q: any) =>
        q.and(...targetFields.map((field, index) => q.eq(q.field(field), localValues[index]))),
      )
      .first();
  }
  if (!target) return null;
  for (let index = 0; index < targetFields.length; index += 1) {
    const field = targetFields[index] === "id" ? "_id" : targetFields[index];
    if (target[field] !== localValues[index]) return null;
  }
  if (tenantField && target[tenantField] !== tenantValue) return null;
  return target;
}`;

/**
 * Render an IR default value to a TS literal that satisfies a Convex validator.
 *
 * Two of the projection's type mappings are *representational*: `int`/`bigint`
 * map to `v.int64()` (a JS `bigint`) and `decimal`/`money` map to `v.string()`
 * (lossless decimal transport — Convex has no native Decimal). A structurally
 * faithful render of an IR `number` default (`1`) is the WRONG runtime type for
 * those validators — Convex rejects a JS number where it expects a bigint or a
 * string — so the create-mutation default fill would fail schema validation at
 * insert time. Coerce numeric leaves to the validator's representation.
 *
 * `validator` is the field's resolved expression (possibly `v.optional`/
 * `v.array`-wrapped); detection is structural so per-property `typeMappings`
 * overrides are honored. Arrays share their element validator, so it propagates
 * to elements; objects carry heterogeneous members the field validator does not
 * describe, so their members are rendered structurally (no coercion).
 */
function defaultToTs(value: IRValue, validator?: string): string {
  switch (value.kind) {
    case 'string':
      return JSON.stringify(value.value);
    case 'number':
      // int64 wants a bigint literal; a non-integer default on an int field is
      // an authoring contradiction — surface it as a type error, don't truncate.
      if (validator && /\bv\.int64\(\)/.test(validator) && Number.isInteger(value.value)) {
        return `${value.value}n`;
      }
      // decimal/money (and stringId FKs) transport as strings.
      if (validator && /\bv\.string\(\)/.test(validator)) {
        return JSON.stringify(String(value.value));
      }
      return String(value.value);
    case 'boolean':
      return String(value.value);
    case 'null':
      return 'null';
    case 'array':
      return `[${value.elements.map((el) => defaultToTs(el, validator)).join(', ')}]`;
    case 'object':
      return `{${Object.entries(value.properties)
        .map(([k, v]) => `${JSON.stringify(k)}: ${defaultToTs(v)}`)
        .join(', ')}}`;
  }
}

/**
 * Render a mutate-action right-hand side, converting a literal-`null` assignment
 * to a NON-nullable field into `undefined`. Convex rejects `null` for an
 * `v.optional(T)` column but treats `undefined` as "unset" — so a DSL `= null`
 * "clear"/"restore" must lower to field omission, not a rejected null write.
 * Nullable fields (schema `v.union(T, v.null())`) keep `null`.
 */
function renderActionValue(
  entity: IREntity,
  target: string | undefined,
  expression: IRExpression,
  scope: RenderScope,
): RenderResult {
  const res = renderExpression(expression, scope);
  if (res.unresolved.length === 0 && target && isNullLiteral(expression)) {
    const targetProp = entity.properties.find((p) => p.name === target);
    if (targetProp?.type.nullable !== true) {
      return { code: 'undefined', unresolved: res.unresolved };
    }
  }
  return res;
}

/**
 * Validator expression for a command parameter (no optional wrap). Mirrors the
 * entity-field `array<T>` handling so an `array`-typed param maps to
 * `v.array(<element>)` instead of collapsing to a structureless `v.any()`.
 * Unknown leaf types still fall back to `v.any()` (params are not schema fields,
 * so an unmapped type is permissive rather than a hard diagnostic).
 */
function paramValidator(type: { name: string; generic?: { name: string } }): string {
  if ((type.name === 'array' || type.name === 'list') && type.generic) {
    const element = resolveConvexValidator(type.generic.name, undefined, '') ?? 'v.any()';
    return `v.array(${element})`;
  }
  return resolveConvexValidator(type.name, undefined, '') ?? 'v.any()';
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

function capWord(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

interface QueryIndexField {
  /** Column being matched (also the arg name). */
  name: string;
  /** Target table when the column is a convexId reference (→ `v.id(...)` arg). */
  fkTarget?: string;
}

interface QueryIndexSpec {
  /** Columns the index covers, in order (single-field or composite). */
  fields: QueryIndexField[];
  /** Schema index name to read via `withIndex(...)`. */
  indexName: string;
}

/**
 * The indexes an entity exposes as reads, derived to match EXACTLY what the
 * schema surface emits (`generator.ts#emitTable`): `indexed`-modifier properties,
 * the tenant column, every belongsTo/ref FK (in BOTH reference modes), and every
 * `options.indexes` entry (single-field AND composite). Single-field specs are
 * deduped by column in schema order; composite specs by index name. The result
 * guarantees every schema index has a corresponding `list<Entity>By<Field...>`
 * query — the two surfaces can no longer drift (closing both the stringId-mode
 * FK gap and the composite-index gap).
 */
function collectQueryIndexSpecs(ir: IR, entity: IREntity, options: Normalized): QueryIndexSpec[] {
  const specs: QueryIndexSpec[] = [];
  const seenSingle = new Set<string>();
  const seenName = new Set<string>();
  // convexId-only targets: present → arg typed `v.id(target)`; absent → `v.string()`.
  const fkTargets = collectFkTargets(entity, ir, options);
  const mkField = (name: string): QueryIndexField => ({ name, fkTarget: fkTargets.get(name) });

  const addSingle = (field: string, indexName: string): void => {
    if (field === 'id' || seenSingle.has(field)) return;
    seenSingle.add(field);
    seenName.add(indexName);
    specs.push({ fields: [mkField(field)], indexName });
  };

  for (const p of entity.properties) {
    if (p.modifiers.includes('indexed')) addSingle(p.name, `by_${p.name}`);
  }
  const tenantProp = ir.tenant?.property;
  if (tenantProp && entity.properties.some((p) => p.name === tenantProp))
    addSingle(tenantProp, `by_${tenantProp}`);
  for (const fk of collectReferenceFields(entity, ir, options).keys()) addSingle(fk, `by_${fk}`);
  for (const entry of options.indexes[entity.name] ?? []) {
    const def = indexEntryToDef(entry);
    if (def.fields.length === 1) {
      addSingle(def.fields[0], def.name);
    } else if (def.fields.length > 1 && !seenName.has(def.name)) {
      seenName.add(def.name);
      specs.push({ fields: def.fields.map(mkField), indexName: def.name });
    }
  }
  return specs;
}

/**
 * Tenant-id binding for a handler body. Identity comes from the author-owned
 * `getAuthContext(ctx)` module ({@link NormalizedOptions.authContextImport}).
 * Generation fails with `CONVEX_AUTH_CONTEXT_REQUIRED` when tenant filtering is
 * on without that import — this path is never reached for the broken legacy
 * `(ctx as any).auth` bag.
 */
function tenantBindingLine(_options: Normalized, tenantProp: string): string {
  return `    const __tenant = ((await getAuthContext(ctx)) as any).${tenantProp} ?? null;`;
}

/** Resolved read-side tenant + soft-delete filtering for an entity (field-aware). */
interface ReadFilter {
  hasTenant: boolean;
  tenantProp: string | undefined;
  /** The `by_<tenantProp>` index exists in the schema (IR-declared tenant). */
  tenantIndexed: boolean;
  hasSoftDelete: boolean;
  deletedProp: string;
}

function resolveReadFilter(ir: IR, entity: IREntity, options: Normalized): ReadFilter {
  const tenantProp = options.tenantIdProperty ?? ir.tenant?.property;
  // Tenant scoping requires a real identity seam — never the ineffective ctx.auth bag.
  const hasTenant =
    options.includeTenantFilter &&
    !!options.authContextImport &&
    !!tenantProp &&
    entity.properties.some((p) => p.name === tenantProp);
  const deletedProp = options.deletedAtProperty;
  const hasSoftDelete =
    options.includeSoftDeleteFilter && entity.properties.some((p) => p.name === deletedProp);
  return {
    hasTenant,
    tenantProp: hasTenant ? tenantProp : undefined,
    tenantIndexed: hasTenant && tenantProp === ir.tenant?.property,
    hasSoftDelete,
    deletedProp,
  };
}

type PolicyPrelude = (deniedValue: '[]' | 'null') => string[];
type FinishRows = (rowsExpr: string) => string;
type FinishDoc = (docExpr: string) => string;

function emitListEntityQuery(
  blocks: string[],
  entity: IREntity,
  table: string,
  rf: ReadFilter,
  options: Normalized,
  qfn: string,
  policyPrelude: PolicyPrelude,
  finishRows: FinishRows,
): void {
  if (!rf.hasTenant && !rf.hasSoftDelete) {
    const bodyLines = [
      ...policyPrelude('[]'),
      `    ${finishRows(`await ctx.db.query("${table}").collect()`)}`,
    ].join('\n');
    blocks.push(
      `export const list${entity.name} = ${qfn}({\n` +
        `  args: {},\n` +
        `  handler: async (ctx) => {\n` +
        `${bodyLines}\n` +
        `  },\n});`,
    );
    return;
  }
  const lines: string[] = [...policyPrelude('[]')];
  if (rf.hasTenant) lines.push(tenantBindingLine(options, rf.tenantProp!));
  if (rf.hasTenant && rf.tenantIndexed) {
    lines.push(
      `    let rows = await ctx.db.query("${table}").withIndex("by_${rf.tenantProp}", (q) => q.eq("${rf.tenantProp}", __tenant)).collect();`,
    );
  } else {
    lines.push(`    let rows = await ctx.db.query("${table}").collect();`);
    if (rf.hasTenant) {
      lines.push(`    rows = rows.filter((d) => (d as any).${rf.tenantProp} === __tenant);`);
    }
  }
  if (rf.hasSoftDelete) {
    lines.push(`    rows = rows.filter((d) => (d as any).${rf.deletedProp} == null);`);
  }
  lines.push(`    ${finishRows('rows')}`);
  blocks.push(
    `export const list${entity.name} = ${qfn}({\n` +
      `  args: {},\n` +
      `  handler: async (ctx) => {\n${lines.join('\n')}\n  },\n});`,
  );
}

function emitGetEntityQuery(
  blocks: string[],
  entity: IREntity,
  table: string,
  rf: ReadFilter,
  options: Normalized,
  qfn: string,
  policyPrelude: PolicyPrelude,
  finishDoc: FinishDoc,
): void {
  if (!rf.hasTenant && !rf.hasSoftDelete) {
    const bodyLines = [...policyPrelude('null'), `    ${finishDoc(`await ctx.db.get(id)`)}`].join(
      '\n',
    );
    blocks.push(
      `export const get${entity.name} = ${qfn}({\n` +
        `  args: { id: v.id("${table}") },\n` +
        `  handler: async (ctx, { id }) => {\n` +
        `${bodyLines}\n` +
        `  },\n});`,
    );
    return;
  }
  const lines: string[] = [...policyPrelude('null'), `    const doc = await ctx.db.get(id);`];
  if (rf.hasTenant) {
    lines.push(tenantBindingLine(options, rf.tenantProp!));
    lines.push(`    if (doc && (doc as any).${rf.tenantProp} !== __tenant) return null;`);
  }
  if (rf.hasSoftDelete) {
    lines.push(`    if (doc && (doc as any).${rf.deletedProp} != null) return null;`);
  }
  lines.push(`    ${finishDoc('doc')}`);
  blocks.push(
    `export const get${entity.name} = ${qfn}({\n` +
      `  args: { id: v.id("${table}") },\n` +
      `  handler: async (ctx, { id }) => {\n${lines.join('\n')}\n  },\n});`,
  );
}

function emitListByIndexQueries(
  blocks: string[],
  ir: IR,
  entity: IREntity,
  table: string,
  rf: ReadFilter,
  options: Normalized,
  qfn: string,
  policyPrelude: PolicyPrelude,
  finishRows: FinishRows,
): void {
  for (const spec of collectQueryIndexSpecs(ir, entity, options)) {
    const names = spec.fields.map((f) => f.name);
    const suffix = spec.fields.map((f) => capWord(f.name)).join('And');
    const argList = spec.fields
      .map((f) => `${f.name}: ${f.fkTarget ? `v.id("${f.fkTarget}")` : 'v.string()'}`)
      .join(', ');
    const destructure = `{ ${names.join(', ')} }`;
    const eqChain = spec.fields.map((f) => `.eq("${f.name}", ${f.name})`).join('');
    const applyTenant = rf.hasTenant && !!rf.tenantProp && !names.includes(rf.tenantProp);

    if (!applyTenant && !rf.hasSoftDelete) {
      const bodyLines = [
        ...policyPrelude('[]'),
        `    ${finishRows(
          `await ctx.db.query("${table}").withIndex("${spec.indexName}", (q) => q${eqChain}).collect()`,
        )}`,
      ].join('\n');
      blocks.push(
        `export const list${entity.name}By${suffix} = ${qfn}({\n` +
          `  args: { ${argList} },\n` +
          `  handler: async (ctx, ${destructure}) => {\n` +
          `${bodyLines}\n` +
          `  },\n});`,
      );
      continue;
    }

    const lines: string[] = [...policyPrelude('[]')];
    if (applyTenant) lines.push(tenantBindingLine(options, rf.tenantProp!));
    lines.push(
      `    let rows = await ctx.db.query("${table}").withIndex("${spec.indexName}", (q) => q${eqChain}).collect();`,
    );
    if (applyTenant) {
      lines.push(`    rows = rows.filter((d) => (d as any).${rf.tenantProp} === __tenant);`);
    }
    if (rf.hasSoftDelete) {
      lines.push(`    rows = rows.filter((d) => (d as any).${rf.deletedProp} == null);`);
    }
    lines.push(`    ${finishRows('rows')}`);
    blocks.push(
      `export const list${entity.name}By${suffix} = ${qfn}({\n` +
        `  args: { ${argList} },\n` +
        `  handler: async (ctx, ${destructure}) => {\n${lines.join('\n')}\n  },\n});`,
    );
  }
}

export function generateQueries(
  ir: IR,
  rawOptions: Record<string, unknown> | undefined,
): FunctionsResult {
  const options = normalizeOptions(rawOptions);
  const diagnostics: ProjectionDiagnostic[] = [];
  const blocks: string[] = [];

  for (const entity of persistentEntities(ir)) {
    const visibility = resolveConvexReadVisibility(
      ir,
      entity.name,
      options.authContextImport,
      '__row',
    );
    const listPolicyPlan = visibility.policies;
    const docPolicyPlan = renderReadPolicies(ir, entity.name, '__doc');
    diagnostics.push(...listPolicyPlan.diagnostics);
    const policyGated = visibility.gated;
    const policyEnforceable = visibility.clientReadable;
    const qfn = policyEnforceable ? 'query' : 'internalQuery';
    const table = resolveConvexTableName(entity.name, options);
    const rf = resolveReadFilter(ir, entity, options);
    const privates = privateFieldNames(entity);
    const encrypted = encryptedFieldNames(entity);
    const inlineComputed =
      options.computedProperties === 'inline'
        ? renderInlineComputedFields(entity, '__row', options)
        : {
            fields: [] as { name: string; code: string }[],
            diagnostics: [] as ProjectionDiagnostic[],
          };
    diagnostics.push(...inlineComputed.diagnostics);
    const inlineHydrateDoc =
      options.computedProperties === 'inline' && inlineComputed.fields.length > 0
        ? renderEntityComputedHydration(ir, entity, options, '(__doc as any)', '__doc._id')
        : { lines: [] as string[] };
    const inlineHydrateRow =
      options.computedProperties === 'inline' && inlineComputed.fields.length > 0
        ? renderEntityComputedHydration(ir, entity, options, '(__row as any)', '__row._id')
        : { lines: [] as string[] };
    const allPolicyChecks = [...listPolicyPlan.contextChecks, ...listPolicyPlan.rowChecks];
    const policyAuthLines = (): string[] => {
      const text = allPolicyChecks.map((check) => check.code).join('\n');
      const needsUser = /\buser\b/.test(text);
      const needsContext = /\bcontext\b/.test(text);
      if (!needsUser && !needsContext) return [];
      return [
        `    const __auth = (await getAuthContext(ctx)) as any;`,
        ...(needsUser ? [`    const user = (__auth.user ?? __auth) as any;`] : []),
        ...(needsContext ? [`    const context = (__auth.context ?? __auth) as any;`] : []),
      ];
    };
    const policyPrelude = (deniedValue: '[]' | 'null'): string[] => {
      if (!policyGated || !policyEnforceable) return [];
      return [
        ...policyAuthLines(),
        ...listPolicyPlan.contextChecks.map(
          (check) =>
            `    if (!__allowsRead(${JSON.stringify(check.policyName)}, ${JSON.stringify(entity.name)}, () => ${check.code})) return ${deniedValue};`,
        ),
      ];
    };

    const hydrateThenProjectRows = (sourceExpr: string): string => {
      const assigns = inlineComputed.fields.map((f) => `${f.name}: ${f.code}`).join(', ');
      const hydrate = inlineHydrateRow.lines.map((line) => `      ${line.trimStart()}`).join('\n');
      return (
        `const __projectedRows: any[] = [];\n` +
        `    for (const __row of ${sourceExpr} as any[]) {\n` +
        (hydrate ? `${hydrate}\n` : '') +
        `      __projectedRows.push({ ...(__row as any), ${assigns} });\n` +
        `    }\n` +
        `    ${stripPrivateFromRows('__projectedRows', privates)}`
      );
    };

    /** Finalize rows: decrypt → read policies → computed/private public projection. */
    const finishRows = (rowsExpr: string): string => {
      if (encrypted.length === 0 && !policyGated) {
        if (inlineComputed.fields.length === 0) {
          return stripPrivateFromRows(rowsExpr, privates);
        }
        if (inlineHydrateRow.lines.length === 0) {
          const assigns = inlineComputed.fields.map((f) => `${f.name}: ${f.code}`).join(', ');
          const mapped = `(${rowsExpr}).map((__row) => ({ ...(__row as any), ${assigns} }))`;
          return stripPrivateFromRows(mapped, privates);
        }
        return hydrateThenProjectRows(rowsExpr);
      }

      const lines: string[] = [];
      const plainExpr =
        encrypted.length > 0 && options.encryptionImport
          ? `await Promise.all((${rowsExpr}).map((row) => __decryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(encrypted)}, row)))`
          : rowsExpr;
      lines.push(`const __plainRows = ${plainExpr};`);
      let visibleExpr = '__plainRows';
      if (policyGated && policyEnforceable) {
        if (listPolicyPlan.rowChecks.length > 0) {
          lines.push(`    const __visibleRows: any[] = [];`);
          lines.push(`    for (const __row of __plainRows) {`);
          for (const check of listPolicyPlan.rowChecks) {
            lines.push(
              `      if (!__allowsRead(${JSON.stringify(check.policyName)}, ${JSON.stringify(entity.name)}, () => ${check.code})) continue;`,
            );
          }
          lines.push(`      __visibleRows.push(__row);`);
          lines.push(`    }`);
          visibleExpr = '__visibleRows';
        }
      }
      if (inlineComputed.fields.length > 0) {
        if (inlineHydrateRow.lines.length > 0) {
          lines.push(`    ${hydrateThenProjectRows(visibleExpr)}`);
          return lines.join('\n');
        }
        const assigns = inlineComputed.fields.map((f) => `${f.name}: ${f.code}`).join(', ');
        visibleExpr = `(${visibleExpr}).map((__row) => ({ ...(__row as any), ${assigns} }))`;
      }
      lines.push(`    ${stripPrivateFromRows(visibleExpr, privates)}`);
      return lines.join('\n');
    };
    /** Finalize one doc: decrypt → read policies → computed/private projection. */
    const finishDoc = (docExpr: string): string => {
      const hydrateBlock =
        inlineHydrateDoc.lines.length > 0 ? `${inlineHydrateDoc.lines.join('\n')}\n` : '';
      if (encrypted.length === 0 && !policyGated) {
        if (inlineComputed.fields.length === 0) {
          return stripPrivateFromDoc(docExpr, privates);
        }
        const assigns = inlineComputed.fields
          .map((f) => `${f.name}: ${f.code.replace(/\b__row\b/g, '__doc')}`)
          .join(', ');
        if (privates.length === 0) {
          return (
            `const __doc = ${docExpr};\n` +
            `    if (!__doc) return __doc;\n` +
            hydrateBlock +
            `    return { ...(__doc as any), ${assigns} };`
          );
        }
        const dels = privates.map((p) => `delete (__out as any).${p};`).join(' ');
        return (
          `const __doc = ${docExpr};\n` +
          `    if (!__doc) return __doc;\n` +
          hydrateBlock +
          `    const __out = { ...(__doc as any), ${assigns} };\n` +
          `    ${dels}\n` +
          `    return __out;`
        );
      }

      const lines: string[] = [
        `const __rawDoc = ${docExpr};`,
        `    if (!__rawDoc) return __rawDoc;`,
      ];
      if (encrypted.length > 0 && options.encryptionImport) {
        lines.push(
          `    const __doc = await __decryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(encrypted)}, __rawDoc);`,
        );
      } else {
        lines.push(`    const __doc = __rawDoc;`);
      }
      if (policyGated && policyEnforceable) {
        for (const check of docPolicyPlan.rowChecks) {
          lines.push(
            `    if (!__allowsRead(${JSON.stringify(check.policyName)}, ${JSON.stringify(entity.name)}, () => ${check.code})) return null;`,
          );
        }
      }
      if (hydrateBlock) lines.push(hydrateBlock.trimEnd());
      const assigns = inlineComputed.fields
        .map((f) => `${f.name}: ${f.code.replace(/\b__row\b/g, '__doc')}`)
        .join(', ');
      if (privates.length === 0) {
        lines.push(
          inlineComputed.fields.length > 0
            ? `    return { ...(__doc as any), ${assigns} };`
            : `    return __doc;`,
        );
        return lines.join('\n');
      }
      const dels = privates.map((p) => `delete (__out as any).${p};`).join(' ');
      lines.push(
        `    const __out = { ...(__doc as any)${assigns ? `, ${assigns}` : ''} };`,
        `    ${dels}`,
        `    return __out;`,
      );
      return lines.join('\n');
    };

    // list/get/listBy — tenant + soft-delete filters applied in helpers.
    emitListEntityQuery(blocks, entity, table, rf, options, qfn, policyPrelude, finishRows);
    emitGetEntityQuery(blocks, entity, table, rf, options, qfn, policyPrelude, finishDoc);
    emitListByIndexQueries(blocks, ir, entity, table, rf, options, qfn, policyPrelude, finishRows);
  }

  // System events table reads (when emitted): recent feed + the three indexed
  // lookups (by_type / by_entity / by_entityId) the schema declares on it.
  if (options.emitEventsTable) {
    // Event rows carry payloads from every entity, so ANY read/all policy in
    // the program locks the events feed down too — unless an auth seam is set
    // (same rule as entity queries: public + tenant via getAuthContext).
    const anyReadPolicy = ir.policies.some((p) => p.action === 'read' || p.action === 'all');
    const evq = anyReadPolicy ? 'internalQuery' : 'query';
    const ev = resolveEventsTableName(ir, options);
    blocks.push(
      `export const listRecentEvents = ${evq}({\n` +
        `  args: {},\n` +
        `  handler: async (ctx) => {\n` +
        `    return await ctx.db.query("${ev}").order("desc").take(50);\n` +
        `  },\n});`,
    );
    for (const field of ['type', 'entity', 'entityId']) {
      blocks.push(
        `export const listEventsBy${capWord(field)} = ${evq}({\n` +
          `  args: { ${field}: v.string() },\n` +
          `  handler: async (ctx, { ${field} }) => {\n` +
          `    return await ctx.db.query("${ev}").withIndex("by_${field}", (q) => q.eq("${field}", ${field})).collect();\n` +
          `  },\n});`,
      );
    }
  }

  const body = blocks.join('\n\n');
  const needsAuthCtx = !!options.authContextImport && /\bgetAuthContext\b/.test(body);
  const needsDecrypt = !!options.encryptionImport && /\b__decryptDoc\b/.test(body);
  const helpers: string[] = [];
  if (/\b__allowsRead\(/.test(body)) helpers.push(READ_POLICY_HELPER);
  if (/\b__resolveRelation\(/.test(body)) helpers.push(RELATION_HELPER);
  if (/\bcheckRole\(/.test(body)) {
    helpers.push(
      `const ROLE_PERMISSIONS: Record<string, { action: string; target?: string }[]> = ${roleMapLiteral(ir)};\n\n` +
        `function checkRole(userRole: unknown, action: unknown, target?: unknown): boolean {\n` +
        `  if (typeof userRole !== "string" || typeof action !== "string") return false;\n` +
        `  const perms = ROLE_PERMISSIONS[userRole];\n` +
        `  const requestedTarget = typeof target === "string" ? target : undefined;\n` +
        `  return perms ? perms.some((permission) =>\n` +
        `    (permission.action === action || permission.action === "all") &&\n` +
        `    (permission.target === undefined || permission.target === requestedTarget)\n` +
        `  ) : false;\n` +
        `}`,
    );
  }
  if (/\bflag\(/.test(body)) {
    helpers.push(
      `// Feature toggle (configurable). Not an authorization gate.\nfunction flag(_name?: string): boolean { return true; }`,
    );
  }
  const serverImports = [
    ...(/= query\({/.test(body) || blocks.length === 0 ? ['query'] : []),
    ...(/= internalQuery\({/.test(body) ? ['internalQuery'] : []),
  ];
  const code =
    `${GENERATED_HEADER}\n// ${blocks.length} query function(s).\n\n` +
    `import { ${serverImports.join(', ')} } from "./_generated/server";\n` +
    `import { v } from "convex/values";\n` +
    (needsAuthCtx
      ? `import { getAuthContext } from ${JSON.stringify(options.authContextImport)};\n`
      : '') +
    (needsDecrypt ? `import { decrypt } from ${JSON.stringify(options.encryptionImport)};\n` : '') +
    `\n` +
    (needsDecrypt ? `${DECRYPT_HELPER}\n\n` : '') +
    (helpers.length ? `${helpers.join('\n\n')}\n\n` : '') +
    `${body}\n`;

  return { code, diagnostics };
}

// ---------------------------------------------------------------------------
// Mutations
// ---------------------------------------------------------------------------

/** Build the ROLE_PERMISSIONS map literal from IR roles' effective permissions. */
function roleMapLiteral(ir: IR): string {
  const map: Record<string, { action: string; target?: string }[]> = {};
  for (const role of ir.roles ?? []) {
    map[role.name] = [...(role.effectivePermissions ?? [])]
      .map((permission) => ({
        action: permission.action,
        ...(permission.target === undefined ? {} : { target: permission.target }),
      }))
      .sort((a, b) =>
        `${a.action}\u0000${a.target ?? ''}`.localeCompare(`${b.action}\u0000${b.target ?? ''}`),
      );
  }
  return JSON.stringify(map, null, 2);
}

interface CheckSpec {
  expr: IRExpression | undefined;
  /** denial message */
  message: string;
  /** diagnostic code emitted when unresolved */
  code: 'CONVEX_UNRESOLVED_POLICY' | 'CONVEX_UNRESOLVED_GUARD' | 'CONVEX_UNRESOLVED_CONSTRAINT';
  label: string;
  /**
   * failWhen polarity (docs/spec/semantics.md § Constraint Polarity): a TRUTHY
   * expression is the violation, so the check throws when the expression holds.
   * Default/absent: falsy expression is the violation.
   */
  failWhen?: boolean;
}

/** Render governance checks fail-closed. Returns TS lines + diagnostics. */
function renderChecks(
  entityName: string,
  checks: CheckSpec[],
  scope: RenderScope,
): { lines: string[]; diagnostics: ProjectionDiagnostic[] } {
  const lines: string[] = [];
  const diagnostics: ProjectionDiagnostic[] = [];
  for (const c of checks) {
    const { code, unresolved } = renderExpression(c.expr, scope);
    if (unresolved.length > 0) {
      diagnostics.push({
        severity: 'error',
        code: c.code,
        entity: entityName,
        message: `${c.label}: could not resolve expression (${unresolved.join('; ')}). Emitted a denying throw (fail-closed).`,
      });
      lines.push(`    throw new Error(${JSON.stringify(`${c.label} unresolved — denied`)});`);
    } else if (c.failWhen) {
      lines.push(`    if (${code}) throw new Error(${JSON.stringify(c.message)});`);
    } else {
      lines.push(`    if (!(${code})) throw new Error(${JSON.stringify(c.message)});`);
    }
  }
  return { lines, diagnostics };
}

/** Collect the policy/guard/constraint checks for a command, in runtime order. */
function commandChecks(ir: IR, cmd: IRCommand, policyMode: 'enforce' | 'skip'): CheckSpec[] {
  const checks: CheckSpec[] = [];
  if (policyMode !== 'skip') {
    for (const pName of cmd.policies ?? []) {
      const policy: IRPolicy | undefined = ir.policies.find((p) => p.name === pName);
      if (!policy) continue;
      checks.push({
        expr: policy.expression,
        message: policy.message ?? `Policy ${pName} denied`,
        code: 'CONVEX_UNRESOLVED_POLICY',
        label: `policy '${pName}'`,
      });
    }
  }
  for (let i = 0; i < cmd.guards.length; i++) {
    checks.push({
      expr: cmd.guards[i],
      message: `Guard ${i} failed`,
      code: 'CONVEX_UNRESOLVED_GUARD',
      label: `guard[${i}]`,
    });
  }
  for (const c of (cmd.constraints ?? []) as IRConstraint[]) {
    if (c.severity && c.severity !== 'block') continue;
    checks.push({
      expr: c.expression,
      message: c.message ?? c.messageTemplate ?? `Constraint ${c.code} failed`,
      code: 'CONVEX_UNRESOLVED_CONSTRAINT',
      label: `constraint '${c.code}'`,
      failWhen: c.failWhen === true,
    });
  }
  return checks;
}

/** Render reaction fan-out for the events a command emits. */
function renderReactions(
  ir: IR,
  options: Normalized,
  emits: string[],
): { lines: string[]; diagnostics: ProjectionDiagnostic[] } {
  const lines: string[] = [];
  const diagnostics: ProjectionDiagnostic[] = [];
  const matched = (ir.reactions ?? []).filter((r: IRReactionRule) => emits.includes(r.event));
  if (matched.length === 0) return { lines, diagnostics };
  lines.push('    // Reactions');
  const tenantProp = ir.tenant?.property;
  // Count vars + the shared tenant binding are handler-scoped (one handler per
  // command, so all matched reactions share a scope); dedupe across reactions.
  let countCounter = 0;
  let tenantEmitted = false;

  /**
   * Render ONE reaction param. An aggregate-count param lowers to a read block
   * (preLines) that counts rows of the param's entity matching its ANDed equality
   * predicates, then binds the param to that count variable. The foreign-key (or
   * any indexed) predicate drives a `withIndex` read; remaining predicates,
   * soft-delete, and tenant scope are applied as JS `.filter`s — mirroring the
   * hardened read surface. Any other param renders as a single expression.
   * Returns `entry: null` when the value cannot be resolved (caller omits it).
   */
  const buildParam = (
    p: IRReactionParam,
    scope: RenderScope,
    label: string,
  ): { preLines: string[]; entry: string | null } => {
    const e = p.expression;
    if (e.kind === 'aggregate' && (e.op === 'count' || e.op === 'sum')) {
      const childEntity = ir.entities.find((en) => en.name === e.entity);
      if (!childEntity) {
        diagnostics.push({
          severity: 'error',
          code: 'CONVEX_AGGREGATE_UNKNOWN_ENTITY',
          message: `${label} param '${p.name}' ${e.op}s unknown entity '${e.entity}'; omitted.`,
        });
        return { preLines: [], entry: null };
      }
      if (e.op === 'sum' && !e.field) {
        diagnostics.push({
          severity: 'error',
          code: 'CONVEX_AGGREGATE_SUM_MISSING_FIELD',
          message: `${label} param '${p.name}' sum is missing 'of' field; omitted.`,
        });
        return { preLines: [], entry: null };
      }
      const childTable = resolveConvexTableName(e.entity, options);
      const rf = resolveReadFilter(ir, childEntity, options);
      const refFields = collectReferenceFields(childEntity, ir, options);
      const isIndexedField = (field: string): boolean => {
        const prop = childEntity.properties.find((pp) => pp.name === field);
        return !!prop && (prop.modifiers.includes('indexed') || refFields.has(field));
      };
      const renderVal = (val: IRExpression): RenderResult => {
        const r = renderExpression(val, scope);
        if (r.unresolved.length) {
          diagnostics.push({
            severity: 'warning',
            code: 'CONVEX_UNRESOLVED_AGGREGATE_PREDICATE',
            message: `${label} param '${p.name}' ${e.op} predicate value unresolved (${r.unresolved.join('; ')}).`,
          });
        }
        return r;
      };

      const indexedPred = e.predicates.find((pr) => isIndexedField(pr.field));
      const remaining = indexedPred
        ? e.predicates.filter((pr) => pr !== indexedPred)
        : e.predicates;
      const rowsVar = `__agg${countCounter}_rows`;
      const aggVar = `__agg${countCounter}`;
      countCounter++;
      const preLines: string[] = [];

      let queryHead: string;
      if (indexedPred) {
        const v = renderVal(indexedPred.value);
        queryHead = `ctx.db.query("${childTable}").withIndex("by_${indexedPred.field}", (q) => q.eq("${indexedPred.field}", ${v.code}))`;
      } else {
        queryHead = `ctx.db.query("${childTable}")`;
        diagnostics.push({
          severity: 'info',
          code: 'CONVEX_AGGREGATE_UNINDEXED',
          message: `${label} param '${p.name}' ${e.op}s '${e.entity}' with no indexed/foreign-key predicate; rendered a table scan (mark an equality field indexed for speed).`,
        });
      }
      preLines.push(`    const ${rowsVar} = await ${queryHead}.collect();`);

      const filters: string[] = [];
      for (const pr of remaining) {
        const v = renderVal(pr.value);
        filters.push(`(d as any).${pr.field} === ${v.code}`);
      }
      if (rf.hasSoftDelete) filters.push(`(d as any).${rf.deletedProp} == null`);
      if (rf.hasTenant && rf.tenantProp) {
        if (!tenantEmitted) {
          preLines.push(tenantBindingLine(options, rf.tenantProp!));
          tenantEmitted = true;
        }
        filters.push(`(d as any).${rf.tenantProp} === __tenant`);
      }
      const filteredVar = `${rowsVar}f`;
      const chain = filters.length ? filters.map((f) => `.filter((d) => ${f})`).join('') : '';
      if (e.op === 'count') {
        preLines.push(`    const ${aggVar} = ${rowsVar}${chain}.length;`);
      } else {
        preLines.push(`    const ${filteredVar} = ${rowsVar}${chain};`);
        preLines.push(
          `    const ${aggVar} = ${filteredVar}.reduce((acc, d) => { const n = Number((d as any).${e.field}); return acc + (Number.isFinite(n) ? n : 0); }, 0);`,
        );
      }
      return { preLines, entry: `${p.name}: ${aggVar}` };
    }

    const { code, unresolved } = renderExpression(e, scope);
    if (unresolved.length) {
      diagnostics.push({
        severity: 'warning',
        code: 'CONVEX_UNRESOLVED_REACTION_PARAM',
        message: `${label} param '${p.name}' unresolved (${unresolved.join('; ')}); omitted.`,
      });
      return { preLines: [], entry: null };
    }
    return { preLines: [], entry: `${p.name}: ${code}` };
  };

  matched.forEach((reaction, idx) => {
    const targetEntity = ir.entities.find((e) => e.name === reaction.targetEntity);
    const label = `reaction ${reaction.event}→${reaction.targetEntity}.${reaction.targetCommand}`;

    // Fan-out reaction: dispatch the command on every target row where
    // row.<matchField> == matchSource. matchSource resolves against the event
    // payload; params resolve per row with self/target = row and payload =
    // event (matching the reference runtime). Each match runs the generated
    // target command runner in the same transaction.
    if (reaction.fanOut) {
      const matchScope: RenderScope = {
        selfVar: 'payload',
        globals: ['payload', 'user', 'context', 'args'],
      };
      const src = renderExpression(reaction.fanOut.matchSource, matchScope);
      if (src.unresolved.length) {
        diagnostics.push({
          severity: 'warning',
          code: 'CONVEX_UNRESOLVED_REACTION_FANOUT',
          message: `fan-out ${label} match source unresolved (${src.unresolved.join('; ')}); skipped.`,
        });
        return;
      }
      const rowScope: RenderScope = {
        selfVar: '__row',
        // Convex documents store the primary key as `_id`; map `self.id` / bare `id`.
        idExpr: '(__row as any)._id',
        globals: ['payload', 'user', 'context', 'args', '__row', 'target'],
      };
      const fanParams: string[] = [];
      const fanPreLines: string[] = [];
      for (const p of reaction.params ?? []) {
        const r = buildParam(p, rowScope, label);
        fanPreLines.push(...r.preLines);
        if (r.entry) fanParams.push(r.entry);
      }
      const field = reaction.fanOut.matchField;
      const matchEntityName = reaction.fanOut.matchEntity ?? reaction.targetEntity;
      const matchEntity = ir.entities.find((e) => e.name === matchEntityName);
      const matchTable = resolveConvexTableName(matchEntityName, options);
      const crossEntity = matchEntityName !== reaction.targetEntity;
      const isFk = !!matchEntity && collectReferenceFields(matchEntity, ir, options).has(field);
      const matchProp = matchEntity?.properties.find((p) => p.name === field);
      const indexed = !!matchProp && (matchProp.modifiers.includes('indexed') || isFk);
      if (!indexed) {
        diagnostics.push({
          severity: 'info',
          code: 'CONVEX_FANOUT_UNINDEXED',
          message: `fan-out ${label} matches on non-indexed '${matchEntityName}.${field}'; rendered an unindexed filter (mark it indexed for speed).`,
        });
      }
      const queryExpr = indexed
        ? `ctx.db.query("${matchTable}").withIndex("by_${field}", (q) => q.eq("${field}", ${src.code}))`
        : `ctx.db.query("${matchTable}").filter((q) => q.eq(q.field("${field}"), ${src.code}))`;
      const rowsVar = `fanRows${idx}`;
      lines.push(`    const ${rowsVar} = await ${queryExpr}.collect();`);
      lines.push(`    for (const __row of ${rowsVar}) {`);
      lines.push(`      const target = __row;`);
      for (const pl of fanPreLines) lines.push(`      ${pl.trimStart()}`);
      const runner = commandRunnerName(reaction.targetEntity, reaction.targetCommand);
      const fanArgs = fanParams.join(', ');
      if (reaction.match && reaction.match.length > 0) {
        const targetTable = resolveConvexTableName(reaction.targetEntity, options);
        const firstPred = reaction.match[0]!;
        const firstVal = renderExpression(firstPred.source, rowScope);
        const matchRaw = `__fanMatch${idx}_raw`;
        const matchRows = `__fanMatch${idx}_rows`;
        const matchId = `__fanMatch${idx}_id`;
        lines.push(
          `      const ${matchRaw} = await ctx.db.query("${targetTable}").withIndex("by_${firstPred.field}", (q) => q.eq("${firstPred.field}", ${firstVal.code})).collect();`,
        );
        const filters = [`(d as any).${firstPred.field} === ${firstVal.code}`];
        for (const m of reaction.match.slice(1)) {
          const mv = renderExpression(m.source, rowScope);
          filters.push(`(d as any).${m.field} === ${mv.code}`);
        }
        filters.push(`(d as any).deletedAt == null`);
        lines.push(
          `      const ${matchRows} = ${matchRaw}.filter((d) => ${filters.join(' && ')}).sort((a, b) => String((a as any)._id).localeCompare(String((b as any)._id)));`,
        );
        lines.push(
          `      const ${matchId} = ${matchRows}.length > 0 ? (${matchRows}[0] as any)._id : null;`,
        );
        if (reaction.elseCreate) {
          lines.push(`      if (${matchId}) {`);
          lines.push(
            `        await ${runner}(ctx, { docId: ${matchId}${fanArgs ? ', ' + fanArgs : ''} } as any);`,
          );
          lines.push(`      } else {`);
          lines.push(`        await ${runner}(ctx, { ${fanArgs} } as any);`);
          lines.push(`      }`);
        } else {
          lines.push(
            `      if (${matchId}) await ${runner}(ctx, { docId: ${matchId}${fanArgs ? ', ' + fanArgs : ''} } as any);`,
          );
        }
      } else if (crossEntity) {
        // Foreach-create (and other cross-entity fanOut): no docId from the source row.
        lines.push(`      await ${runner}(ctx, { ${fanArgs} } as any);`);
      } else {
        lines.push(
          `      await ${runner}(ctx, { docId: (__row as any)._id${fanArgs ? ', ' + fanArgs : ''} } as any);`,
        );
      }
      lines.push(`    }`);
      return;
    }

    const scope: RenderScope = {
      selfVar: 'payload',
      globals: ['payload', 'user', 'context', 'args'],
    };
    const paramEntries: string[] = [];
    const paramPreLines: string[] = [];
    const paramNamesSeen = new Set<string>();
    for (const p of reaction.params ?? []) {
      const r = buildParam(p, scope, label);
      paramPreLines.push(...r.preLines);
      if (r.entry) {
        paramEntries.push(r.entry);
        paramNamesSeen.add(p.name);
      }
    }
    // Tenant propagation: a reaction fires within the source entity's tenant, so
    // when it creates a tenant-scoped target, thread the source tenantId
    // (available as payload.<tenantProp>) unless an explicit param already set it.
    const targetIsTenantScoped =
      !!tenantProp && !!targetEntity?.properties.some((p) => p.name === tenantProp);
    if (
      reaction.targetCommand === 'create' &&
      targetIsTenantScoped &&
      !paramNamesSeen.has(tenantProp!)
    ) {
      paramEntries.unshift(`${tenantProp}: payload.${tenantProp}`);
    }
    for (const pl of paramPreLines) lines.push(pl);
    if (reaction.match && reaction.match.length > 0) {
      const targetTable = resolveConvexTableName(reaction.targetEntity, options);
      const matchScope: RenderScope = {
        selfVar: 'payload',
        globals: ['payload', 'user', 'context', 'args'],
      };
      const matchRawVar = `__match${idx}_raw`;
      const matchRowsVar = `__match${idx}_rows`;
      const matchIdVar = `__match${idx}_id`;
      const firstPred = reaction.match[0]!;
      const firstVal = renderExpression(firstPred.source, matchScope);
      if (firstVal.unresolved.length) {
        diagnostics.push({
          severity: 'warning',
          code: 'CONVEX_UNRESOLVED_REACTION_MATCH',
          message: `${label} match predicate unresolved; skipped.`,
        });
      } else {
        lines.push(
          `    const ${matchRawVar} = await ctx.db.query("${targetTable}").withIndex("by_${firstPred.field}", (q) => q.eq("${firstPred.field}", ${firstVal.code})).collect();`,
        );
        const matchFilters: string[] = [`(d as any).${firstPred.field} === ${firstVal.code}`];
        for (const m of reaction.match.slice(1)) {
          const mv = renderExpression(m.source, matchScope);
          matchFilters.push(`(d as any).${m.field} === ${mv.code}`);
        }
        matchFilters.push(`(d as any).deletedAt == null`);
        lines.push(
          `    const ${matchRowsVar} = ${matchRawVar}.filter((d) => ${matchFilters.join(' && ')}).sort((a, b) => String((a as any)._id).localeCompare(String((b as any)._id)));`,
        );
        lines.push(
          `    const ${matchIdVar} = ${matchRowsVar}.length > 0 ? (${matchRowsVar}[0] as any)._id : null;`,
        );
        const runner = commandRunnerName(reaction.targetEntity, reaction.targetCommand);
        const args = paramEntries.length ? paramEntries.join(', ') : '';
        if (reaction.elseCreate) {
          lines.push(`    if (${matchIdVar}) {`);
          lines.push(
            `      await ${runner}(ctx, { docId: ${matchIdVar}${args ? ', ' + args : ''} } as any);`,
          );
          lines.push(`    } else {`);
          lines.push(`      await ${runner}(ctx, { ${args} } as any);`);
          lines.push(`    }`);
        } else {
          lines.push(
            `    if (${matchIdVar}) await ${runner}(ctx, { docId: ${matchIdVar}${args ? ', ' + args : ''} } as any);`,
          );
        }
      }
    } else if (reaction.targetCommand === 'create') {
      lines.push(
        `    await ${commandRunnerName(reaction.targetEntity, reaction.targetCommand)}(ctx, { ${paramEntries.join(', ')} } as any);`,
      );
    } else if (!reaction.resolve) {
      diagnostics.push({
        severity: 'warning',
        code: 'CONVEX_REACTION_MISSING_TARGET',
        message: `${label} has neither resolve nor match; skipped.`,
      });
    } else {
      const resolve = renderExpression(reaction.resolve, {
        selfVar: 'payload',
        globals: ['payload', 'user', 'context', 'args'],
      });
      const varName = `reactionTarget${idx}`;
      if (reaction.resolve?.kind === 'literal' && reaction.resolve.value.kind === 'null') {
        lines.push(
          `    // reaction ${reaction.event} → ${reaction.targetEntity}.${reaction.targetCommand} (resolve: null — no target id)`,
        );
      } else if (resolve.unresolved.length) {
        diagnostics.push({
          severity: 'warning',
          code: 'CONVEX_UNRESOLVED_REACTION_TARGET',
          message: `${label} target unresolved; skipped.`,
        });
      } else {
        lines.push(`    const ${varName} = ${resolve.code};`);
        lines.push(
          `    if (${varName}) await ${commandRunnerName(reaction.targetEntity, reaction.targetCommand)}(ctx, { docId: ${varName}${paramEntries.length ? ', ' + paramEntries.join(', ') : ''} } as any);`,
        );
      }
    }
  });
  return { lines, diagnostics };
}

/**
 * Auth/context/payload bindings a handler needs, derived by scanning the body
 * for the identifiers it actually references (avoids both undefined-name and
 * unused-var errors). With `authContextImport`, identity comes from the
 * author-owned `getAuthContext(ctx)`; `forceAuth` binds `__auth` even when the
 * scanned body does not reference it (tenant injection / ownership checks are
 * assembled after this scan).
 */
function authBindings(bodyText: string, options: Normalized, forceAuth = false): string[] {
  const lines: string[] = [];
  const refs = (token: string) => new RegExp(`\\b${token}\\b`).test(bodyText);
  const needsIdentity = forceAuth || refs('userRole') || refs('user');
  if (needsIdentity) {
    if (options.authContextImport) {
      lines.push(`    const __auth = (await getAuthContext(ctx)) as any;`);
      if (refs('userRole')) lines.push(`    const userRole = __auth.role ?? "anonymous";`);
      if (refs('user')) lines.push(`    const user = __auth;`);
    } else {
      // Diagnostic CONVEX_AUTH_CONTEXT_REQUIRED is emitted at generate(); fail loud in output too.
      lines.push(
        `    throw new Error("CONVEX_AUTH_CONTEXT_REQUIRED: set options.authContextImport");`,
      );
    }
  }
  if (refs('context')) lines.push(`    const context = (ctx as any);`);
  return lines;
}

interface RelationHydration {
  lines: string[];
  relationVars: Readonly<Record<string, string>>;
  diagnostics: ProjectionDiagnostic[];
  plan: ReturnType<typeof buildRelationDependencyPlan>;
}

/** Render only the relation locals required by this command's shared IR-derived plan. */
function renderRelationHydration(
  ir: IR,
  options: Normalized,
  entity: IREntity,
  command: IRCommand,
  sourceVar: string,
  tenantScoped: boolean,
  writeTenantProp: string | undefined,
  supportedHasMany: ReadonlySet<string> = new Set(),
  refine?: { relationNames: ReadonlySet<string>; varSuffix: string },
): RelationHydration {
  const lines: string[] = [];
  const relationVars: Record<string, string> = {};
  const diagnostics: ProjectionDiagnostic[] = [];
  const plan = buildRelationDependencyPlan(ir, entity, command);

  const deny = (dependency: RelationDependency, reason: string): void => {
    const variable = `__rel_${dependency.relationName}`;
    relationVars[dependency.relationName] = variable;
    diagnostics.push({
      severity: 'error',
      code: 'CONVEX_UNSUPPORTED_RELATION_ACCESS',
      entity: entity.name,
      message: `${entity.name}.${command.name} relation '${dependency.relationName}' ${reason}; emitted a denying throw (fail-closed).`,
    });
    lines.push(
      `    throw new Error(${JSON.stringify(`${entity.name}.${command.name} relation '${dependency.relationName}' unsupported — denied`)});`,
      `    const ${variable} = null as any;`,
    );
  };

  for (const dependency of plan.relations) {
    if (refine && !refine.relationNames.has(dependency.relationName)) continue;
    if (dependency.kind === 'hasMany') {
      const onlyCountOf =
        dependency.accessModes.length === 1 && dependency.accessModes[0] === 'countOf';
      if (!dependency.through && onlyCountOf && supportedHasMany.has(dependency.relationName)) {
        continue;
      }
      deny(dependency, 'uses an inverse/through access mode this command body cannot hydrate');
      continue;
    }
    if (dependency.through || (dependency.kind !== 'belongsTo' && dependency.kind !== 'ref')) {
      deny(dependency, `uses unsupported relationship kind '${dependency.kind}'`);
      continue;
    }
    if (
      dependency.localFields.length === 0 ||
      dependency.localFields.length !== dependency.targetFields.length
    ) {
      deny(dependency, 'has an invalid local/target reference mapping');
      continue;
    }

    const target = ir.entities.find((candidate) => candidate.name === dependency.targetEntity);
    if (!target) {
      deny(dependency, `targets unknown entity '${dependency.targetEntity}'`);
      continue;
    }

    const variable = `__rel_${dependency.relationName}${refine?.varSuffix ?? ''}`;
    const rawVariable = `${variable}Raw`;
    const localValues = dependency.localFields
      .map((field) =>
        tenantScoped && writeTenantProp === field ? `__auth.${field}` : `${sourceVar}.${field}`,
      )
      .join(', ');
    const targetTable = resolveConvexTableName(target.name, options);
    const enforceTenant =
      tenantScoped &&
      dependency.tenantOwnershipRequired &&
      !!writeTenantProp &&
      target.properties.some((property) => property.name === writeTenantProp);
    const tenantArgs = enforceTenant
      ? `, ${JSON.stringify(writeTenantProp)}, __auth.${writeTenantProp}`
      : '';
    const encryptedReads = encryptedFieldNames(target).filter((field) =>
      dependency.targetFieldsRead.includes(field),
    );
    relationVars[dependency.relationName] = variable;

    if (encryptedReads.length > 0 && !options.encryptionImport) {
      diagnostics.push({
        severity: 'error',
        code: 'CONVEX_ENCRYPTION_IMPORT_REQUIRED',
        entity: target.name,
        message: `${entity.name}.${command.name} reads encrypted relation field(s) ${encryptedReads.join(', ')}; set options.encryptionImport. Emitted a denying throw (fail-closed).`,
      });
      lines.push(
        `    throw new Error(${JSON.stringify(`${entity.name}.${command.name} encrypted relation access unsupported — denied`)});`,
        `    const ${variable} = null as any;`,
      );
      continue;
    }

    lines.push(
      `    const ${encryptedReads.length ? rawVariable : variable} = await __resolveRelation(ctx, ${JSON.stringify(targetTable)}, [${localValues}], ${JSON.stringify(dependency.targetFields)}${tenantArgs});`,
    );
    if (encryptedReads.length) {
      lines.push(
        `    const ${variable} = await __decryptDoc(ctx, ${JSON.stringify(target.name)}, ${JSON.stringify(encryptedReads)}, ${rawVariable});`,
      );
    }
  }

  return { lines, relationVars, diagnostics, plan };
}

/**
 * Emit an allocating `createVia*` mutation that performs atomic document
 * construction from the command's IR initialization plan: draft → checks →
 * mutations → single insert. No partial document is persisted before mutations.
 */
function renderGovernedCreationEntry(
  ir: IR,
  options: Normalized,
  entity: IREntity,
  cmd: IRCommand,
  table: string,
  _runnerName: string,
  tenantScoped: boolean,
  writeTenantProp: string | undefined,
  encryptionActive: boolean,
  mutationEncrypted: string[],
): { code?: string; diagnostics: ProjectionDiagnostic[] } {
  const diagnostics: ProjectionDiagnostic[] = [];
  const plan = cmd.initialization;
  if (!plan) {
    diagnostics.push({
      severity: 'warning',
      code: 'CONVEX_CREATION_ENTRY_MISSING_PLAN',
      entity: entity.name,
      message: `Cannot emit governed creation entry for '${entity.name}.${cmd.name}': command has no IR initialization plan.`,
    });
    return { diagnostics };
  }

  const params = cmd.parameters ?? [];
  const paramNames = new Set(params.map((parameter) => parameter.name));
  const commandOwned = new Set(plan.commandOwnedFields);
  const fkTargets = collectFkTargets(entity, ir, options);
  const propertyByName = new Map(entity.properties.map((property) => [property.name, property]));

  const draftLines: string[] = [];
  const draftValueExpressions = new Map<string, string>();
  for (const field of plan.authenticatedOwnershipFields) {
    if (tenantScoped && field === writeTenantProp) {
      draftLines.push(`      ${field}: __auth.${field}`);
    }
  }
  for (const item of plan.declaredDefaults) {
    const property = propertyByName.get(item.property);
    if (!property) continue;
    if (isConvexVersionManagedField(entity, item.property)) continue;
    const built = buildValidator(entity, property, ir, options, fkTargets.get(property.name));
    diagnostics.push(...built.diagnostics);
    if (item.source === 'defaultValue' && property.defaultValue !== undefined) {
      const value = defaultToTs(property.defaultValue, built.validator);
      draftLines.push(`      ${item.property}: ${value}`);
      draftValueExpressions.set(item.property, value);
    } else if (item.source === 'autoNow' || item.source === 'timestamps') {
      draftLines.push(`      ${item.property}: Date.now()`);
      draftValueExpressions.set(item.property, 'Date.now()');
    }
  }
  for (const item of plan.initialLifecycleState) {
    if (draftLines.some((line) => line.includes(`${item.property}:`))) continue;
    const value = defaultToTs(item.value);
    draftLines.push(`      ${item.property}: ${value}`);
    draftValueExpressions.set(item.property, value);
  }
  for (const inputName of plan.initializationInputs) {
    if (!propertyByName.has(inputName)) continue;
    // Same-named inputs are visible on the draft for precondition evaluation.
    const fallback = draftValueExpressions.get(inputName);
    if (fallback !== undefined) {
      const lineIndex = draftLines.findIndex((line) =>
        line.trimStart().startsWith(`${inputName}:`),
      );
      draftLines[lineIndex] =
        `      ${inputName}: args.${inputName} !== undefined ? args.${inputName} : ${fallback}`;
      continue;
    }
    draftLines.push(`      ${inputName}: args.${inputName}`);
  }

  const relationHydration = renderRelationHydration(
    ir,
    options,
    entity,
    cmd,
    '__draft',
    tenantScoped,
    writeTenantProp,
  );
  diagnostics.push(...relationHydration.diagnostics);

  const scope: RenderScope = {
    selfVar: '__draft',
    locals: [...paramNames],
    relationVars: relationHydration.relationVars,
    resolveCollectionElementType: (collection) =>
      resolveHasManyDocElementType(entity, collection, options),
  };
  const checks = renderChecks(entity.name, commandChecks(ir, cmd, options.policyMode), scope);
  diagnostics.push(...checks.diagnostics);

  const mutates = (cmd.actions ?? []).filter(
    (action) =>
      action.kind === 'mutate' &&
      action.target &&
      !(tenantScoped && action.target === writeTenantProp) &&
      !isConvexVersionManagedField(entity, action.target),
  );
  const mutateLines: string[] = [];
  for (const action of mutates) {
    const { code, unresolved } = renderActionValue(entity, action.target, action.expression, {
      selfVar: '__draft',
      locals: [...paramNames],
      relationVars: relationHydration.relationVars,
    });
    if (unresolved.length) {
      diagnostics.push({
        severity: 'warning',
        code: 'CONVEX_UNRESOLVED_ACTION',
        entity: entity.name,
        message: `initialization action '${action.target}' unresolved (${unresolved.join('; ')}); omitted.`,
      });
      continue;
    }
    mutateLines.push(`      ${action.target}: ${code}`);
  }

  for (const requirement of plan.finalDocumentRequirements) {
    if (requirement === 'id') continue;
    if (tenantScoped && requirement === writeTenantProp) continue;
    if (commandOwned.has(requirement)) continue;
    if (plan.declaredDefaults.some((item) => item.property === requirement)) continue;
    if (plan.initialLifecycleState.some((item) => item.property === requirement)) continue;
    if (plan.initializationInputs.includes(requirement)) continue;
    if (plan.authenticatedOwnershipFields.includes(requirement)) continue;
    const property = propertyByName.get(requirement);
    if (!property || property.type.nullable) continue;
    diagnostics.push({
      severity: 'warning',
      code: 'CONVEX_CREATION_ENTRY_INCOMPLETE',
      entity: entity.name,
      message: `Initialization command '${entity.name}.${cmd.name}' cannot satisfy required field '${requirement}' from the IR initialization plan.`,
    });
    return { diagnostics };
  }

  const versionLines = convexCreateVersionDocLines(entity);
  // createVia never re-points reference fields between draft and doc (mutate
  // lines re-bind the same command inputs), so emit payloads reuse the
  // pre-check hydration locals.
  const g7Scope: RenderScope = {
    selfVar: 'doc',
    idExpr: 'docId',
    relationVars: relationHydration.relationVars,
  };
  const g7 = unionEmitPayloadFields(cmd, g7Scope, 'docId');
  diagnostics.push(...g7.diagnostics);
  const events = renderEvents(
    resolveEventsTableName(ir, options),
    ir,
    entity,
    cmd,
    'docId',
    g7Scope,
  );
  diagnostics.push(...events.diagnostics);
  const reactions = renderReactions(ir, options, cmd.emits ?? []);
  diagnostics.push(...reactions.diagnostics);
  const tail = [...events.lines, ...reactions.lines].join('\n');
  const collision = reactionPayloadCollisionPlanner.plan(g7.fields, {
    entity: entity.name,
    command: cmd.name,
  });
  diagnostics.push(...collision.diagnostics);
  const g7Entries = collision.reactionFields
    .map((field) => `${field.name}: ${field.code}`)
    .join(', ');
  const subjectLiteral = `_subject: { entity: ${JSON.stringify(entity.name)}, command: ${JSON.stringify(cmd.name)}, id: docId }`;
  const envelopeResult = collision.includeEnvelopeResult
    ? 'result: { _id: docId, id: docId, ...doc }'
    : '';
  const payloadParts = [
    '_id: docId',
    'id: docId',
    '...doc',
    ...(envelopeResult ? [envelopeResult] : []),
    ...(g7Entries ? [g7Entries] : []),
    subjectLiteral,
  ].join(', ');
  const payloadBinding = /\bpayload\b/.test(tail)
    ? `    const payload: Record<string, any> = { ${payloadParts} };\n`
    : '';

  const argLines = params.map(
    (param) =>
      `    ${param.name}: ${param.required ? paramValidator(param.type) : `v.optional(${paramValidator(param.type)})`}`,
  );
  appendCommandIdempotencyArg(argLines, options);
  const exportName = commandCreationExportName(entity.name, cmd.name);
  // Same binding model as instance commands: params are locals. createVia keeps
  // the `args` bag for draft seeding (`args.<input>`) and destructures into
  // locals so constraint/guard/mutate expressions that reference parameters
  // resolve (locals render verbatim via RenderScope).
  const paramBindLine =
    params.length > 0
      ? `    const { ${params.map((parameter) => parameter.name).join(', ')} } = args;\n`
      : '';
  const bodyText = [
    ...draftLines,
    ...relationHydration.lines,
    ...checks.lines,
    ...mutateLines,
    tail,
    paramBindLine,
  ].join('\n');
  const authLines = authBindings(bodyText, options, tenantScoped);
  const docVar = encryptionActive ? '__storedDoc' : 'doc';

  const code =
    `export const ${exportName} = mutation({\n` +
    `  args: {\n${argLines.join(',\n')}\n  },\n` +
    `  handler: async (ctx, args: any) => {\n` +
    (commandIdempotencyEnabled(options)
      ? `${renderCommandIdempotencyPrologue().join('\n')}\n`
      : '') +
    (authLines.length ? authLines.join('\n') + '\n' : '') +
    paramBindLine +
    `    const __draft: Record<string, any> = {\n${draftLines.join(',\n')}${draftLines.length ? '\n' : ''}    };\n` +
    (relationHydration.lines.length ? relationHydration.lines.join('\n') + '\n' : '') +
    (checks.lines.length ? checks.lines.join('\n') + '\n' : '') +
    `    const doc: Record<string, any> = {\n` +
    `      ...__draft,\n` +
    (mutateLines.length ? `${mutateLines.join(',\n')},\n` : '') +
    (versionLines.length ? `${versionLines.join(',\n')},\n` : '') +
    `    };\n` +
    (encryptionActive
      ? `    const __storedDoc = await __encryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(mutationEncrypted)}, doc);\n`
      : '') +
    `    const docId = await ctx.db.insert("${table}", ${docVar} as any);\n` +
    payloadBinding +
    (tail ? tail + '\n' : '') +
    (commandIdempotencyEnabled(options)
      ? `${renderCommandIdempotencyEpilogue(exportName, '{ docId }').join('\n')}\n`
      : `    return { docId };\n`) +
    `  },\n});`;
  return { code, diagnostics };
}

function generateMutation(
  ir: IR,
  options: Normalized,
  cmd: IRCommand,
): { code: string; diagnostics: ProjectionDiagnostic[] } | null {
  if (!cmd.entity) return null;
  const entity = ir.entities.find((e) => e.name === cmd.entity);
  if (!entity || !isPersistentEntity(entity, ir)) return null;

  const diagnostics: ProjectionDiagnostic[] = [];
  const table = resolveConvexTableName(entity.name, options);
  const name = `${entity.name}_${cmd.name}`;
  const runnerName = commandRunnerName(entity.name, cmd.name);
  const fkTargets = collectFkTargets(entity, ir, options);
  const isCreate = cmd.name === 'create';
  const paramNames = (cmd.parameters ?? []).map((p) => p.name);

  // Write-side tenant protection, active only with an auth seam: creates set
  // the tenant column server-side (never a client argument), instance commands
  // verify the document belongs to the caller's tenant.
  const writeTenantProp = options.tenantIdProperty ?? ir.tenant?.property;
  const tenantScoped =
    !!options.authContextImport &&
    !!writeTenantProp &&
    entity.properties.some((p) => p.name === writeTenantProp);
  // Mutation RESULTS are client-visible too — strip private fields from them
  // exactly like the query surfaces do.
  const mutationPrivates = privateFieldNames(entity);
  const mutationEncrypted = encryptedFieldNames(entity);
  const encryptionActive = mutationEncrypted.length > 0 && !!options.encryptionImport;

  if (isCreate) {
    // Unified create model. Every stored field must be reachable so the insert
    // satisfies the schema: it is either (a) set by a `mutate` action, (b) filled
    // from its default, or (c) exposed as a mutation argument the caller provides.
    // Command parameters that feed actions (and are not themselves fields) are
    // also exposed as args. All expressions resolve against `args`.
    const params = cmd.parameters ?? [];
    const relationHydration = renderRelationHydration(
      ir,
      options,
      entity,
      cmd,
      'args',
      tenantScoped,
      writeTenantProp,
    );
    diagnostics.push(...relationHydration.diagnostics);
    const scope: RenderScope = {
      selfVar: 'args',
      relationVars: relationHydration.relationVars,
      resolveCollectionElementType: (collection) =>
        resolveHasManyDocElementType(entity, collection, options),
    };
    const argLines: string[] = [];
    const argNames = new Set<string>();
    const docLines: string[] = [];

    // Fields set by mutate actions (mapped from params); not exposed as args.
    // A create action targeting the tenant column is overridden by the seam —
    // the tenant id is always server-derived, never caller-influenced.
    if (
      tenantScoped &&
      (cmd.actions ?? []).some((a) => a.kind === 'mutate' && a.target === writeTenantProp)
    ) {
      diagnostics.push({
        severity: 'info',
        code: 'CONVEX_TENANT_SERVER_DERIVED',
        entity: entity.name,
        message: `create action sets '${writeTenantProp}'; overridden — the tenant id is derived from the auth context.`,
      });
    }
    const mutates = (cmd.actions ?? []).filter(
      (a) =>
        a.kind === 'mutate' &&
        a.target &&
        !(tenantScoped && a.target === writeTenantProp) &&
        !isConvexVersionManagedField(entity, a.target),
    );
    const targetSet = new Set(mutates.map((a) => a.target as string));

    // Entity properties → args (unless action-set) + doc lines (with defaults).
    for (const p of entity.properties) {
      if (tenantScoped && p.name === writeTenantProp) {
        docLines.push(`      ${p.name}: __auth.${p.name}`);
        argNames.add(p.name); // suppress any same-named command param arg
        continue;
      }
      if (isConvexVersionManagedField(entity, p.name)) {
        // Seeded below — never accept client-supplied version / versionAt.
        argNames.add(p.name);
        continue;
      }
      if (p.name === 'id' || targetSet.has(p.name)) continue;
      const { validator, diagnostics: vd } = buildValidator(
        entity,
        p,
        ir,
        options,
        fkTargets.get(p.name),
      );
      diagnostics.push(...vd);
      if (!validator) continue;
      // Required AND no default → required arg; otherwise optional (caller may
      // omit; default fills in).
      const required = p.modifiers.includes('required') && !p.defaultValue;
      if (!argNames.has(p.name)) {
        argLines.push(`    ${p.name}: ${required ? validator : `v.optional(${validator})`}`);
        argNames.add(p.name);
      }
      docLines.push(
        `      ${p.name}: args.${p.name}${p.defaultValue ? ` ?? ${defaultToTs(p.defaultValue, validator)}` : ''}`,
      );
    }

    // Command params that are not entity fields (they feed actions) → args.
    for (const p of params) {
      if (argNames.has(p.name)) continue;
      const validator = paramValidator(p.type);
      argLines.push(`    ${p.name}: ${p.required ? validator : `v.optional(${validator})`}`);
      argNames.add(p.name);
    }
    appendCommandIdempotencyArg(argLines, options);

    // mutate actions → doc fields (param → field mapping).
    for (const a of mutates) {
      const { code, unresolved } = renderActionValue(entity, a.target, a.expression, scope);
      if (unresolved.length) {
        diagnostics.push({
          severity: 'warning',
          code: 'CONVEX_UNRESOLVED_ACTION',
          entity: entity.name,
          message: `create action '${a.target}' unresolved (${unresolved.join('; ')}); omitted.`,
        });
        continue;
      }
      docLines.push(`      ${a.target}: ${code}`);
    }

    for (const line of convexCreateVersionDocLines(entity)) {
      docLines.push(line);
    }

    const checks = renderChecks(entity.name, commandChecks(ir, cmd, options.policyMode), scope);
    diagnostics.push(...checks.diagnostics);
    // G7 `emit Event { field: expr }`: populate each event-row payload (and the
    // shared reaction payload below) with declared fields evaluated against the
    // post-action instance. `doc` is the created instance; `self.id` → Convex `_id`.
    const g7Scope: RenderScope = {
      selfVar: 'doc',
      idExpr: '_id',
      relationVars: relationHydration.relationVars,
    };
    const g7 = unionEmitPayloadFields(cmd, g7Scope, '_id');
    diagnostics.push(...g7.diagnostics);
    const events = renderEvents(
      resolveEventsTableName(ir, options),
      ir,
      entity,
      cmd,
      '_id',
      g7Scope,
    );
    diagnostics.push(...events.diagnostics);
    const reactions = renderReactions(ir, options, cmd.emits ?? []);
    diagnostics.push(...reactions.diagnostics);
    const tail = [...events.lines, ...reactions.lines].join('\n');
    // Reaction expressions resolve `payload` against the reference-runtime
    // contract (runtime-engine.ts): the emitted event payload is `{ ...input,
    // result }` then G7 fields overwrite; reactions additionally see `_subject`.
    // When G7 declares `result`, keep the business field and omit the envelope
    // (entity identity stays on `_subject`) — never emit duplicate object keys.
    const collision = reactionPayloadCollisionPlanner.plan(g7.fields, {
      entity: entity.name,
      command: cmd.name,
    });
    diagnostics.push(...collision.diagnostics);
    const g7Entries = collision.reactionFields.map((f) => `${f.name}: ${f.code}`).join(', ');
    const subjectLiteral = `_subject: { entity: ${JSON.stringify(entity.name)}, command: ${JSON.stringify(cmd.name)}, id: _id }`;
    const envelopeResult = collision.includeEnvelopeResult
      ? 'result: { _id, id: _id, ...doc }'
      : '';
    const payloadParts = [
      '_id',
      'id: _id',
      '...doc',
      ...(envelopeResult ? [envelopeResult] : []),
      ...(g7Entries ? [g7Entries] : []),
      subjectLiteral,
    ].join(', ');
    const payloadBinding = /\bpayload\b/.test(tail)
      ? `    const payload: Record<string, any> = { ${payloadParts} };\n`
      : '';
    const bodyText = [...relationHydration.lines, ...checks.lines, tail].join('\n');
    const authLines = authBindings(bodyText, options, tenantScoped);

    const createReturn = stripPrivateFromReturn('{ _id, ...doc }', mutationPrivates);
    const body =
      `async function ${runnerName}(ctx: MutationCtx, args: any) {\n` +
      (authLines.length ? authLines.join('\n') + '\n' : '') +
      (relationHydration.lines.length ? relationHydration.lines.join('\n') + '\n' : '') +
      `    const doc: Record<string, any> = {\n${docLines.join(',\n')}\n    };\n` +
      (checks.lines.length ? checks.lines.join('\n') + '\n' : '') +
      (encryptionActive
        ? `    const __storedDoc = await __encryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(mutationEncrypted)}, doc);\n`
        : '') +
      `    const _id = await ctx.db.insert("${table}", ${encryptionActive ? '__storedDoc' : 'doc'} as any);\n` +
      payloadBinding +
      (tail ? tail + '\n' : '') +
      `${createReturn}\n` +
      `}\n\n` +
      `export const ${name} = mutation({\n` +
      `  args: {\n${argLines.join(',\n')}\n  },\n` +
      `  handler: ` +
      (commandIdempotencyEnabled(options)
        ? `async (ctx, args) => {\n${renderCommandIdempotencyPrologue().join('\n')}\n    const __result = await ${runnerName}(ctx, args);\n    if (args.idempotencyKey !== undefined) {\n      await __setCommandIdempotency(ctx, args.idempotencyKey, ${JSON.stringify(name)}, __result);\n    }\n    return __result;\n  }`
        : runnerName) +
      `,\n});`;
    return { code: body, diagnostics };
  }

  // Non-create mutation
  const versionOcc = renderConvexUpdateVersionOcc(entity);
  const argLines = [`    docId: v.id("${table}")`];
  for (const p of cmd.parameters ?? []) {
    argLines.push(
      `    ${p.name}: ${p.required ? paramValidator(p.type) : `v.optional(${paramValidator(p.type)})`}`,
    );
  }
  if (versionOcc.argLine) {
    argLines.push(versionOcc.argLine);
  }
  appendCommandIdempotencyArg(argLines, options);

  // Non-create: command params are destructured locals; self.x → doc.x.
  const checkSpecs = commandChecks(ir, cmd, options.policyMode);
  const aggregateExprs = checkSpecs.map((c) => c.expr);
  const aggregateHydration = planAndRenderAggregateHydration(
    ir,
    entity,
    aggregateExprs,
    options,
    'docId',
  );
  const hasManyPreloads = aggregateHydration.lines;
  // Preserve one-hop count_of support detection for relation-plan skip logic.
  const countOfRels = new Set<string>();
  for (const c of checkSpecs) collectCountOfHasManyRels(c.expr, countOfRels);
  const supportedHasMany = new Set(
    [...countOfRels, ...aggregateHydration.rootHasMany].filter((relationName) =>
      hasManyPreloads.some((line) => line.includes(`.${relationName} =`)),
    ),
  );
  const relationHydration = renderRelationHydration(
    ir,
    options,
    entity,
    cmd,
    'doc',
    tenantScoped,
    writeTenantProp,
    supportedHasMany,
  );
  diagnostics.push(...relationHydration.diagnostics);
  const checks = renderChecks(entity.name, checkSpecs, {
    selfVar: 'doc',
    locals: paramNames,
    relationVars: relationHydration.relationVars,
    resolveCollectionElementType: (collection) =>
      resolveHasManyDocElementType(entity, collection, options),
  });
  diagnostics.push(...checks.diagnostics);

  // IR `compute` bindings: evaluate against pre-update `doc`, then expose as
  // locals to mutate actions and emit payloads (semantics.md § Actions).
  const compute = renderCommandComputeBindings(cmd, {
    selfVar: 'doc',
    locals: paramNames,
    relationVars: relationHydration.relationVars,
  });
  diagnostics.push(...compute.diagnostics);
  const computeLocals = compute.localNames;
  const actionLocals = [...paramNames, ...computeLocals];

  const updateLines: string[] = [];
  const resolvedUpdates: {
    target: string;
    expression: IRExpression;
    renderedCode: string;
  }[] = [];
  for (const a of cmd.actions ?? []) {
    if (a.kind !== 'mutate' || !a.target) continue;
    if (isConvexVersionManagedField(entity, a.target)) continue;
    const { code, unresolved } = renderActionValue(entity, a.target, a.expression, {
      selfVar: 'doc',
      locals: actionLocals,
      relationVars: relationHydration.relationVars,
    });
    if (unresolved.length) {
      diagnostics.push({
        severity: 'warning',
        code: 'CONVEX_UNRESOLVED_ACTION',
        entity: entity.name,
        message: `action mutate '${a.target}' unresolved (${unresolved.join('; ')}); omitted.`,
      });
      continue;
    }
    updateLines.push(`      ${a.target}: ${code}`);
    resolvedUpdates.push({ target: a.target, expression: a.expression, renderedCode: code });
  }

  const transitions = renderTransitionChecks(entity, cmd, 'doc', resolvedUpdates, '__creation');
  diagnostics.push(...transitions.diagnostics);

  // Post-action snapshot for G7 / schema synthesis. Current fields → `__after`;
  // previous-state fields → `compute` locals (pre-update expressions).
  const needsAfter = commandNeedsAfterSnapshot(ir, entity, cmd);
  // Emit payloads see relations through hydrated locals. When a mutate action
  // re-points one of the relation's reference fields, re-resolve from the
  // post-update snapshot so the payload reflects the new target, matching the
  // runtime's lazy post-mutation resolution.
  const mutatedTargets = new Set(resolvedUpdates.map((update) => update.target));
  const staleEmitRelations = new Set(
    relationHydration.plan.relations
      .filter(
        (dependency) =>
          dependency.phases.includes('emit') &&
          dependency.localFields.some((field) => mutatedTargets.has(field)),
      )
      .map((dependency) => dependency.relationName),
  );
  const postHydration = staleEmitRelations.size
    ? renderRelationHydration(
        ir,
        options,
        entity,
        cmd,
        '__after',
        tenantScoped,
        writeTenantProp,
        supportedHasMany,
        { relationNames: staleEmitRelations, varSuffix: '__post' },
      )
    : undefined;
  if (postHydration) diagnostics.push(...postHydration.diagnostics);
  const emitRelationVars = {
    ...relationHydration.relationVars,
    ...(postHydration?.relationVars ?? {}),
  };
  const g7Scope: RenderScope = {
    selfVar: needsAfter || postHydration !== undefined ? '__after' : 'doc',
    locals: actionLocals,
    idExpr: 'docId',
    beforeVar: 'doc',
    relationVars: emitRelationVars,
  };
  const g7 = unionEmitPayloadFields(cmd, g7Scope, 'docId', computeLocals);
  diagnostics.push(...g7.diagnostics);
  const useAfter = needsAfter || postHydration !== undefined;
  const afterLine = useAfter
    ? `    const __after: Record<string, any> = { ...doc, ...updates };\n` +
      (postHydration?.lines.length ? postHydration.lines.join('\n') + '\n' : '')
    : '';
  const events = renderEvents(
    resolveEventsTableName(ir, options),
    ir,
    entity,
    cmd,
    'docId',
    g7Scope,
    computeLocals,
  );
  diagnostics.push(...events.diagnostics);
  const reactions = renderReactions(ir, options, cmd.emits ?? []);
  diagnostics.push(...reactions.diagnostics);

  const tail = [...events.lines, ...reactions.lines].join('\n');
  // Same reference-runtime payload contract as the create branch, including
  // G7 `result` collision handling (business field wins; `_subject` keeps id).
  const collision = reactionPayloadCollisionPlanner.plan(g7.fields, {
    entity: entity.name,
    command: cmd.name,
  });
  diagnostics.push(...collision.diagnostics);
  const g7Entries = collision.reactionFields.map((f) => `${f.name}: ${f.code}`).join(', ');
  const subjectLiteral = `_subject: { entity: ${JSON.stringify(entity.name)}, command: ${JSON.stringify(cmd.name)}, id: docId }`;
  const envelopeResult = collision.includeEnvelopeResult
    ? useAfter
      ? 'result: { id: docId, ...__after }'
      : 'result: { id: docId, ...doc, ...updates }'
    : '';
  const baseParts = useAfter ? ['id: docId', '...__after'] : ['id: docId', '...doc', '...updates'];
  const payloadParts = [
    ...baseParts,
    ...(envelopeResult ? [envelopeResult] : []),
    ...(g7Entries ? [g7Entries] : []),
    subjectLiteral,
  ].join(', ');
  const payloadBinding = /\bpayload\b/.test(tail)
    ? `    const payload: Record<string, any> = { ${payloadParts} };\n`
    : '';
  const argDestructureParts = [...paramNames];
  if (versionOcc.expectedArgName) {
    argDestructureParts.push(versionOcc.expectedArgName);
  }
  const argDestructure = argDestructureParts.length ? `, ${argDestructureParts.join(', ')}` : '';
  const bodyText = [
    ...relationHydration.lines,
    ...checks.lines,
    ...transitions.lines,
    ...versionOcc.checkLines,
    ...updateLines,
    ...versionOcc.updateFields,
    tail,
  ].join('\n');
  const authLines = authBindings(bodyText, options, tenantScoped);
  // Document-tenancy check: an instance command may only touch documents in
  // the caller's tenant. Same message as the missing-doc throw so a cross-
  // tenant probe cannot distinguish "exists elsewhere" from "does not exist".
  const ownershipLine = tenantScoped
    ? `    if ((${encryptionActive ? '__storedDoc' : 'doc'} as any).${writeTenantProp} !== __auth.${writeTenantProp}) throw new Error(${JSON.stringify(`${entity.name} not found`)});\n`
    : '';

  const updateFieldLines = [...updateLines, ...versionOcc.updateFields];
  let body =
    `async function ${runnerName}(ctx: MutationCtx, { docId${argDestructure} }: any, __creation = false) {\n` +
    (authLines.length ? authLines.join('\n') + '\n' : '') +
    (encryptionActive
      ? `    const __storedDoc = await ctx.db.get(docId) as Record<string, any> | null;\n` +
        `    if (!__storedDoc) throw new Error(${JSON.stringify(`${entity.name} not found`)});\n` +
        ownershipLine +
        `    const doc = await __decryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(mutationEncrypted)}, __storedDoc) as Record<string, any>;\n`
      : `    const doc = await ctx.db.get(docId) as Record<string, any> | null;\n` +
        `    if (!doc) throw new Error(${JSON.stringify(`${entity.name} not found`)});\n` +
        ownershipLine) +
    (relationHydration.lines.length ? relationHydration.lines.join('\n') + '\n' : '') +
    (hasManyPreloads.length ? hasManyPreloads.join('\n') + '\n' : '') +
    (checks.lines.length ? checks.lines.join('\n') + '\n' : '') +
    (compute.bindings.length ? computeBindingLines(compute.bindings).join('\n') + '\n' : '') +
    (transitions.lines.length ? transitions.lines.join('\n') + '\n' : '') +
    (versionOcc.checkLines.length ? versionOcc.checkLines.join('\n') + '\n' : '') +
    `    const updates = {\n${updateFieldLines.join(',\n')}${updateFieldLines.length ? '\n' : ''}    };\n` +
    (encryptionActive
      ? `    const __storedUpdates = await __encryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(mutationEncrypted)}, updates);\n`
      : '') +
    `    await ctx.db.patch(docId, ${encryptionActive ? '__storedUpdates' : 'updates'} as any);\n` +
    afterLine +
    payloadBinding +
    (tail ? tail + '\n' : '') +
    stripPrivateFromReturn('{ ...doc, ...updates }', mutationPrivates) +
    `}\n\n` +
    `export const ${name} = mutation({\n` +
    `  args: {\n${argLines.join(',\n')}\n  },\n` +
    `  handler: ${commandIdempotencyEnabled(options) ? renderCommandIdempotencyWrappedRunnerHandler(name, runnerName) : runnerName},\n});`;

  if (commandCreationEntry(ir, entity)?.name === cmd.name) {
    const creation = renderGovernedCreationEntry(
      ir,
      options,
      entity,
      cmd,
      table,
      runnerName,
      tenantScoped,
      writeTenantProp,
      encryptionActive,
      mutationEncrypted,
    );
    diagnostics.push(...creation.diagnostics);
    if (creation.code) body += `\n\n${creation.code}`;
  }
  return { code: body, diagnostics };
}

export function generateMutations(
  ir: IR,
  rawOptions: Record<string, unknown> | undefined,
): FunctionsResult {
  const options = normalizeOptions(rawOptions);
  const diagnostics: ProjectionDiagnostic[] = [];
  const blocks: string[] = [];

  for (const cmd of ir.commands) {
    const m = generateMutation(ir, options, cmd);
    if (!m) continue;
    blocks.push(m.code);
    diagnostics.push(...m.diagnostics);
  }

  // Emit helpers only when the generated mutations actually reference them
  // (a policyMode:'skip' build may use neither), so there is no dead code.
  const body = blocks.join('\n\n');
  const helpers: string[] = [];
  const needsEncrypt = !!options.encryptionImport && /\b__encryptDoc\b/.test(body);
  const needsDecrypt = !!options.encryptionImport && /\b__decryptDoc\b/.test(body);
  if (needsEncrypt) helpers.push(ENCRYPT_HELPER);
  if (needsDecrypt) helpers.push(DECRYPT_HELPER);
  if (/\b__resolveRelation\(/.test(body)) helpers.push(RELATION_HELPER);
  if (commandIdempotencyEnabled(options) || /\b__getCommandIdempotency\b/.test(body)) {
    helpers.push(renderCommandIdempotencyHelpers(options.commandIdempotencyTable));
  }
  if (/\bcheckRole\(/.test(body)) {
    helpers.push(
      `// Role hierarchy from IR (effective permissions after inheritance).\n` +
        `const ROLE_PERMISSIONS: Record<string, { action: string; target?: string }[]> = ${roleMapLiteral(ir)};\n\n` +
        `function checkRole(userRole: unknown, action: unknown, target?: unknown): boolean {\n` +
        `  if (typeof userRole !== "string" || typeof action !== "string") return false;\n` +
        `  const perms = ROLE_PERMISSIONS[userRole];\n` +
        `  const requestedTarget = typeof target === "string" ? target : undefined;\n` +
        `  return perms ? perms.some((permission) =>\n` +
        `    (permission.action === action || permission.action === "all") &&\n` +
        `    (permission.target === undefined || permission.target === requestedTarget)\n` +
        `  ) : false;\n` +
        `}`,
    );
  }
  if (/\bflag\(/.test(body)) {
    helpers.push(
      `// Feature toggle (configurable). Not an authorization gate.\nfunction flag(_name?: string): boolean { return true; }`,
    );
  }

  const policyNote =
    options.policyMode === 'skip' ? ' (policyMode: skip — authorization policies omitted)' : '';
  const needsAuthCtx = !!options.authContextImport && /\bgetAuthContext\b/.test(body);
  const needsDoc = codeUsesDocType(body);
  const code =
    `${GENERATED_HEADER}\n// ${blocks.length} mutation(s); roles: ${(ir.roles ?? []).length}; policies: ${ir.policies.length}.${policyNote}\n\n` +
    `import { mutation, type MutationCtx } from "./_generated/server";\n` +
    `import { v } from "convex/values";\n` +
    (needsDoc ? `import type { Doc } from "./_generated/dataModel";\n` : '') +
    (needsAuthCtx
      ? `import { getAuthContext } from ${JSON.stringify(options.authContextImport)};\n`
      : '') +
    (needsEncrypt || needsDecrypt
      ? `import { ${[needsEncrypt ? 'encrypt' : '', needsDecrypt ? 'decrypt' : ''].filter(Boolean).join(', ')} } from ${JSON.stringify(options.encryptionImport)};\n`
      : '') +
    `\n` +
    (helpers.length ? helpers.join('\n\n') + '\n\n' : '') +
    `${body}\n`;

  return { code, diagnostics };
}
