/**
 * Convex functions surfaces: `convex.queries` and `convex.mutations`.
 *
 * Queries are reactive reads over `ctx.db` (reads are not governed). Mutations
 * are governed writes: each IR command becomes a Convex `mutation` that runs the
 * command's policies → guards → constraints (rendered from IR via the
 * fail-closed expression resolver), applies the command's mutate actions,
 * appends an event row, and fires matched reactions.
 *
 * Governance is rendered FAIL CLOSED: any guard/policy/constraint the resolver
 * cannot fully map produces a hard diagnostic AND a denying `throw`, never a
 * silent pass.
 */

import type {
  IR,
  IRCommand,
  IRConstraint,
  IREntity,
  IRExpression,
  IRPolicy,
  IRProperty,
  IRReactionParam,
  IRReactionRule,
  IRValue,
} from '../../ir';
import type { ProjectionDiagnostic } from '../interface';
import { normalizeOptions } from './options.js';
import {
  resolveConvexTableName,
  collectFkTargets,
  collectReferenceFields,
  indexEntryToDef,
  buildValidator,
  isPersistentEntity,
  resolveEventsTableName,
  type NormalizedOptions,
} from './generator.js';
import { resolveConvexValidator } from './type-mapping.js';
import { ReactionPayloadCollisionPlanner } from './reactionPayloadCollision.js';
import {
  codeUsesDocType,
  collectCountOfHasManyRels,
  renderCountOfHasManyPreloads,
  resolveHasManyDocElementType,
} from './count-of-preload.js';
import {
  renderExpression,
  isNullLiteral,
  type RenderScope,
  type RenderResult,
} from './expression.js';
import { renderTransitionChecks } from './transitions.js';
import {
  commandCreationEntry,
  commandCreationExportName,
  commandRunnerName,
} from './creation-entry.js';
import {
  convexCreateVersionDocLines,
  isConvexVersionManagedField,
  renderConvexUpdateVersionOcc,
} from './version-occ.js';
import {
  renderReadPolicies,
  resolveConvexReadVisibility,
} from './read-policies.js';
import {
  encryptedFieldNames,
  privateFieldNames,
  stripPrivateFromDoc,
  stripPrivateFromReturn,
  stripPrivateFromRows,
} from './privacy.js';
import { renderInlineComputedFields } from './computed.js';
import {
  commandNeedsAfterSnapshot,
  computeBindingLines,
  renderCommandComputeBindings,
  renderEvents,
  unionEmitPayloadFields,
} from './event-payload.js';

type Normalized = NormalizedOptions;

const reactionPayloadCollisionPlanner = new ReactionPayloadCollisionPlanner();

export interface FunctionsResult {
  code: string;
  diagnostics: ProjectionDiagnostic[];
}

const GENERATED_HEADER = '// GENERATED by the Manifest → Convex projection. DO NOT EDIT.';

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function persistentEntities(ir: IR): IREntity[] {
  return ir.entities.filter((e) => isPersistentEntity(e, ir));
}

const ENCRYPT_HELPER = `async function __encryptDoc(ctx: any, entity: string, fields: readonly string[], doc: Record<string, any>): Promise<Record<string, any>> {
  const out = { ...doc };
  for (const property of fields) {
    const value = out[property];
    if (value == null) continue;
    const { ciphertext, keyId } = await encrypt(String(value), { ctx, entity, property });
    out[property] = JSON.stringify({ v: 1, kid: keyId, ct: ciphertext });
  }
  return out;
}`;

const DECRYPT_HELPER = `async function __decryptDoc(ctx: any, entity: string, fields: readonly string[], doc: any): Promise<any> {
  if (!doc) return doc;
  const out = { ...doc } as Record<string, any>;
  for (const property of fields) {
    const raw = out[property];
    if (typeof raw !== "string") continue;
    let envelope: any;
    try { envelope = JSON.parse(raw); } catch { continue; }
    const looksEncrypted = envelope && typeof envelope === "object" && "v" in envelope && "kid" in envelope && "ct" in envelope;
    if (!looksEncrypted) continue;
    if (envelope.v !== 1) throw new Error(\`Unsupported Manifest encryption envelope version: \${String(envelope.v)}\`);
    out[property] = await decrypt(envelope.ct, envelope.kid, { ctx, entity, property });
  }
  return out;
}`;

const READ_POLICY_HELPER = `function __allowsRead(policy: string, entity: string, check: () => unknown): boolean {
  try {
    return !!check();
  } catch (error) {
    console.warn(\`[Manifest Convex] read policy '\${policy}' evaluation error for '\${entity}' (read denied)\`, error);
    return false;
  }
}`;

/**
 * Render an IR default value to a TS literal that satisfies a Convex validator.
 *
 * Two of the projection's type mappings are *representational*: `int`/`bigint`
 * map to `v.int64()` (a JS `bigint`) and `decimal`/`money` map to `v.string()`
 * (lossless decimal transport — Convex has no native Decimal). A structurally
 * faithful render of an IR `number` default (`1`) is the WRONG runtime type for
 * those validators — Convex rejects a JS number where it expects a bigint or a
 * string — so the create-mutation default fill would fail schema validation at
 * insert time. Coerce numeric leaves to the validator's representation.
 *
 * `validator` is the field's resolved expression (possibly `v.optional`/
 * `v.array`-wrapped); detection is structural so per-property `typeMappings`
 * overrides are honored. Arrays share their element validator, so it propagates
 * to elements; objects carry heterogeneous members the field validator does not
 * describe, so their members are rendered structurally (no coercion).
 */
function defaultToTs(value: IRValue, validator?: string): string {
  switch (value.kind) {
    case 'string':
      return JSON.stringify(value.value);
    case 'number':
      // int64 wants a bigint literal; a non-integer default on an int field is
      // an authoring contradiction — surface it as a type error, don't truncate.
      if (validator && /\bv\.int64\(\)/.test(validator) && Number.isInteger(value.value)) {
        return `${value.value}n`;
      }
      // decimal/money (and stringId FKs) transport as strings.
      if (validator && /\bv\.string\(\)/.test(validator)) {
        return JSON.stringify(String(value.value));
      }
      return String(value.value);
    case 'boolean':
      return String(value.value);
    case 'null':
      return 'null';
    case 'array':
      return `[${value.elements.map((el) => defaultToTs(el, validator)).join(', ')}]`;
    case 'object':
      return `{${Object.entries(value.properties)
        .map(([k, v]) => `${JSON.stringify(k)}: ${defaultToTs(v)}`)
        .join(', ')}}`;
  }
}

/**
 * Render a mutate-action right-hand side, converting a literal-`null` assignment
 * to a NON-nullable field into `undefined`. Convex rejects `null` for an
 * `v.optional(T)` column but treats `undefined` as "unset" — so a DSL `= null`
 * "clear"/"restore" must lower to field omission, not a rejected null write.
 * Nullable fields (schema `v.union(T, v.null())`) keep `null`.
 */
function renderActionValue(
  entity: IREntity,
  target: string | undefined,
  expression: IRExpression,
  scope: RenderScope,
): RenderResult {
  const res = renderExpression(expression, scope);
  if (res.unresolved.length === 0 && target && isNullLiteral(expression)) {
    const targetProp = entity.properties.find((p) => p.name === target);
    if (targetProp?.type.nullable !== true) {
      return { code: 'undefined', unresolved: res.unresolved };
    }
  }
  return res;
}

/**
 * Validator expression for a command parameter (no optional wrap). Mirrors the
 * entity-field `array<T>` handling so an `array`-typed param maps to
 * `v.array(<element>)` instead of collapsing to a structureless `v.any()`.
 * Unknown leaf types still fall back to `v.any()` (params are not schema fields,
 * so an unmapped type is permissive rather than a hard diagnostic).
 */
function paramValidator(type: { name: string; generic?: { name: string } }): string {
  if ((type.name === 'array' || type.name === 'list') && type.generic) {
    const element = resolveConvexValidator(type.generic.name, undefined, '') ?? 'v.any()';
    return `v.array(${element})`;
  }
  return resolveConvexValidator(type.name, undefined, '') ?? 'v.any()';
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

function capWord(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

interface QueryIndexField {
  /** Column being matched (also the arg name). */
  name: string;
  /** Target table when the column is a convexId reference (→ `v.id(...)` arg). */
  fkTarget?: string;
}

interface QueryIndexSpec {
  /** Columns the index covers, in order (single-field or composite). */
  fields: QueryIndexField[];
  /** Schema index name to read via `withIndex(...)`. */
  indexName: string;
}

/**
 * The indexes an entity exposes as reads, derived to match EXACTLY what the
 * schema surface emits (`generator.ts#emitTable`): `indexed`-modifier properties,
 * the tenant column, every belongsTo/ref FK (in BOTH reference modes), and every
 * `options.indexes` entry (single-field AND composite). Single-field specs are
 * deduped by column in schema order; composite specs by index name. The result
 * guarantees every schema index has a corresponding `list<Entity>By<Field...>`
 * query — the two surfaces can no longer drift (closing both the stringId-mode
 * FK gap and the composite-index gap).
 */
function collectQueryIndexSpecs(ir: IR, entity: IREntity, options: Normalized): QueryIndexSpec[] {
  const specs: QueryIndexSpec[] = [];
  const seenSingle = new Set<string>();
  const seenName = new Set<string>();
  // convexId-only targets: present → arg typed `v.id(target)`; absent → `v.string()`.
  const fkTargets = collectFkTargets(entity, ir, options);
  const mkField = (name: string): QueryIndexField => ({ name, fkTarget: fkTargets.get(name) });

  const addSingle = (field: string, indexName: string): void => {
    if (field === 'id' || seenSingle.has(field)) return;
    seenSingle.add(field);
    seenName.add(indexName);
    specs.push({ fields: [mkField(field)], indexName });
  };

  for (const p of entity.properties) {
    if (p.modifiers.includes('indexed')) addSingle(p.name, `by_${p.name}`);
  }
  const tenantProp = ir.tenant?.property;
  if (tenantProp && entity.properties.some((p) => p.name === tenantProp))
    addSingle(tenantProp, `by_${tenantProp}`);
  for (const fk of collectReferenceFields(entity, ir, options).keys()) addSingle(fk, `by_${fk}`);
  for (const entry of options.indexes[entity.name] ?? []) {
    const def = indexEntryToDef(entry);
    if (def.fields.length === 1) {
      addSingle(def.fields[0], def.name);
    } else if (def.fields.length > 1 && !seenName.has(def.name)) {
      seenName.add(def.name);
      specs.push({ fields: def.fields.map(mkField), indexName: def.name });
    }
  }
  return specs;
}

/**
 * Tenant-id binding for a handler body. Identity comes from the author-owned
 * `getAuthContext(ctx)` module ({@link NormalizedOptions.authContextImport}).
 * Generation fails with `CONVEX_AUTH_CONTEXT_REQUIRED` when tenant filtering is
 * on without that import — this path is never reached for the broken legacy
 * `(ctx as any).auth` bag.
 */
function tenantBindingLine(_options: Normalized, tenantProp: string): string {
  return `    const __tenant = ((await getAuthContext(ctx)) as any).${tenantProp} ?? null;`;
}

/** Resolved read-side tenant + soft-delete filtering for an entity (field-aware). */
interface ReadFilter {
  hasTenant: boolean;
  tenantProp: string | undefined;
  /** The `by_<tenantProp>` index exists in the schema (IR-declared tenant). */
  tenantIndexed: boolean;
  hasSoftDelete: boolean;
  deletedProp: string;
}

function resolveReadFilter(ir: IR, entity: IREntity, options: Normalized): ReadFilter {
  const tenantProp = options.tenantIdProperty ?? ir.tenant?.property;
  // Tenant scoping requires a real identity seam — never the ineffective ctx.auth bag.
  const hasTenant =
    options.includeTenantFilter &&
    !!options.authContextImport &&
    !!tenantProp &&
    entity.properties.some((p) => p.name === tenantProp);
  const deletedProp = options.deletedAtProperty;
  const hasSoftDelete =
    options.includeSoftDeleteFilter && entity.properties.some((p) => p.name === deletedProp);
  return {
    hasTenant,
    tenantProp: hasTenant ? tenantProp : undefined,
    tenantIndexed: hasTenant && tenantProp === ir.tenant?.property,
    hasSoftDelete,
    deletedProp,
  };
}

type PolicyPrelude = (deniedValue: '[]' | 'null') => string[];
type FinishRows = (rowsExpr: string) => string;
type FinishDoc = (docExpr: string) => string;

function emitListEntityQuery(
  blocks: string[],
  entity: IREntity,
  table: string,
  rf: ReadFilter,
  options: Normalized,
  qfn: string,
  policyPrelude: PolicyPrelude,
  finishRows: FinishRows,
): void {
  if (!rf.hasTenant && !rf.hasSoftDelete) {
    const bodyLines = [
      ...policyPrelude('[]'),
      `    ${finishRows(`await ctx.db.query("${table}").collect()`)}`,
    ].join('\n');
    blocks.push(
      `export const list${entity.name} = ${qfn}({\n` +
        `  args: {},\n` +
        `  handler: async (ctx) => {\n` +
        `${bodyLines}\n` +
        `  },\n});`,
    );
    return;
  }
  const lines: string[] = [...policyPrelude('[]')];
  if (rf.hasTenant) lines.push(tenantBindingLine(options, rf.tenantProp!));
  if (rf.hasTenant && rf.tenantIndexed) {
    lines.push(
      `    let rows = await ctx.db.query("${table}").withIndex("by_${rf.tenantProp}", (q) => q.eq("${rf.tenantProp}", __tenant)).collect();`,
    );
  } else {
    lines.push(`    let rows = await ctx.db.query("${table}").collect();`);
    if (rf.hasTenant) {
      lines.push(`    rows = rows.filter((d) => (d as any).${rf.tenantProp} === __tenant);`);
    }
  }
  if (rf.hasSoftDelete) {
    lines.push(`    rows = rows.filter((d) => (d as any).${rf.deletedProp} == null);`);
  }
  lines.push(`    ${finishRows('rows')}`);
  blocks.push(
    `export const list${entity.name} = ${qfn}({\n` +
      `  args: {},\n` +
      `  handler: async (ctx) => {\n${lines.join('\n')}\n  },\n});`,
  );
}

function emitGetEntityQuery(
  blocks: string[],
  entity: IREntity,
  table: string,
  rf: ReadFilter,
  options: Normalized,
  qfn: string,
  policyPrelude: PolicyPrelude,
  finishDoc: FinishDoc,
): void {
  if (!rf.hasTenant && !rf.hasSoftDelete) {
    const bodyLines = [...policyPrelude('null'), `    ${finishDoc(`await ctx.db.get(id)`)}`].join(
      '\n',
    );
    blocks.push(
      `export const get${entity.name} = ${qfn}({\n` +
        `  args: { id: v.id("${table}") },\n` +
        `  handler: async (ctx, { id }) => {\n` +
        `${bodyLines}\n` +
        `  },\n});`,
    );
    return;
  }
  const lines: string[] = [...policyPrelude('null'), `    const doc = await ctx.db.get(id);`];
  if (rf.hasTenant) {
    lines.push(tenantBindingLine(options, rf.tenantProp!));
    lines.push(`    if (doc && (doc as any).${rf.tenantProp} !== __tenant) return null;`);
  }
  if (rf.hasSoftDelete) {
    lines.push(`    if (doc && (doc as any).${rf.deletedProp} != null) return null;`);
  }
  lines.push(`    ${finishDoc('doc')}`);
  blocks.push(
    `export const get${entity.name} = ${qfn}({\n` +
      `  args: { id: v.id("${table}") },\n` +
      `  handler: async (ctx, { id }) => {\n${lines.join('\n')}\n  },\n});`,
  );
}

function emitListByIndexQueries(
  blocks: string[],
  ir: IR,
  entity: IREntity,
  table: string,
  rf: ReadFilter,
  options: Normalized,
  qfn: string,
  policyPrelude: PolicyPrelude,
  finishRows: FinishRows,
): void {
  for (const spec of collectQueryIndexSpecs(ir, entity, options)) {
    const names = spec.fields.map((f) => f.name);
    const suffix = spec.fields.map((f) => capWord(f.name)).join('And');
    const argList = spec.fields
      .map((f) => `${f.name}: ${f.fkTarget ? `v.id("${f.fkTarget}")` : 'v.string()'}`)
      .join(', ');
    const destructure = `{ ${names.join(', ')} }`;
    const eqChain = spec.fields.map((f) => `.eq("${f.name}", ${f.name})`).join('');
    const applyTenant = rf.hasTenant && !!rf.tenantProp && !names.includes(rf.tenantProp);

    if (!applyTenant && !rf.hasSoftDelete) {
      const bodyLines = [
        ...policyPrelude('[]'),
        `    ${finishRows(
          `await ctx.db.query("${table}").withIndex("${spec.indexName}", (q) => q${eqChain}).collect()`,
        )}`,
      ].join('\n');
      blocks.push(
        `export const list${entity.name}By${suffix} = ${qfn}({\n` +
          `  args: { ${argList} },\n` +
          `  handler: async (ctx, ${destructure}) => {\n` +
          `${bodyLines}\n` +
          `  },\n});`,
      );
      continue;
    }

    const lines: string[] = [...policyPrelude('[]')];
    if (applyTenant) lines.push(tenantBindingLine(options, rf.tenantProp!));
    lines.push(
      `    let rows = await ctx.db.query("${table}").withIndex("${spec.indexName}", (q) => q${eqChain}).collect();`,
    );
    if (applyTenant) {
      lines.push(`    rows = rows.filter((d) => (d as any).${rf.tenantProp} === __tenant);`);
    }
    if (rf.hasSoftDelete) {
      lines.push(`    rows = rows.filter((d) => (d as any).${rf.deletedProp} == null);`);
    }
    lines.push(`    ${finishRows('rows')}`);
    blocks.push(
      `export const list${entity.name}By${suffix} = ${qfn}({\n` +
        `  args: { ${argList} },\n` +
        `  handler: async (ctx, ${destructure}) => {\n${lines.join('\n')}\n  },\n});`,
    );
  }
}

export function generateQueries(
  ir: IR,
  rawOptions: Record<string, unknown> | undefined,
): FunctionsResult {
  const options = normalizeOptions(rawOptions);
  const diagnostics: ProjectionDiagnostic[] = [];
  const blocks: string[] = [];

  for (const entity of persistentEntities(ir)) {
    const visibility = resolveConvexReadVisibility(
      ir,
      entity.name,
      options.authContextImport,
      '__row',
    );
    const listPolicyPlan = visibility.policies;
    const docPolicyPlan = renderReadPolicies(ir, entity.name, '__doc');
    diagnostics.push(...listPolicyPlan.diagnostics);
    const policyGated = visibility.gated;
    const policyEnforceable = visibility.clientReadable;
    const qfn = policyEnforceable ? 'query' : 'internalQuery';
    const table = resolveConvexTableName(entity.name, options);
    const rf = resolveReadFilter(ir, entity, options);
    const privates = privateFieldNames(entity);
    const encrypted = encryptedFieldNames(entity);
    const inlineComputed =
      options.computedProperties === 'inline'
        ? renderInlineComputedFields(entity, '__row', options)
        : {
            fields: [] as { name: string; code: string }[],
            diagnostics: [] as ProjectionDiagnostic[],
          };
    diagnostics.push(...inlineComputed.diagnostics);
    const allPolicyChecks = [...listPolicyPlan.contextChecks, ...listPolicyPlan.rowChecks];
    const policyAuthLines = (): string[] => {
      const text = allPolicyChecks.map((check) => check.code).join('\n');
      const needsUser = /\buser\b/.test(text);
      const needsContext = /\bcontext\b/.test(text);
      if (!needsUser && !needsContext) return [];
      return [
        `    const __auth = (await getAuthContext(ctx)) as any;`,
        ...(needsUser ? [`    const user = (__auth.user ?? __auth) as any;`] : []),
        ...(needsContext ? [`    const context = (__auth.context ?? __auth) as any;`] : []),
      ];
    };
    const policyPrelude = (deniedValue: '[]' | 'null'): string[] => {
      if (!policyGated || !policyEnforceable) return [];
      return [
        ...policyAuthLines(),
        ...listPolicyPlan.contextChecks.map(
          (check) =>
            `    if (!__allowsRead(${JSON.stringify(check.policyName)}, ${JSON.stringify(entity.name)}, () => ${check.code})) return ${deniedValue};`,
        ),
      ];
    };

    /** Finalize rows: decrypt → read policies → computed/private public projection. */
    const finishRows = (rowsExpr: string): string => {
      if (encrypted.length === 0 && !policyGated) {
        if (inlineComputed.fields.length === 0) {
          return stripPrivateFromRows(rowsExpr, privates);
        }
        const assigns = inlineComputed.fields.map((f) => `${f.name}: ${f.code}`).join(', ');
        const mapped = `(${rowsExpr}).map((__row) => ({ ...(__row as any), ${assigns} }))`;
        return stripPrivateFromRows(mapped, privates);
      }

      const lines: string[] = [];
      const plainExpr =
        encrypted.length > 0 && options.encryptionImport
          ? `await Promise.all((${rowsExpr}).map((row) => __decryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(encrypted)}, row)))`
          : rowsExpr;
      lines.push(`const __plainRows = ${plainExpr};`);
      let visibleExpr = '__plainRows';
      if (policyGated && policyEnforceable) {
        if (listPolicyPlan.rowChecks.length > 0) {
          lines.push(`    const __visibleRows: any[] = [];`);
          lines.push(`    for (const __row of __plainRows) {`);
          for (const check of listPolicyPlan.rowChecks) {
            lines.push(
              `      if (!__allowsRead(${JSON.stringify(check.policyName)}, ${JSON.stringify(entity.name)}, () => ${check.code})) continue;`,
            );
          }
          lines.push(`      __visibleRows.push(__row);`);
          lines.push(`    }`);
          visibleExpr = '__visibleRows';
        }
      }
      if (inlineComputed.fields.length > 0) {
        const assigns = inlineComputed.fields.map((f) => `${f.name}: ${f.code}`).join(', ');
        visibleExpr = `(${visibleExpr}).map((__row) => ({ ...(__row as any), ${assigns} }))`;
      }
      lines.push(`    ${stripPrivateFromRows(visibleExpr, privates)}`);
      return lines.join('\n');
    };
    /** Finalize one doc: decrypt → read policies → computed/private projection. */
    const finishDoc = (docExpr: string): string => {
      if (encrypted.length === 0 && !policyGated) {
        if (inlineComputed.fields.length === 0) {
          return stripPrivateFromDoc(docExpr, privates);
        }
        const assigns = inlineComputed.fields
          .map((f) => `${f.name}: ${f.code.replace(/\b__row\b/g, '__doc')}`)
          .join(', ');
        if (privates.length === 0) {
          return (
            `const __doc = ${docExpr};\n` +
            `    if (!__doc) return __doc;\n` +
            `    return { ...(__doc as any), ${assigns} };`
          );
        }
        const dels = privates.map((p) => `delete (__out as any).${p};`).join(' ');
        return (
          `const __doc = ${docExpr};\n` +
          `    if (!__doc) return __doc;\n` +
          `    const __out = { ...(__doc as any), ${assigns} };\n` +
          `    ${dels}\n` +
          `    return __out;`
        );
      }

      const lines: string[] = [
        `const __rawDoc = ${docExpr};`,
        `    if (!__rawDoc) return __rawDoc;`,
      ];
      if (encrypted.length > 0 && options.encryptionImport) {
        lines.push(
          `    const __doc = await __decryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(encrypted)}, __rawDoc);`,
        );
      } else {
        lines.push(`    const __doc = __rawDoc;`);
      }
      if (policyGated && policyEnforceable) {
        for (const check of docPolicyPlan.rowChecks) {
          lines.push(
            `    if (!__allowsRead(${JSON.stringify(check.policyName)}, ${JSON.stringify(entity.name)}, () => ${check.code})) return null;`,
          );
        }
      }
      const assigns = inlineComputed.fields
        .map((f) => `${f.name}: ${f.code.replace(/\b__row\b/g, '__doc')}`)
        .join(', ');
      if (privates.length === 0) {
        lines.push(
          inlineComputed.fields.length > 0
            ? `    return { ...(__doc as any), ${assigns} };`
            : `    return __doc;`,
        );
        return lines.join('\n');
      }
      const dels = privates.map((p) => `delete (__out as any).${p};`).join(' ');
      lines.push(
        `    const __out = { ...(__doc as any)${assigns ? `, ${assigns}` : ''} };`,
        `    ${dels}`,
        `    return __out;`,
      );
      return lines.join('\n');
    };

    // list/get/listBy — tenant + soft-delete filters applied in helpers.
    emitListEntityQuery(blocks, entity, table, rf, options, qfn, policyPrelude, finishRows);
    emitGetEntityQuery(blocks, entity, table, rf, options, qfn, policyPrelude, finishDoc);
    emitListByIndexQueries(
      blocks,
      ir,
      entity,
      table,
      rf,
      options,
      qfn,
      policyPrelude,
      finishRows,
    );
  }

  // System events table reads (when emitted): recent feed + the three indexed
  // lookups (by_type / by_entity / by_entityId) the schema declares on it.
  if (options.emitEventsTable) {
    // Event rows carry payloads from every entity, so ANY read/all policy in
    // the program locks the events feed down too — unless an auth seam is set
    // (same rule as entity queries: public + tenant via getAuthContext).
    const anyReadPolicy = ir.policies.some((p) => p.action === 'read' || p.action === 'all');
    const evq = anyReadPolicy ? 'internalQuery' : 'query';
    const ev = resolveEventsTableName(ir, options);
    blocks.push(
      `export const listRecentEvents = ${evq}({\n` +
        `  args: {},\n` +
        `  handler: async (ctx) => {\n` +
        `    return await ctx.db.query("${ev}").order("desc").take(50);\n` +
        `  },\n});`,
    );
    for (const field of ['type', 'entity', 'entityId']) {
      blocks.push(
        `export const listEventsBy${capWord(field)} = ${evq}({\n` +
          `  args: { ${field}: v.string() },\n` +
          `  handler: async (ctx, { ${field} }) => {\n` +
          `    return await ctx.db.query("${ev}").withIndex("by_${field}", (q) => q.eq("${field}", ${field})).collect();\n` +
          `  },\n});`,
      );
    }
  }

  const body = blocks.join('\n\n');
  const needsAuthCtx = !!options.authContextImport && /\bgetAuthContext\b/.test(body);
  const needsDecrypt = !!options.encryptionImport && /\b__decryptDoc\b/.test(body);
  const helpers: string[] = [];
  if (/\b__allowsRead\(/.test(body)) helpers.push(READ_POLICY_HELPER);
  if (/\bcheckRole\(/.test(body)) {
    helpers.push(
      `const ROLE_PERMISSIONS: Record<string, { action: string; target?: string }[]> = ${roleMapLiteral(ir)};\n\n` +
        `function checkRole(userRole: unknown, action: unknown, target?: unknown): boolean {\n` +
        `  if (typeof userRole !== "string" || typeof action !== "string") return false;\n` +
        `  const perms = ROLE_PERMISSIONS[userRole];\n` +
        `  const requestedTarget = typeof target === "string" ? target : undefined;\n` +
        `  return perms ? perms.some((permission) =>\n` +
        `    (permission.action === action || permission.action === "all") &&\n` +
        `    (permission.target === undefined || permission.target === requestedTarget)\n` +
        `  ) : false;\n` +
        `}`,
    );
  }
  if (/\bflag\(/.test(body)) {
    helpers.push(
      `// Feature toggle (configurable). Not an authorization gate.\nfunction flag(_name?: string): boolean { return true; }`,
    );
  }
  const serverImports = [
    ...(/= query\({/.test(body) || blocks.length === 0 ? ['query'] : []),
    ...(/= internalQuery\({/.test(body) ? ['internalQuery'] : []),
  ];
  const code =
    `${GENERATED_HEADER}\n// ${blocks.length} query function(s).\n\n` +
    `import { ${serverImports.join(', ')} } from "./_generated/server";\n` +
    `import { v } from "convex/values";\n` +
    (needsAuthCtx
      ? `import { getAuthContext } from ${JSON.stringify(options.authContextImport)};\n`
      : '') +
    (needsDecrypt ? `import { decrypt } from ${JSON.stringify(options.encryptionImport)};\n` : '') +
    `\n` +
    (needsDecrypt ? `${DECRYPT_HELPER}\n\n` : '') +
    (helpers.length ? `${helpers.join('\n\n')}\n\n` : '') +
    `${body}\n`;

  return { code, diagnostics };
}

// ---------------------------------------------------------------------------
// Mutations
// ---------------------------------------------------------------------------

/** Build the ROLE_PERMISSIONS map literal from IR roles' effective permissions. */
function roleMapLiteral(ir: IR): string {
  const map: Record<string, { action: string; target?: string }[]> = {};
  for (const role of ir.roles ?? []) {
    map[role.name] = [...(role.effectivePermissions ?? [])]
      .map((permission) => ({
        action: permission.action,
        ...(permission.target === undefined ? {} : { target: permission.target }),
      }))
      .sort((a, b) =>
        `${a.action}\u0000${a.target ?? ''}`.localeCompare(`${b.action}\u0000${b.target ?? ''}`),
      );
  }
  return JSON.stringify(map, null, 2);
}

interface CheckSpec {
  expr: IRExpression | undefined;
  /** denial message */
  message: string;
  /** diagnostic code emitted when unresolved */
  code: 'CONVEX_UNRESOLVED_POLICY' | 'CONVEX_UNRESOLVED_GUARD' | 'CONVEX_UNRESOLVED_CONSTRAINT';
  label: string;
  /**
   * failWhen polarity (docs/spec/semantics.md § Constraint Polarity): a TRUTHY
   * expression is the violation, so the check throws when the expression holds.
   * Default/absent: falsy expression is the violation.
   */
  failWhen?: boolean;
}

/** Render governance checks fail-closed. Returns TS lines + diagnostics. */
function renderChecks(
  entityName: string,
  checks: CheckSpec[],
  scope: RenderScope,
): { lines: string[]; diagnostics: ProjectionDiagnostic[] } {
  const lines: string[] = [];
  const diagnostics: ProjectionDiagnostic[] = [];
  for (const c of checks) {
    const { code, unresolved } = renderExpression(c.expr, scope);
    if (unresolved.length > 0) {
      diagnostics.push({
        severity: 'error',
        code: c.code,
        entity: entityName,
        message: `${c.label}: could not resolve expression (${unresolved.join('; ')}). Emitted a denying throw (fail-closed).`,
      });
      lines.push(`    throw new Error(${JSON.stringify(`${c.label} unresolved — denied`)});`);
    } else if (c.failWhen) {
      lines.push(`    if (${code}) throw new Error(${JSON.stringify(c.message)});`);
    } else {
      lines.push(`    if (!(${code})) throw new Error(${JSON.stringify(c.message)});`);
    }
  }
  return { lines, diagnostics };
}

/** Collect the policy/guard/constraint checks for a command, in runtime order. */
function commandChecks(ir: IR, cmd: IRCommand, policyMode: 'enforce' | 'skip'): CheckSpec[] {
  const checks: CheckSpec[] = [];
  if (policyMode !== 'skip') {
    for (const pName of cmd.policies ?? []) {
      const policy: IRPolicy | undefined = ir.policies.find((p) => p.name === pName);
      if (!policy) continue;
      checks.push({
        expr: policy.expression,
        message: policy.message ?? `Policy ${pName} denied`,
        code: 'CONVEX_UNRESOLVED_POLICY',
        label: `policy '${pName}'`,
      });
    }
  }
  for (let i = 0; i < cmd.guards.length; i++) {
    checks.push({
      expr: cmd.guards[i],
      message: `Guard ${i} failed`,
      code: 'CONVEX_UNRESOLVED_GUARD',
      label: `guard[${i}]`,
    });
  }
  for (const c of (cmd.constraints ?? []) as IRConstraint[]) {
    if (c.severity && c.severity !== 'block') continue;
    checks.push({
      expr: c.expression,
      message: c.message ?? c.messageTemplate ?? `Constraint ${c.code} failed`,
      code: 'CONVEX_UNRESOLVED_CONSTRAINT',
      label: `constraint '${c.code}'`,
      failWhen: c.failWhen === true,
    });
  }
  return checks;
}

/** Render reaction fan-out for the events a command emits. */
function renderReactions(
  ir: IR,
  options: Normalized,
  emits: string[],
): { lines: string[]; diagnostics: ProjectionDiagnostic[] } {
  const lines: string[] = [];
  const diagnostics: ProjectionDiagnostic[] = [];
  const matched = (ir.reactions ?? []).filter((r: IRReactionRule) => emits.includes(r.event));
  if (matched.length === 0) return { lines, diagnostics };
  lines.push('    // Reactions');
  const tenantProp = ir.tenant?.property;
  // Count vars + the shared tenant binding are handler-scoped (one handler per
  // command, so all matched reactions share a scope); dedupe across reactions.
  let countCounter = 0;
  let tenantEmitted = false;

  /**
   * Render ONE reaction param. An aggregate-count param lowers to a read block
   * (preLines) that counts rows of the param's entity matching its ANDed equality
   * predicates, then binds the param to that count variable. The foreign-key (or
   * any indexed) predicate drives a `withIndex` read; remaining predicates,
   * soft-delete, and tenant scope are applied as JS `.filter`s — mirroring the
   * hardened read surface. Any other param renders as a single expression.
   * Returns `entry: null` when the value cannot be resolved (caller omits it).
   */
  const buildParam = (
    p: IRReactionParam,
    scope: RenderScope,
    label: string,
  ): { preLines: string[]; entry: string | null } => {
    const e = p.expression;
    if (e.kind === 'aggregate' && e.op === 'count') {
      const childEntity = ir.entities.find((en) => en.name === e.entity);
      if (!childEntity) {
        diagnostics.push({
          severity: 'error',
          code: 'CONVEX_AGGREGATE_UNKNOWN_ENTITY',
          message: `${label} param '${p.name}' counts unknown entity '${e.entity}'; omitted.`,
        });
        return { preLines: [], entry: null };
      }
      const childTable = resolveConvexTableName(e.entity, options);
      const rf = resolveReadFilter(ir, childEntity, options);
      const refFields = collectReferenceFields(childEntity, ir, options);
      const isIndexedField = (field: string): boolean => {
        const prop = childEntity.properties.find((pp) => pp.name === field);
        return !!prop && (prop.modifiers.includes('indexed') || refFields.has(field));
      };
      const renderVal = (val: IRExpression): RenderResult => {
        const r = renderExpression(val, scope);
        if (r.unresolved.length) {
          diagnostics.push({
            severity: 'warning',
            code: 'CONVEX_UNRESOLVED_AGGREGATE_PREDICATE',
            message: `${label} param '${p.name}' count predicate value unresolved (${r.unresolved.join('; ')}).`,
          });
        }
        return r;
      };

      const indexedPred = e.predicates.find((pr) => isIndexedField(pr.field));
      const remaining = indexedPred
        ? e.predicates.filter((pr) => pr !== indexedPred)
        : e.predicates;
      const rowsVar = `__count${countCounter}_rows`;
      const countVar = `__count${countCounter}`;
      countCounter++;
      const preLines: string[] = [];

      let queryHead: string;
      if (indexedPred) {
        const v = renderVal(indexedPred.value);
        queryHead = `ctx.db.query("${childTable}").withIndex("by_${indexedPred.field}", (q) => q.eq("${indexedPred.field}", ${v.code}))`;
      } else {
        queryHead = `ctx.db.query("${childTable}")`;
        diagnostics.push({
          severity: 'info',
          code: 'CONVEX_AGGREGATE_UNINDEXED',
          message: `${label} param '${p.name}' counts '${e.entity}' with no indexed/foreign-key predicate; rendered a table scan (mark an equality field indexed for speed).`,
        });
      }
      preLines.push(`    const ${rowsVar} = await ${queryHead}.collect();`);

      const filters: string[] = [];
      for (const pr of remaining) {
        const v = renderVal(pr.value);
        filters.push(`(d as any).${pr.field} === ${v.code}`);
      }
      if (rf.hasSoftDelete) filters.push(`(d as any).${rf.deletedProp} == null`);
      if (rf.hasTenant && rf.tenantProp) {
        if (!tenantEmitted) {
          preLines.push(tenantBindingLine(options, rf.tenantProp!));
          tenantEmitted = true;
        }
        filters.push(`(d as any).${rf.tenantProp} === __tenant`);
      }
      const chain = filters.length ? filters.map((f) => `.filter((d) => ${f})`).join('') : '';
      preLines.push(`    const ${countVar} = ${rowsVar}${chain}.length;`);
      return { preLines, entry: `${p.name}: ${countVar}` };
    }

    const { code, unresolved } = renderExpression(e, scope);
    if (unresolved.length) {
      diagnostics.push({
        severity: 'warning',
        code: 'CONVEX_UNRESOLVED_REACTION_PARAM',
        message: `${label} param '${p.name}' unresolved (${unresolved.join('; ')}); omitted.`,
      });
      return { preLines: [], entry: null };
    }
    return { preLines: [], entry: `${p.name}: ${code}` };
  };

  matched.forEach((reaction, idx) => {
    const targetTable = resolveConvexTableName(reaction.targetEntity, options);
    const targetEntity = ir.entities.find((e) => e.name === reaction.targetEntity);
    const label = `reaction ${reaction.event}→${reaction.targetEntity}.${reaction.targetCommand}`;

    // Fan-out reaction: dispatch the command on every target row where
    // row.<matchField> == matchSource. matchSource + params resolve against the
    // event payload (self === payload, matching the reference runtime). Each
    // match runs the generated target command runner in the same transaction,
    // so the target command's own governance/actions run. Prefer the schema index (FK/indexed fields
    // carry by_<field>); fall back to a table-scan filter otherwise.
    if (reaction.fanOut) {
      const fanScope: RenderScope = {
        selfVar: 'payload',
        globals: ['payload', 'user', 'context', 'args'],
      };
      const src = renderExpression(reaction.fanOut.matchSource, fanScope);
      if (src.unresolved.length) {
        diagnostics.push({
          severity: 'warning',
          code: 'CONVEX_UNRESOLVED_REACTION_FANOUT',
          message: `fan-out ${label} match source unresolved (${src.unresolved.join('; ')}); skipped.`,
        });
        return;
      }
      const fanParams: string[] = [];
      const fanPreLines: string[] = [];
      for (const p of reaction.params ?? []) {
        const r = buildParam(p, fanScope, label);
        fanPreLines.push(...r.preLines);
        if (r.entry) fanParams.push(r.entry);
      }
      const field = reaction.fanOut.matchField;
      const isFk = !!targetEntity && collectReferenceFields(targetEntity, ir, options).has(field);
      const targetProp = targetEntity?.properties.find((p) => p.name === field);
      const indexed = !!targetProp && (targetProp.modifiers.includes('indexed') || isFk);
      if (!indexed) {
        diagnostics.push({
          severity: 'info',
          code: 'CONVEX_FANOUT_UNINDEXED',
          message: `fan-out ${label} matches on non-indexed '${field}'; rendered an unindexed filter (mark '${reaction.targetEntity}.${field}' indexed for speed).`,
        });
      }
      const queryExpr = indexed
        ? `ctx.db.query("${targetTable}").withIndex("by_${field}", (q) => q.eq("${field}", ${src.code}))`
        : `ctx.db.query("${targetTable}").filter((q) => q.eq(q.field("${field}"), ${src.code}))`;
      const rowsVar = `fanRows${idx}`;
      for (const pl of fanPreLines) lines.push(pl);
      lines.push(`    const ${rowsVar} = await ${queryExpr}.collect();`);
      lines.push(`    for (const __row of ${rowsVar}) {`);
      lines.push(
        `      await ${commandRunnerName(reaction.targetEntity, reaction.targetCommand)}(ctx, { docId: (__row as any)._id${fanParams.length ? ', ' + fanParams.join(', ') : ''} } as any);`,
      );
      lines.push(`    }`);
      return;
    }

    const scope: RenderScope = {
      selfVar: 'payload',
      globals: ['payload', 'user', 'context', 'args'],
    };
    const paramEntries: string[] = [];
    const paramPreLines: string[] = [];
    const paramNamesSeen = new Set<string>();
    for (const p of reaction.params ?? []) {
      const r = buildParam(p, scope, label);
      paramPreLines.push(...r.preLines);
      if (r.entry) {
        paramEntries.push(r.entry);
        paramNamesSeen.add(p.name);
      }
    }
    // Tenant propagation: a reaction fires within the source entity's tenant, so
    // when it creates a tenant-scoped target, thread the source tenantId
    // (available as payload.<tenantProp>) unless an explicit param already set it.
    const targetIsTenantScoped =
      !!tenantProp && !!targetEntity?.properties.some((p) => p.name === tenantProp);
    if (
      reaction.targetCommand === 'create' &&
      targetIsTenantScoped &&
      !paramNamesSeen.has(tenantProp!)
    ) {
      paramEntries.unshift(`${tenantProp}: payload.${tenantProp}`);
    }
    for (const pl of paramPreLines) lines.push(pl);
    if (reaction.targetCommand === 'create') {
      lines.push(
        `    await ${commandRunnerName(reaction.targetEntity, reaction.targetCommand)}(ctx, { ${paramEntries.join(', ')} } as any);`,
      );
    } else {
      const resolve = renderExpression(reaction.resolve, {
        selfVar: 'payload',
        globals: ['payload', 'user', 'context', 'args'],
      });
      const varName = `reactionTarget${idx}`;
      if (reaction.resolve?.kind === 'literal' && reaction.resolve.value.kind === 'null') {
        lines.push(
          `    // reaction ${reaction.event} → ${reaction.targetEntity}.${reaction.targetCommand} (resolve: null — no target id)`,
        );
      } else if (resolve.unresolved.length) {
        diagnostics.push({
          severity: 'warning',
          code: 'CONVEX_UNRESOLVED_REACTION_TARGET',
          message: `${label} target unresolved; skipped.`,
        });
      } else {
        lines.push(`    const ${varName} = ${resolve.code};`);
        lines.push(
          `    if (${varName}) await ${commandRunnerName(reaction.targetEntity, reaction.targetCommand)}(ctx, { docId: ${varName}${paramEntries.length ? ', ' + paramEntries.join(', ') : ''} } as any);`,
        );
      }
    }
  });
  return { lines, diagnostics };
}

/**
 * Auth/context/payload bindings a handler needs, derived by scanning the body
 * for the identifiers it actually references (avoids both undefined-name and
 * unused-var errors). With `authContextImport`, identity comes from the
 * author-owned `getAuthContext(ctx)`; `forceAuth` binds `__auth` even when the
 * scanned body does not reference it (tenant injection / ownership checks are
 * assembled after this scan).
 */
function authBindings(bodyText: string, options: Normalized, forceAuth = false): string[] {
  const lines: string[] = [];
  const refs = (token: string) => new RegExp(`\\b${token}\\b`).test(bodyText);
  const needsIdentity = forceAuth || refs('userRole') || refs('user');
  if (needsIdentity) {
    if (options.authContextImport) {
      lines.push(`    const __auth = (await getAuthContext(ctx)) as any;`);
      if (refs('userRole')) lines.push(`    const userRole = __auth.role ?? "anonymous";`);
      if (refs('user')) lines.push(`    const user = __auth;`);
    } else {
      // Diagnostic CONVEX_AUTH_CONTEXT_REQUIRED is emitted at generate(); fail loud in output too.
      lines.push(
        `    throw new Error("CONVEX_AUTH_CONTEXT_REQUIRED: set options.authContextImport");`,
      );
    }
  }
  if (refs('context')) lines.push(`    const context = (ctx as any);`);
  return lines;
}

function creationSeedFallback(ir: IR, property: IRProperty, validator: string): string | undefined {
  if (property.defaultValue) return defaultToTs(property.defaultValue, validator);
  if (property.autoNow) return 'Date.now()';
  if (!property.modifiers.includes('required') || property.type.nullable) return undefined;
  if (property.type.name === 'boolean') return 'false';
  if (property.type.name === 'array' || property.type.name === 'list') return '[]';
  if (/\bv\.int64\(\)/.test(validator)) return '0n';
  if (/\bv\.number\(\)/.test(validator)) return '0';
  if (/\bv\.string\(\)/.test(validator)) return '""';
  const enumType = ir.enums.find((item) => item.name === property.type.name);
  if (enumType?.values[0]) return JSON.stringify(enumType.values[0].name);
  return undefined;
}

function renderGovernedCreationEntry(
  ir: IR,
  options: Normalized,
  entity: IREntity,
  cmd: IRCommand,
  table: string,
  runnerName: string,
  tenantScoped: boolean,
  writeTenantProp: string | undefined,
  encryptionActive: boolean,
  mutationEncrypted: string[],
): { code?: string; diagnostics: ProjectionDiagnostic[] } {
  const diagnostics: ProjectionDiagnostic[] = [];
  const fkTargets = collectFkTargets(entity, ir, options);
  const params = cmd.parameters ?? [];
  const paramNames = new Set(params.map((param) => param.name));
  const actionByTarget = new Map(
    (cmd.actions ?? [])
      .filter((action) => action.kind === 'mutate' && action.target)
      .map((action) => [action.target!, action]),
  );
  const seedLines: string[] = [];

  for (const property of entity.properties) {
    if (property.name === 'id') continue;
    if (tenantScoped && property.name === writeTenantProp) {
      seedLines.push(`      ${property.name}: __auth.${property.name}`);
      continue;
    }
    if (isConvexVersionManagedField(entity, property.name)) continue;
    const built = buildValidator(
      entity,
      property,
      ir,
      options,
      fkTargets.get(property.name),
    );
    diagnostics.push(...built.diagnostics);
    if (!built.validator) continue;

    const action = actionByTarget.get(property.name);
    if (action) {
      const rendered = renderExpression(action.expression, {
        selfVar: 'args',
      });
      if (rendered.unresolved.length === 0 && !/\bself\b|\bthis\b/.test(rendered.code)) {
        seedLines.push(`      ${property.name}: ${rendered.code}`);
        continue;
      }
    }
    if (paramNames.has(property.name)) {
      const fallback = creationSeedFallback(ir, property, built.validator);
      seedLines.push(
        `      ${property.name}: args.${property.name}${fallback === undefined ? '' : ` ?? ${fallback}`}`,
      );
      continue;
    }
    const fallback = creationSeedFallback(ir, property, built.validator);
    if (fallback !== undefined) {
      seedLines.push(`      ${property.name}: ${fallback}`);
      continue;
    }
    if (property.modifiers.includes('required') && !property.type.nullable) {
      diagnostics.push({
        severity: 'warning',
        code: 'CONVEX_CREATION_ENTRY_UNSEEDABLE',
        entity: entity.name,
        message: `Cannot emit governed creation entry for '${entity.name}.${cmd.name}': required field '${property.name}' has no default, command value, or safe Convex seed.`,
      });
      return { diagnostics };
    }
  }
  // This is an allocation shell, not the completed creation write. The
  // governed command below performs the first version increment.
  if (entity.versionProperty) seedLines.push(`      ${entity.versionProperty}: 0`);
  if (entity.versionAtProperty) {
    seedLines.push(`      ${entity.versionAtProperty}: Date.now()`);
  }

  const argLines = params.map(
    (param) =>
      `    ${param.name}: ${param.required ? paramValidator(param.type) : `v.optional(${paramValidator(param.type)})`}`,
  );
  const exportName = commandCreationExportName(entity.name, cmd.name);
  const authLines = authBindings(seedLines.join('\n'), options, tenantScoped);
  const seedVar = encryptionActive ? '__storedSeed' : '__seed';
  const code =
    `export const ${exportName} = mutation({\n` +
    `  args: {\n${argLines.join(',\n')}\n  },\n` +
    `  handler: async (ctx, args: any) => {\n` +
    (authLines.length ? authLines.join('\n') + '\n' : '') +
    `    const __seed: Record<string, any> = {\n${seedLines.join(',\n')}\n    };\n` +
    (encryptionActive
      ? `    const __storedSeed = await __encryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(mutationEncrypted)}, __seed);\n`
      : '') +
    `    const docId = await ctx.db.insert("${table}", ${seedVar} as any);\n` +
    `    try {\n` +
    `      await ${runnerName}(ctx, { ...args, docId }, true);\n` +
    `      return { docId };\n` +
    `    } catch (error) {\n` +
    `      await ctx.db.delete(docId);\n` +
    `      throw error;\n` +
    `    }\n` +
    `  },\n});`;
  return { code, diagnostics };
}

function generateMutation(
  ir: IR,
  options: Normalized,
  cmd: IRCommand,
): { code: string; diagnostics: ProjectionDiagnostic[] } | null {
  if (!cmd.entity) return null;
  const entity = ir.entities.find((e) => e.name === cmd.entity);
  if (!entity || !isPersistentEntity(entity, ir)) return null;

  const diagnostics: ProjectionDiagnostic[] = [];
  const table = resolveConvexTableName(entity.name, options);
  const name = `${entity.name}_${cmd.name}`;
  const runnerName = commandRunnerName(entity.name, cmd.name);
  const fkTargets = collectFkTargets(entity, ir, options);
  const isCreate = cmd.name === 'create';
  const paramNames = (cmd.parameters ?? []).map((p) => p.name);

  // Write-side tenant protection, active only with an auth seam: creates set
  // the tenant column server-side (never a client argument), instance commands
  // verify the document belongs to the caller's tenant.
  const writeTenantProp = options.tenantIdProperty ?? ir.tenant?.property;
  const tenantScoped =
    !!options.authContextImport &&
    !!writeTenantProp &&
    entity.properties.some((p) => p.name === writeTenantProp);
  // Mutation RESULTS are client-visible too — strip private fields from them
  // exactly like the query surfaces do.
  const mutationPrivates = privateFieldNames(entity);
  const mutationEncrypted = encryptedFieldNames(entity);
  const encryptionActive = mutationEncrypted.length > 0 && !!options.encryptionImport;

  if (isCreate) {
    // Unified create model. Every stored field must be reachable so the insert
    // satisfies the schema: it is either (a) set by a `mutate` action, (b) filled
    // from its default, or (c) exposed as a mutation argument the caller provides.
    // Command parameters that feed actions (and are not themselves fields) are
    // also exposed as args. All expressions resolve against `args`.
    const params = cmd.parameters ?? [];
    const scope: RenderScope = {
      selfVar: 'args',
      resolveCollectionElementType: (collection) =>
        resolveHasManyDocElementType(entity, collection, options),
    };
    const argLines: string[] = [];
    const argNames = new Set<string>();
    const docLines: string[] = [];

    // Fields set by mutate actions (mapped from params); not exposed as args.
    // A create action targeting the tenant column is overridden by the seam —
    // the tenant id is always server-derived, never caller-influenced.
    if (
      tenantScoped &&
      (cmd.actions ?? []).some((a) => a.kind === 'mutate' && a.target === writeTenantProp)
    ) {
      diagnostics.push({
        severity: 'info',
        code: 'CONVEX_TENANT_SERVER_DERIVED',
        entity: entity.name,
        message: `create action sets '${writeTenantProp}'; overridden — the tenant id is derived from the auth context.`,
      });
    }
    const mutates = (cmd.actions ?? []).filter(
      (a) =>
        a.kind === 'mutate' &&
        a.target &&
        !(tenantScoped && a.target === writeTenantProp) &&
        !isConvexVersionManagedField(entity, a.target),
    );
    const targetSet = new Set(mutates.map((a) => a.target as string));

    // Entity properties → args (unless action-set) + doc lines (with defaults).
    for (const p of entity.properties) {
      if (tenantScoped && p.name === writeTenantProp) {
        docLines.push(`      ${p.name}: __auth.${p.name}`);
        argNames.add(p.name); // suppress any same-named command param arg
        continue;
      }
      if (isConvexVersionManagedField(entity, p.name)) {
        // Seeded below — never accept client-supplied version / versionAt.
        argNames.add(p.name);
        continue;
      }
      if (p.name === 'id' || targetSet.has(p.name)) continue;
      const { validator, diagnostics: vd } = buildValidator(
        entity,
        p,
        ir,
        options,
        fkTargets.get(p.name),
      );
      diagnostics.push(...vd);
      if (!validator) continue;
      // Required AND no default → required arg; otherwise optional (caller may
      // omit; default fills in).
      const required = p.modifiers.includes('required') && !p.defaultValue;
      if (!argNames.has(p.name)) {
        argLines.push(`    ${p.name}: ${required ? validator : `v.optional(${validator})`}`);
        argNames.add(p.name);
      }
      docLines.push(
        `      ${p.name}: args.${p.name}${p.defaultValue ? ` ?? ${defaultToTs(p.defaultValue, validator)}` : ''}`,
      );
    }

    // Command params that are not entity fields (they feed actions) → args.
    for (const p of params) {
      if (argNames.has(p.name)) continue;
      const validator = paramValidator(p.type);
      argLines.push(`    ${p.name}: ${p.required ? validator : `v.optional(${validator})`}`);
      argNames.add(p.name);
    }

    // mutate actions → doc fields (param → field mapping).
    for (const a of mutates) {
      const { code, unresolved } = renderActionValue(entity, a.target, a.expression, scope);
      if (unresolved.length) {
        diagnostics.push({
          severity: 'warning',
          code: 'CONVEX_UNRESOLVED_ACTION',
          entity: entity.name,
          message: `create action '${a.target}' unresolved (${unresolved.join('; ')}); omitted.`,
        });
        continue;
      }
      docLines.push(`      ${a.target}: ${code}`);
    }

    for (const line of convexCreateVersionDocLines(entity)) {
      docLines.push(line);
    }

    const checks = renderChecks(entity.name, commandChecks(ir, cmd, options.policyMode), scope);
    diagnostics.push(...checks.diagnostics);
    // G7 `emit Event { field: expr }`: populate each event-row payload (and the
    // shared reaction payload below) with declared fields evaluated against the
    // post-action instance. `doc` is the created instance; `self.id` → Convex `_id`.
    const g7Scope: RenderScope = { selfVar: 'doc', idExpr: '_id' };
    const g7 = unionEmitPayloadFields(cmd, g7Scope, '_id');
    diagnostics.push(...g7.diagnostics);
    const events = renderEvents(
      resolveEventsTableName(ir, options),
      ir,
      entity,
      cmd,
      '_id',
      g7Scope,
    );
    diagnostics.push(...events.diagnostics);
    const reactions = renderReactions(ir, options, cmd.emits ?? []);
    diagnostics.push(...reactions.diagnostics);
    const tail = [...events.lines, ...reactions.lines].join('\n');
    // Reaction expressions resolve `payload` against the reference-runtime
    // contract (runtime-engine.ts): the emitted event payload is `{ ...input,
    // result }` then G7 fields overwrite; reactions additionally see `_subject`.
    // When G7 declares `result`, keep the business field and omit the envelope
    // (entity identity stays on `_subject`) — never emit duplicate object keys.
    const collision = reactionPayloadCollisionPlanner.plan(g7.fields, {
      entity: entity.name,
      command: cmd.name,
    });
    diagnostics.push(...collision.diagnostics);
    const g7Entries = collision.reactionFields.map((f) => `${f.name}: ${f.code}`).join(', ');
    const subjectLiteral = `_subject: { entity: ${JSON.stringify(entity.name)}, command: ${JSON.stringify(cmd.name)}, id: _id }`;
    const envelopeResult = collision.includeEnvelopeResult
      ? 'result: { _id, id: _id, ...doc }'
      : '';
    const payloadParts = [
      '_id',
      'id: _id',
      '...doc',
      ...(envelopeResult ? [envelopeResult] : []),
      ...(g7Entries ? [g7Entries] : []),
      subjectLiteral,
    ].join(', ');
    const payloadBinding = /\bpayload\b/.test(tail)
      ? `    const payload: Record<string, any> = { ${payloadParts} };\n`
      : '';
    const bodyText = [...checks.lines, tail].join('\n');
    const authLines = authBindings(bodyText, options, tenantScoped);

    const body =
      `async function ${runnerName}(ctx: MutationCtx, args: any) {\n` +
      (authLines.length ? authLines.join('\n') + '\n' : '') +
      `    const doc: Record<string, any> = {\n${docLines.join(',\n')}\n    };\n` +
      (checks.lines.length ? checks.lines.join('\n') + '\n' : '') +
      (encryptionActive
        ? `    const __storedDoc = await __encryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(mutationEncrypted)}, doc);\n`
        : '') +
      `    const _id = await ctx.db.insert("${table}", ${encryptionActive ? '__storedDoc' : 'doc'} as any);\n` +
      payloadBinding +
      (tail ? tail + '\n' : '') +
      stripPrivateFromReturn('{ _id, ...doc }', mutationPrivates) +
      `}\n\n` +
      `export const ${name} = mutation({\n` +
      `  args: {\n${argLines.join(',\n')}\n  },\n` +
      `  handler: ${runnerName},\n});`;
    return { code: body, diagnostics };
  }

  // Non-create mutation
  const versionOcc = renderConvexUpdateVersionOcc(entity);
  const argLines = [`    docId: v.id("${table}")`];
  for (const p of cmd.parameters ?? []) {
    argLines.push(
      `    ${p.name}: ${p.required ? paramValidator(p.type) : `v.optional(${paramValidator(p.type)})`}`,
    );
  }
  if (versionOcc.argLine) {
    argLines.push(versionOcc.argLine);
  }

  // Non-create: command params are destructured locals; self.x → doc.x.
  const checkSpecs = commandChecks(ir, cmd, options.policyMode);
  const countOfRels = new Set<string>();
  for (const c of checkSpecs) collectCountOfHasManyRels(c.expr, countOfRels);
  const hasManyPreloads = renderCountOfHasManyPreloads(ir, entity, countOfRels, options, 'docId');
  const checks = renderChecks(entity.name, checkSpecs, {
    selfVar: 'doc',
    locals: paramNames,
    resolveCollectionElementType: (collection) =>
      resolveHasManyDocElementType(entity, collection, options),
  });
  diagnostics.push(...checks.diagnostics);

  // IR `compute` bindings: evaluate against pre-update `doc`, then expose as
  // locals to mutate actions and emit payloads (semantics.md § Actions).
  const compute = renderCommandComputeBindings(cmd, {
    selfVar: 'doc',
    locals: paramNames,
  });
  diagnostics.push(...compute.diagnostics);
  const computeLocals = compute.localNames;
  const actionLocals = [...paramNames, ...computeLocals];

  const updateLines: string[] = [];
  const resolvedUpdates: {
    target: string;
    expression: IRExpression;
    renderedCode: string;
  }[] = [];
  for (const a of cmd.actions ?? []) {
    if (a.kind !== 'mutate' || !a.target) continue;
    if (isConvexVersionManagedField(entity, a.target)) continue;
    const { code, unresolved } = renderActionValue(entity, a.target, a.expression, {
      selfVar: 'doc',
      locals: actionLocals,
    });
    if (unresolved.length) {
      diagnostics.push({
        severity: 'warning',
        code: 'CONVEX_UNRESOLVED_ACTION',
        entity: entity.name,
        message: `action mutate '${a.target}' unresolved (${unresolved.join('; ')}); omitted.`,
      });
      continue;
    }
    updateLines.push(`      ${a.target}: ${code}`);
    resolvedUpdates.push({ target: a.target, expression: a.expression, renderedCode: code });
  }

  const transitions = renderTransitionChecks(entity, cmd, 'doc', resolvedUpdates, '__creation');
  diagnostics.push(...transitions.diagnostics);

  // Post-action snapshot for G7 / schema synthesis. Current fields → `__after`;
  // previous-state fields → `compute` locals (pre-update expressions).
  const needsAfter = commandNeedsAfterSnapshot(ir, entity, cmd);
  const g7Scope: RenderScope = {
    selfVar: needsAfter ? '__after' : 'doc',
    locals: actionLocals,
    idExpr: 'docId',
    beforeVar: 'doc',
  };
  const g7 = unionEmitPayloadFields(cmd, g7Scope, 'docId', computeLocals);
  diagnostics.push(...g7.diagnostics);
  const useAfter = needsAfter;
  const afterLine = useAfter
    ? `    const __after: Record<string, any> = { ...doc, ...updates };\n`
    : '';
  const events = renderEvents(
    resolveEventsTableName(ir, options),
    ir,
    entity,
    cmd,
    'docId',
    g7Scope,
    computeLocals,
  );
  diagnostics.push(...events.diagnostics);
  const reactions = renderReactions(ir, options, cmd.emits ?? []);
  diagnostics.push(...reactions.diagnostics);

  const tail = [...events.lines, ...reactions.lines].join('\n');
  // Same reference-runtime payload contract as the create branch, including
  // G7 `result` collision handling (business field wins; `_subject` keeps id).
  const collision = reactionPayloadCollisionPlanner.plan(g7.fields, {
    entity: entity.name,
    command: cmd.name,
  });
  diagnostics.push(...collision.diagnostics);
  const g7Entries = collision.reactionFields.map((f) => `${f.name}: ${f.code}`).join(', ');
  const subjectLiteral = `_subject: { entity: ${JSON.stringify(entity.name)}, command: ${JSON.stringify(cmd.name)}, id: docId }`;
  const envelopeResult = collision.includeEnvelopeResult
    ? useAfter
      ? 'result: { id: docId, ...__after }'
      : 'result: { id: docId, ...doc, ...updates }'
    : '';
  const baseParts = useAfter ? ['id: docId', '...__after'] : ['id: docId', '...doc', '...updates'];
  const payloadParts = [
    ...baseParts,
    ...(envelopeResult ? [envelopeResult] : []),
    ...(g7Entries ? [g7Entries] : []),
    subjectLiteral,
  ].join(', ');
  const payloadBinding = /\bpayload\b/.test(tail)
    ? `    const payload: Record<string, any> = { ${payloadParts} };\n`
    : '';
  const argDestructureParts = [...paramNames];
  if (versionOcc.expectedArgName) {
    argDestructureParts.push(versionOcc.expectedArgName);
  }
  const argDestructure = argDestructureParts.length ? `, ${argDestructureParts.join(', ')}` : '';
  const bodyText = [
    ...checks.lines,
    ...transitions.lines,
    ...versionOcc.checkLines,
    ...updateLines,
    ...versionOcc.updateFields,
    tail,
  ].join('\n');
  const authLines = authBindings(bodyText, options, tenantScoped);
  // Document-tenancy check: an instance command may only touch documents in
  // the caller's tenant. Same message as the missing-doc throw so a cross-
  // tenant probe cannot distinguish "exists elsewhere" from "does not exist".
  const ownershipLine = tenantScoped
    ? `    if ((${encryptionActive ? '__storedDoc' : 'doc'} as any).${writeTenantProp} !== __auth.${writeTenantProp}) throw new Error(${JSON.stringify(`${entity.name} not found`)});\n`
    : '';

  const updateFieldLines = [...updateLines, ...versionOcc.updateFields];
  let body =
    `async function ${runnerName}(ctx: MutationCtx, { docId${argDestructure} }: any, __creation = false) {\n` +
    (authLines.length ? authLines.join('\n') + '\n' : '') +
    (encryptionActive
      ? `    const __storedDoc = await ctx.db.get(docId) as Record<string, any> | null;\n` +
        `    if (!__storedDoc) throw new Error(${JSON.stringify(`${entity.name} not found`)});\n` +
        ownershipLine +
        `    const doc = await __decryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(mutationEncrypted)}, __storedDoc) as Record<string, any>;\n`
      : `    const doc = await ctx.db.get(docId) as Record<string, any> | null;\n` +
        `    if (!doc) throw new Error(${JSON.stringify(`${entity.name} not found`)});\n` +
        ownershipLine) +
    (hasManyPreloads.length ? hasManyPreloads.join('\n') + '\n' : '') +
    (checks.lines.length ? checks.lines.join('\n') + '\n' : '') +
    (compute.bindings.length ? computeBindingLines(compute.bindings).join('\n') + '\n' : '') +
    (transitions.lines.length ? transitions.lines.join('\n') + '\n' : '') +
    (versionOcc.checkLines.length ? versionOcc.checkLines.join('\n') + '\n' : '') +
    `    const updates = {\n${updateFieldLines.join(',\n')}${updateFieldLines.length ? '\n' : ''}    };\n` +
    (encryptionActive
      ? `    const __storedUpdates = await __encryptDoc(ctx, ${JSON.stringify(entity.name)}, ${JSON.stringify(mutationEncrypted)}, updates);\n`
      : '') +
    `    await ctx.db.patch(docId, ${encryptionActive ? '__storedUpdates' : 'updates'} as any);\n` +
    afterLine +
    payloadBinding +
    (tail ? tail + '\n' : '') +
    stripPrivateFromReturn('{ ...doc, ...updates }', mutationPrivates) +
    `}\n\n` +
    `export const ${name} = mutation({\n` +
    `  args: {\n${argLines.join(',\n')}\n  },\n` +
    `  handler: ${runnerName},\n});`;

  if (commandCreationEntry(ir, entity)?.name === cmd.name) {
    const creation = renderGovernedCreationEntry(
      ir,
      options,
      entity,
      cmd,
      table,
      runnerName,
      tenantScoped,
      writeTenantProp,
      encryptionActive,
      mutationEncrypted,
    );
    diagnostics.push(...creation.diagnostics);
    if (creation.code) body += `\n\n${creation.code}`;
  }
  return { code: body, diagnostics };
}

export function generateMutations(
  ir: IR,
  rawOptions: Record<string, unknown> | undefined,
): FunctionsResult {
  const options = normalizeOptions(rawOptions);
  const diagnostics: ProjectionDiagnostic[] = [];
  const blocks: string[] = [];

  for (const cmd of ir.commands) {
    const m = generateMutation(ir, options, cmd);
    if (!m) continue;
    blocks.push(m.code);
    diagnostics.push(...m.diagnostics);
  }

  // Emit helpers only when the generated mutations actually reference them
  // (a policyMode:'skip' build may use neither), so there is no dead code.
  const body = blocks.join('\n\n');
  const helpers: string[] = [];
  const needsEncrypt = !!options.encryptionImport && /\b__encryptDoc\b/.test(body);
  const needsDecrypt = !!options.encryptionImport && /\b__decryptDoc\b/.test(body);
  if (needsEncrypt) helpers.push(ENCRYPT_HELPER);
  if (needsDecrypt) helpers.push(DECRYPT_HELPER);
  if (/\bcheckRole\(/.test(body)) {
    helpers.push(
      `// Role hierarchy from IR (effective permissions after inheritance).\n` +
        `const ROLE_PERMISSIONS: Record<string, { action: string; target?: string }[]> = ${roleMapLiteral(ir)};\n\n` +
        `function checkRole(userRole: unknown, action: unknown, target?: unknown): boolean {\n` +
        `  if (typeof userRole !== "string" || typeof action !== "string") return false;\n` +
        `  const perms = ROLE_PERMISSIONS[userRole];\n` +
        `  const requestedTarget = typeof target === "string" ? target : undefined;\n` +
        `  return perms ? perms.some((permission) =>\n` +
        `    (permission.action === action || permission.action === "all") &&\n` +
        `    (permission.target === undefined || permission.target === requestedTarget)\n` +
        `  ) : false;\n` +
        `}`,
    );
  }
  if (/\bflag\(/.test(body)) {
    helpers.push(
      `// Feature toggle (configurable). Not an authorization gate.\nfunction flag(_name?: string): boolean { return true; }`,
    );
  }

  const policyNote =
    options.policyMode === 'skip' ? ' (policyMode: skip — authorization policies omitted)' : '';
  const needsAuthCtx = !!options.authContextImport && /\bgetAuthContext\b/.test(body);
  const needsDoc = codeUsesDocType(body);
  const code =
    `${GENERATED_HEADER}\n// ${blocks.length} mutation(s); roles: ${(ir.roles ?? []).length}; policies: ${ir.policies.length}.${policyNote}\n\n` +
    `import { mutation, type MutationCtx } from "./_generated/server";\n` +
    `import { v } from "convex/values";\n` +
    (needsDoc ? `import type { Doc } from "./_generated/dataModel";\n` : '') +
    (needsAuthCtx
      ? `import { getAuthContext } from ${JSON.stringify(options.authContextImport)};\n`
      : '') +
    (needsEncrypt || needsDecrypt
      ? `import { ${[needsEncrypt ? 'encrypt' : '', needsDecrypt ? 'decrypt' : ''].filter(Boolean).join(', ')} } from ${JSON.stringify(options.encryptionImport)};\n`
      : '') +
    `\n` +
    (helpers.length ? helpers.join('\n\n') + '\n\n' : '') +
    `${body}\n`;

  return { code, diagnostics };
}
