/**
 * Convex orchestration surfaces: `convex.crons`, `convex.http`, `convex.sagas`.
 *
 * - Schedules → `convex/crons.ts` (`cronJobs()` scheduling the command mutations).
 * - Webhooks  → `convex/http.ts` (`httpRouter` + `httpAction` invoking commands).
 * - Sagas     → `convex/sagas.ts` (orchestrator `action`s that run each step via
 *   `ctx.runMutation`, compensating completed steps in reverse on failure).
 *
 * Convex has no native saga/webhook/cron-of-commands primitive, so these are
 * faithful structural projections onto Convex's scheduler / HTTP / action APIs.
 * Step argument mapping is not expressed in the saga IR, so the orchestrator
 * forwards a single `input` payload to each step (app-supplied).
 */

import type { IR, IRSchedule, IRWebhook, IRSaga } from '../../ir';
import type { ProjectionDiagnostic } from '../interface';
import { normalizeOptions } from './options.js';
import { renderExpression, DEFAULT_GLOBALS } from './expression.js';

export interface OrchestrationResult {
  code: string;
  diagnostics: ProjectionDiagnostic[];
}

const HEADER = '// GENERATED by the Manifest → Convex projection. DO NOT EDIT.';

/** Mutation export name for a command on an entity (matches convex.mutations). */
function mutationRef(entity: string, command: string): string {
  return `api.mutations.${entity}_${command}`;
}

// ---------------------------------------------------------------------------
// Schedules → crons
// ---------------------------------------------------------------------------

function intervalArg(durationMs: number): string {
  if (durationMs % 3_600_000 === 0) return `{ hours: ${durationMs / 3_600_000} }`;
  if (durationMs % 60_000 === 0) return `{ minutes: ${durationMs / 60_000} }`;
  return `{ seconds: ${Math.max(1, Math.round(durationMs / 1000))} }`;
}

export function generateCrons(ir: IR, rawOptions: Record<string, unknown> | undefined): OrchestrationResult {
  void normalizeOptions(rawOptions);
  const diagnostics: ProjectionDiagnostic[] = [];
  const lines: string[] = [];

  for (const sched of (ir.schedules ?? []) as IRSchedule[]) {
    const ref = sched.entityName ? mutationRef(sched.entityName, sched.commandName) : `api.mutations.${sched.commandName}`;
    const paramsObj = `{${(sched.params ?? []).map(p => {
      const { code, unresolved } = renderExpression(p.expression, { selfVar: 'args' });
      if (unresolved.length) diagnostics.push({ severity: 'warning', code: 'CONVEX_UNRESOLVED_SCHEDULE_PARAM', message: `schedule '${sched.name}' param '${p.name}' unresolved; omitted.` });
      return unresolved.length ? null : ` ${p.name}: ${code}`;
    }).filter(Boolean).join(',')} }`;
    const t = sched.trigger;
    if (t.kind === 'cron' && t.cron) {
      lines.push(`crons.cron(${JSON.stringify(sched.name)}, ${JSON.stringify(t.cron)}, ${ref}, ${paramsObj});`);
    } else if (t.durationMs) {
      lines.push(`crons.interval(${JSON.stringify(sched.name)}, ${intervalArg(t.durationMs)}, ${ref}, ${paramsObj});`);
    } else {
      diagnostics.push({ severity: 'warning', code: 'CONVEX_UNRESOLVED_TRIGGER', message: `schedule '${sched.name}' has no cron/duration; skipped.` });
    }
  }

  if (lines.length === 0) diagnostics.push({ severity: 'info', code: 'CONVEX_NO_SCHEDULES', message: 'No schedules declared; emitted an empty crons file.' });

  const code =
    `${HEADER}\n// ${lines.length} cron job(s).\n\n` +
    `import { cronJobs } from "convex/server";\n` +
    `import { api } from "./_generated/api";\n\n` +
    `const crons = cronJobs();\n\n` +
    `${lines.join('\n')}${lines.length ? '\n\n' : '\n'}` +
    `export default crons;\n`;
  return { code, diagnostics };
}

// ---------------------------------------------------------------------------
// Webhooks → http
// ---------------------------------------------------------------------------

export function generateHttp(ir: IR, rawOptions: Record<string, unknown> | undefined): OrchestrationResult {
  void normalizeOptions(rawOptions);
  const diagnostics: ProjectionDiagnostic[] = [];
  const routes: string[] = [];

  for (const wh of (ir.webhooks ?? []) as IRWebhook[]) {
    const ref = wh.entity ? mutationRef(wh.entity, wh.command) : `api.mutations.${wh.command}`;
    const transformEntries: string[] = [];
    for (const t of wh.transform ?? []) {
      const { code, unresolved } = renderExpression(t.expression, { selfVar: 'body', globals: ['body', ...DEFAULT_GLOBALS] });
      if (unresolved.length) { diagnostics.push({ severity: 'warning', code: 'CONVEX_UNRESOLVED_WEBHOOK_PARAM', message: `webhook '${wh.name}' param '${t.name}' unresolved; omitted.` }); continue; }
      transformEntries.push(`${t.name}: ${code}`);
    }
    const method = (wh.method ?? 'POST').toUpperCase();
    routes.push(
      `http.route({\n` +
      `  path: ${JSON.stringify(wh.path)},\n` +
      `  method: ${JSON.stringify(method)},\n` +
      `  handler: httpAction(async (ctx, request) => {\n` +
      `    const body = await request.json();\n` +
      `    await ctx.runMutation(${ref}, { ${transformEntries.join(', ')} } as any);\n` +
      `    return new Response(null, { status: 200 });\n` +
      `  }),\n` +
      `});`,
    );
  }

  if (routes.length === 0) diagnostics.push({ severity: 'info', code: 'CONVEX_NO_WEBHOOKS', message: 'No webhooks declared; emitted an empty http router.' });

  const code =
    `${HEADER}\n// ${routes.length} webhook route(s).\n\n` +
    `import { httpRouter } from "convex/server";\n` +
    `import { httpAction } from "./_generated/server";\n` +
    `import { api } from "./_generated/api";\n\n` +
    `const http = httpRouter();\n\n` +
    `${routes.join('\n\n')}${routes.length ? '\n\n' : '\n'}` +
    `export default http;\n`;
  return { code, diagnostics };
}

// ---------------------------------------------------------------------------
// Sagas → orchestrator actions
// ---------------------------------------------------------------------------

export function generateSagas(ir: IR, _rawOptions: Record<string, unknown> | undefined): OrchestrationResult {
  const diagnostics: ProjectionDiagnostic[] = [];
  const blocks: string[] = [];

  for (const saga of (ir.sagas ?? []) as IRSaga[]) {
    const forward: string[] = [];
    saga.steps.forEach((step, i) => {
      forward.push(`      await ctx.runMutation(${mutationRef(step.commandEntity, step.command)}, input as any);`);
      forward.push(`      completed.push(${i});`);
    });

    // Compensation in reverse for completed steps that declare a compensate command.
    const comp: string[] = [];
    if (saga.onFailure === 'compensate') {
      for (let i = saga.steps.length - 1; i >= 0; i--) {
        const step = saga.steps[i];
        if (!step.compensate || !step.compensateEntity) continue;
        comp.push(`      if (completed.includes(${i})) await ctx.runMutation(${mutationRef(step.compensateEntity, step.compensate)}, input as any);`);
      }
    }

    blocks.push(
      `export const ${saga.name} = action({\n` +
      `  args: { input: v.any() },\n` +
      `  handler: async (ctx, { input }) => {\n` +
      `    const completed: number[] = [];\n` +
      `    try {\n` +
      `${forward.join('\n')}\n` +
      `      return { ok: true, completed };\n` +
      `    } catch (err) {\n` +
      (comp.length
        ? `      // compensate completed steps in reverse\n${comp.join('\n')}\n`
        : `      // onFailure: ${saga.onFailure} — no compensation\n`) +
      `      throw err;\n` +
      `    }\n` +
      `  },\n});`,
    );
  }

  if (blocks.length === 0) diagnostics.push({ severity: 'info', code: 'CONVEX_NO_SAGAS', message: 'No sagas declared; emitted an empty sagas file.' });

  const code =
    `${HEADER}\n// ${blocks.length} saga orchestrator(s).\n\n` +
    `import { action } from "./_generated/server";\n` +
    `import { v } from "convex/values";\n` +
    `import { api } from "./_generated/api";\n\n` +
    `${blocks.join('\n\n')}${blocks.length ? '\n' : ''}`;
  return { code, diagnostics };
}
