/**
 * Convex React client surface (`convex.react`).
 *
 * Emits typed `useQuery` / `useMutation` wrappers against the generated
 * `api.queries.*` / `api.mutations.*` symbols from the queries/mutations
 * surfaces. This is the Manifest frontend contract for Convex apps — not
 * react-query or openapi (those target HTTP dispatchers).
 *
 * Entities gated by read/`all` policies emit `internalQuery` server-side and
 * are omitted from client hooks (fail-closed; use a policy-enforcing public
 * wrapper). Mutations remain callable — governance runs inside the mutation.
 */

import type { IR, IRCommand, IREntity } from '../../ir';
import type { ProjectionDiagnostic } from '../interface';
import { isPersistentEntity } from './persist.js';
import { hasReadPolicies } from './read-policies.js';

export const SURFACE_REACT = 'convex.react' as const;

export interface ConvexReactOptions {
  /** Import path for Convex's generated `api` (default `../convex/_generated/api`). */
  apiImportPath?: string;
  /** Output path hint (default `src/lib/manifest-convex-react.ts`). */
  output?: string;
}

const DEFAULTS = {
  apiImportPath: '../convex/_generated/api',
  output: 'src/lib/manifest-convex-react.ts',
} as const;

function persistentEntities(ir: IR): IREntity[] {
  return ir.entities.filter((e) => isPersistentEntity(e, ir));
}

function entityCommands(ir: IR, entityName: string): IRCommand[] {
  return ir.commands.filter((c) => c.entity === entityName);
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}

/**
 * Generate the Convex React client module for persistent, publicly readable
 * entities + all persistent-entity commands.
 */
export function generateReactClient(
  ir: IR,
  rawOptions: Record<string, unknown> | undefined,
): { code: string; diagnostics: ProjectionDiagnostic[]; pathHint: string } {
  const reactOpts = (rawOptions ?? {}) as ConvexReactOptions;
  const apiImport = reactOpts.apiImportPath ?? DEFAULTS.apiImportPath;
  const pathHint = reactOpts.output ?? DEFAULTS.output;
  const diagnostics: ProjectionDiagnostic[] = [];
  const lines: string[] = [];

  lines.push(`/** Generated by Manifest convex.react — do not edit by hand. */`);
  lines.push(`import { useQuery, useMutation } from "convex/react";`);
  lines.push(`import { api } from ${JSON.stringify(apiImport)};`);
  lines.push('');

  let hookCount = 0;
  for (const entity of persistentEntities(ir)) {
    const gated = hasReadPolicies(ir, entity.name);
    if (gated) {
      diagnostics.push({
        severity: 'info',
        code: 'CONVEX_REACT_INTERNAL_QUERY',
        entity: entity.name,
        message:
          `Entity '${entity.name}' has read/all policies — queries are internalQuery ` +
          `(not client-callable). No useQuery hooks emitted; expose via a policy-enforcing public wrapper.`,
      });
    } else {
      lines.push(`/** Reactive list for ${entity.name}. */`);
      lines.push(`export function useList${entity.name}() {`);
      lines.push(`  return useQuery(api.queries.list${entity.name});`);
      lines.push(`}`);
      lines.push('');
      lines.push(`/** Reactive get-by-id for ${entity.name}. Pass "skip" to suspend. */`);
      lines.push(
        `export function useGet${entity.name}(id: string | "skip") {`,
      );
      lines.push(
        `  return useQuery(api.queries.get${entity.name}, id === "skip" ? "skip" : { id: id as any });`,
      );
      lines.push(`}`);
      lines.push('');
      hookCount += 2;
    }

    for (const cmd of entityCommands(ir, entity.name)) {
      const mutName = `${entity.name}_${cmd.name}`;
      const hookName = `use${entity.name}${capitalize(cmd.name)}`;
      lines.push(`/** Mutation hook for ${entity.name}.${cmd.name}. */`);
      lines.push(`export function ${hookName}() {`);
      lines.push(`  return useMutation(api.mutations.${mutName});`);
      lines.push(`}`);
      lines.push('');
      hookCount += 1;
    }
  }

  if (hookCount === 0) {
    diagnostics.push({
      severity: 'warning',
      code: 'CONVEX_REACT_EMPTY',
      message:
        'No client hooks emitted (no persistent entities, or all reads are internalQuery with no commands).',
    });
  }

  lines.push(`export const MANIFEST_CONVEX_REACT_HOOK_COUNT = ${hookCount} as const;`);
  lines.push('');

  return { code: lines.join('\n'), diagnostics, pathHint };
}
