/**
 * Convex React client surface (`convex.react`).
 *
 * Emits typed `useQuery` / `useMutation` wrappers against the generated
 * `api.queries.*` / `api.mutations.*` symbols from the queries/mutations
 * surfaces. This is the Manifest frontend contract for Convex apps — not
 * react-query or openapi (those target HTTP dispatchers).
 *
 * Entities gated by read/`all` policies emit `internalQuery` server-side and
 * are omitted from client hooks (fail-closed; use a policy-enforcing public
 * wrapper). Mutations remain callable — governance runs inside the mutation.
 *
 * When `zodParamsImport` is set, command/create hooks parse Manifest command
 * params through the bundled Zod module (`zod.schemas`) before calling Convex.
 */

import type { IR, IRCommand, IREntity } from '../../ir';
import type { ProjectionDiagnostic } from '../interface';
import { zodParamsSchemaName } from '../shared/route-contract.js';
import { isPersistentEntity } from './persist.js';
import {
  relativeImportBetweenArtifacts,
  resolveReactApiImportPath,
  resolveReactClientPathHint,
} from './react-api-import.js';
import { resolveConvexReadVisibility } from './read-policies.js';
import { commandCreationEntry, commandCreationExportName } from './creation-entry.js';

export const SURFACE_REACT = 'convex.react' as const;

/** Bundled Zod companion path (zod.schemas surface) — not per-command microfiles. */
export const DEFAULT_ZOD_BUNDLE_PATH = 'schemas/manifest-schemas.ts';

export interface ConvexReactOptions {
  /**
   * Override for the Convex `api` import. When omitted, derived from
   * {@link output} (or the default client path) relative to
   * `convex/_generated/api`.
   */
  apiImportPath?: string;
  /**
   * Output path hint (default `src/lib/manifest-convex-react.ts`).
   * Schema-surface `output` values like `convex/schema.ts` are ignored so a
   * shared options bag cannot mis-place the client artifact.
   */
  output?: string;
  /**
   * When set (Convex auth seam), emit useQuery hooks even for read-policy-gated
   * entities — matching public `query` emission under the same option.
   */
  authContextImport?: string;
  /**
   * Wire mutation/create hooks to parse command params via the Zod bundle.
   * - `true` → import from {@link DEFAULT_ZOD_BUNDLE_PATH} relative to the client
   * - string → explicit module specifier
   * - omitted/false → raw `useMutation` (no client parse)
   */
  zodParamsImport?: string | boolean;
}

function persistentEntities(ir: IR): IREntity[] {
  return ir.entities.filter((e) => isPersistentEntity(e, ir));
}

function entityCommands(ir: IR, entityName: string): IRCommand[] {
  return ir.commands.filter((c) => c.entity === entityName);
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}

export function resolveZodParamsImportPath(
  reactPathHint: string,
  option: string | boolean | undefined,
): string | undefined {
  if (option === false || option === undefined) return undefined;
  if (option === true) {
    return relativeImportBetweenArtifacts(reactPathHint, DEFAULT_ZOD_BUNDLE_PATH);
  }
  if (typeof option === 'string' && option.trim().length > 0) {
    return option.trim();
  }
  return undefined;
}

/**
 * Generate the Convex React client module for persistent, publicly readable
 * entities + all persistent-entity commands.
 */
export function generateReactClient(
  ir: IR,
  rawOptions: Record<string, unknown> | undefined,
): { code: string; diagnostics: ProjectionDiagnostic[]; pathHint: string } {
  const reactOpts = (rawOptions ?? {}) as ConvexReactOptions;
  const pathHint = resolveReactClientPathHint(reactOpts.output);
  const apiImport = resolveReactApiImportPath(pathHint, reactOpts.apiImportPath);
  const zodImport = resolveZodParamsImportPath(pathHint, reactOpts.zodParamsImport);
  const diagnostics: ProjectionDiagnostic[] = [];
  const lines: string[] = [];

  const schemaNames = new Set<string>();
  if (zodImport) {
    for (const entity of persistentEntities(ir)) {
      for (const cmd of entityCommands(ir, entity.name)) {
        schemaNames.add(zodParamsSchemaName(entity.name, cmd.name));
      }
      const creationEntry = commandCreationEntry(ir, entity);
      if (creationEntry) {
        schemaNames.add(zodParamsSchemaName(entity.name, creationEntry.name));
      }
    }
  }

  lines.push(`/** Generated by Manifest convex.react — do not edit by hand. */`);
  lines.push(`import { useQuery, useMutation } from "convex/react";`);
  lines.push(`import { api } from ${JSON.stringify(apiImport)};`);
  if (zodImport && schemaNames.size > 0) {
    const names = [...schemaNames].sort();
    lines.push(`import {`);
    for (const name of names) {
      lines.push(`  ${name},`);
    }
    lines.push(`} from ${JSON.stringify(zodImport)};`);
    lines.push('');
    // Zod datetime → Date; Convex mutations expect epoch millis.
    lines.push(`function __convexArgsFromZod(parsed: Record<string, unknown>): Record<string, unknown> {`);
    lines.push(`  const out: Record<string, unknown> = {};`);
    lines.push(`  for (const [key, value] of Object.entries(parsed)) {`);
    lines.push(`    out[key] = value instanceof Date ? value.getTime() : value;`);
    lines.push(`  }`);
    lines.push(`  return out;`);
    lines.push(`}`);
  }
  lines.push('');

  let hookCount = 0;
  const authSeam =
    typeof reactOpts.authContextImport === 'string' && reactOpts.authContextImport.length > 0;
  for (const entity of persistentEntities(ir)) {
    const visibility = resolveConvexReadVisibility(
      ir,
      entity.name,
      reactOpts.authContextImport,
      '__row',
    );
    diagnostics.push(...visibility.policies.diagnostics);
    if (!visibility.clientReadable) {
      if (visibility.gated) {
        diagnostics.push({
          severity: 'info',
          code: 'CONVEX_REACT_INTERNAL_QUERY',
          entity: entity.name,
          message:
            `Entity '${entity.name}' has read/all policies without a fully renderable auth seam — ` +
            `queries are internalQuery (not client-callable). No useQuery hooks emitted.`,
        });
      }
    } else {
      if (visibility.gated && authSeam) {
        diagnostics.push({
          severity: 'info',
          code: 'CONVEX_REACT_AUTH_QUERY',
          entity: entity.name,
          message:
            `Entity '${entity.name}' has read/all policies and authContextImport is set — ` +
            `emitting useQuery against policy-enforcing public queries.`,
        });
      }
      lines.push(`/** Reactive list for ${entity.name}. */`);
      lines.push(`export function useList${entity.name}() {`);
      lines.push(`  return useQuery(api.queries.list${entity.name});`);
      lines.push(`}`);
      lines.push('');
      lines.push(`/** Reactive get-by-id for ${entity.name}. Pass "skip" to suspend. */`);
      lines.push(`export function useGet${entity.name}(id: string | "skip") {`);
      lines.push(
        `  return useQuery(api.queries.get${entity.name}, id === "skip" ? "skip" : { id: id as any });`,
      );
      lines.push(`}`);
      lines.push('');
      hookCount += 2;
    }

    for (const cmd of entityCommands(ir, entity.name)) {
      const mutName = `${entity.name}_${cmd.name}`;
      const hookName = `use${entity.name}${capitalize(cmd.name)}`;
      const schemaName = zodParamsSchemaName(entity.name, cmd.name);
      lines.push(`/** Mutation hook for ${entity.name}.${cmd.name}. */`);
      lines.push(`export function ${hookName}() {`);
      if (zodImport) {
        lines.push(`  const mutate = useMutation(api.mutations.${mutName});`);
        lines.push(`  return (args: any) => {`);
        lines.push(`    const { docId, version, idempotencyKey, ...params } = args ?? {};`);
        lines.push(`    const parsed = ${schemaName}.parse(params) as Record<string, unknown>;`);
        lines.push(
          `    return mutate({ docId, version, idempotencyKey, ...__convexArgsFromZod(parsed) } as any);`,
        );
        lines.push(`  };`);
      } else {
        lines.push(`  return useMutation(api.mutations.${mutName});`);
      }
      lines.push(`}`);
      lines.push('');
      hookCount += 1;
    }

    const creationEntry = commandCreationEntry(ir, entity);
    if (creationEntry) {
      const mutationName = commandCreationExportName(entity.name, creationEntry.name);
      const schemaName = zodParamsSchemaName(entity.name, creationEntry.name);
      lines.push(`/** Governed creation hook for ${entity.name}.${creationEntry.name}. */`);
      lines.push(`export function useCreate${entity.name}() {`);
      if (zodImport) {
        lines.push(`  const mutate = useMutation(api.mutations.${mutationName});`);
        lines.push(`  return (args: any) => {`);
        lines.push(`    const { idempotencyKey, ...params } = args ?? {};`);
        lines.push(`    const parsed = ${schemaName}.parse(params) as Record<string, unknown>;`);
        lines.push(`    const body = __convexArgsFromZod(parsed);`);
        lines.push(
          `    return mutate((idempotencyKey !== undefined ? { ...body, idempotencyKey } : body) as any);`,
        );
        lines.push(`  };`);
      } else {
        lines.push(`  return useMutation(api.mutations.${mutationName});`);
      }
      lines.push(`}`);
      lines.push('');
      hookCount += 1;
    }
  }

  if (hookCount === 0) {
    diagnostics.push({
      severity: 'warning',
      code: 'CONVEX_REACT_EMPTY',
      message:
        'No client hooks emitted (no persistent entities, or all reads are internalQuery with no commands).',
    });
  }

  if (zodImport) {
    diagnostics.push({
      severity: 'info',
      code: 'CONVEX_REACT_ZOD_PARAMS',
      message:
        `Mutation/create hooks parse command params via ${zodImport} ` +
        `(bundled zod.schemas — not per-command schema files).`,
    });
  }

  lines.push(`export const MANIFEST_CONVEX_REACT_HOOK_COUNT = ${hookCount} as const;`);
  lines.push('');

  return { code: lines.join('\n'), diagnostics, pathHint };
}
