/**
 * HTTP adapter generator — produces typed client code for remote services.
 *
 * Given a ServiceDescriptor, generates a TypeScript module with strongly-typed
 * methods for each exposed command. The generated adapter handles:
 * - Base URL configuration
 * - Auth token injection
 * - Policy bridge header propagation
 * - Timeout and error handling
 *
 * The generator is pure: same descriptor in → same code out. No side effects.
 *
 * @module federation/http-adapter
 */

import type { ServiceDescriptor, ExposedEntity, ExposedCommand, TypedClientAdapter } from './types';
import { buildBridgeHeaders } from './client.js';
import type { PolicyBridgeHeaders } from './types';

/**
 * Generate a typed HTTP client adapter from a service descriptor.
 * The generated source is a self-contained TypeScript module.
 */
export function generateHttpAdapter(descriptor: ServiceDescriptor): TypedClientAdapter {
  const source = renderAdapterSource(descriptor);
  return {
    serviceId: descriptor.serviceId,
    source,
    create(
      baseUrl: string,
      options?: { authToken?: string; timeoutMs?: number },
    ): Record<string, (...args: unknown[]) => Promise<unknown>> {
      const client = createRuntimeClient(
        descriptor,
        baseUrl,
        options?.authToken,
        options?.timeoutMs ?? 30000,
      );
      return client;
    },
  };
}

/**
 * Render the TypeScript source code for a typed HTTP adapter.
 * The output is deterministic for a given descriptor.
 */
export function renderAdapterSource(descriptor: ServiceDescriptor): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * Typed HTTP client adapter for service "${descriptor.serviceId}".`);
  if (descriptor.displayName) {
    lines.push(` * Display name: ${descriptor.displayName}`);
  }
  lines.push(` * Schema version: ${descriptor.schemaVersion}`);
  lines.push(` * Auto-generated by Manifest federation — do not edit manually.`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`export interface BridgeHeaders {`);
  lines.push(`  actorId?: string;`);
  lines.push(`  tenantId?: string;`);
  lines.push(`  orgId?: string;`);
  lines.push(`  actorRoles?: string[];`);
  lines.push(`  requestId?: string;`);
  lines.push(`  correlationId?: string;`);
  lines.push(`  bearerToken?: string;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export interface FederationResult<T = unknown> {`);
  lines.push(`  success: boolean;`);
  lines.push(`  result?: T;`);
  lines.push(`  error?: string;`);
  lines.push(`  deniedBy?: string;`);
  lines.push(`  guardFailure?: { index: number; expression: string };`);
  lines.push(`  emittedEvents: Array<{ name: string; channel: string; payload: unknown }>;`);
  lines.push(`  correlationId?: string;`);
  lines.push(`  handledBy: string;`);
  lines.push(`  respondedAt: number;`);
  lines.push(`}`);
  lines.push(``);

  // Group commands by entity
  for (const entity of descriptor.entities) {
    lines.push(
      `// ── Entity: ${entity.name}${entity.module ? ` (module: ${entity.module})` : ''} ──`,
    );
    for (const cmd of entity.commands) {
      const methodName = toMethodName(entity.name, cmd.name);
      lines.push(...renderCommandMethod(methodName, entity, cmd));
      lines.push(``);
    }
  }

  // Factory function
  const className = toPascalCase(descriptor.serviceId) + 'Client';
  lines.push(`export class ${className} {`);
  lines.push(`  constructor(`);
  lines.push(`    private baseUrl: string,`);
  lines.push(
    `    private options: { authToken?: string; timeoutMs?: number; fetchImpl?: typeof fetch } = {}`,
  );
  lines.push(`  ) {}`);
  lines.push(``);
  for (const entity of descriptor.entities) {
    for (const cmd of entity.commands) {
      const methodName = toMethodName(entity.name, cmd.name);
      lines.push(
        `  ${methodName}(input: Record<string, unknown>, bridge: BridgeHeaders): Promise<FederationResult> {`,
      );
      lines.push(
        `    return invokeCommand(this, "${entity.name}", "${cmd.name}", input, bridge, ${cmd.idempotent});`,
      );
      lines.push(`  }`);
    }
  }
  lines.push(`}`);
  lines.push(``);

  // Shared invoke helper
  lines.push(`async function invokeCommand(`);
  lines.push(
    `  client: { baseUrl: string; options: { authToken?: string; timeoutMs?: number; fetchImpl?: typeof fetch } },`,
  );
  lines.push(`  entity: string,`);
  lines.push(`  command: string,`);
  lines.push(`  input: Record<string, unknown>,`);
  lines.push(`  bridge: BridgeHeaders,`);
  lines.push(`  idempotent: boolean`);
  lines.push(`): Promise<FederationResult> {`);
  lines.push(`  const fetchImpl = client.options.fetchImpl ?? globalThis.fetch;`);
  lines.push(`  const controller = new AbortController();`);
  lines.push(
    `  const timeout = setTimeout(() => controller.abort(), client.options.timeoutMs ?? 30000);`,
  );
  lines.push(`  const headers: Record<string, string> = { "Content-Type": "application/json" };`);
  lines.push(`  if (bridge.actorId) headers["X-Manifest-Actor"] = bridge.actorId;`);
  lines.push(`  if (bridge.tenantId) headers["X-Manifest-Tenant"] = bridge.tenantId;`);
  lines.push(`  if (bridge.orgId) headers["X-Manifest-Org"] = bridge.orgId;`);
  lines.push(
    `  if (bridge.actorRoles?.length) headers["X-Manifest-Roles"] = bridge.actorRoles.join(",");`,
  );
  lines.push(`  if (bridge.requestId) headers["X-Request-Id"] = bridge.requestId;`);
  lines.push(`  if (bridge.correlationId) headers["X-Correlation-Id"] = bridge.correlationId;`);
  lines.push(
    `  if (client.options.authToken) headers["Authorization"] = \`Bearer \${client.options.authToken}\`;`,
  );
  lines.push(`  try {`);
  lines.push(
    `    const url = \`\${client.baseUrl}/__manifest/federation/\${encodeURIComponent(entity)}/\${encodeURIComponent(command)}\`;`,
  );
  lines.push(
    `    const res = await fetchImpl(url, { method: "POST", headers, body: JSON.stringify({ input }), signal: controller.signal });`,
  );
  lines.push(`    clearTimeout(timeout);`);
  lines.push(`    return await res.json() as FederationResult;`);
  lines.push(`  } catch (err) {`);
  lines.push(`    clearTimeout(timeout);`);
  lines.push(
    `    return { success: false, error: err instanceof Error ? err.message : String(err), emittedEvents: [], handledBy: "${descriptor.serviceId}", respondedAt: Date.now() };`,
  );
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  return lines.join('\n');
}

function renderCommandMethod(
  methodName: string,
  entity: ExposedEntity,
  cmd: ExposedCommand,
): string[] {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * ${cmd.description ?? `Invoke ${entity.name}.${cmd.name} on the remote service.`}`);
  if (cmd.requiredPolicies.length > 0) {
    lines.push(` * Required policies: ${cmd.requiredPolicies.join(', ')}`);
  }
  if (cmd.idempotent) {
    lines.push(` * Idempotent: safe to retry on transient failure.`);
  }
  lines.push(` */`);
  lines.push(`export function ${methodName}(`);
  lines.push(
    `  client: { baseUrl: string; options: { authToken?: string; timeoutMs?: number; fetchImpl?: typeof fetch } },`,
  );
  lines.push(`  input: Record<string, unknown>,`);
  lines.push(`  bridge: BridgeHeaders`);
  lines.push(`): Promise<FederationResult> {`);
  lines.push(
    `  return invokeCommand(client, "${entity.name}", "${cmd.name}", input, bridge, ${cmd.idempotent});`,
  );
  lines.push(`}`);
  return lines;
}

function createRuntimeClient(
  descriptor: ServiceDescriptor,
  baseUrl: string,
  authToken: string | undefined,
  timeoutMs: number,
): Record<string, (...args: unknown[]) => Promise<unknown>> {
  const client: Record<string, (...args: unknown[]) => Promise<unknown>> = {};
  for (const entity of descriptor.entities) {
    for (const cmd of entity.commands) {
      const methodName = toMethodName(entity.name, cmd.name);
      client[methodName] = async (...args: unknown[]) => {
        const input = args[0] as Record<string, unknown>;
        const bridge = args[1] as PolicyBridgeHeaders;
        const fetchImpl = globalThis.fetch;
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), timeoutMs);
        const headers: Record<string, string> = { 'Content-Type': 'application/json' };
        for (const [k, v] of Object.entries(buildBridgeHeaders(bridge))) {
          if (v !== undefined) headers[k] = v;
        }
        if (authToken) headers['Authorization'] = `Bearer ${authToken}`;
        try {
          const url = `${baseUrl}/__manifest/federation/${encodeURIComponent(entity.name)}/${encodeURIComponent(cmd.name)}`;
          const res = await fetchImpl(url, {
            method: 'POST',
            headers,
            body: JSON.stringify({ input }),
            signal: controller.signal,
          });
          clearTimeout(timeout);
          return await res.json();
        } catch (err) {
          clearTimeout(timeout);
          return {
            success: false,
            error: err instanceof Error ? err.message : String(err),
            emittedEvents: [],
            handledBy: descriptor.serviceId,
            respondedAt: Date.now(),
          };
        }
      };
    }
  }
  return client;
}

/**
 * Convert (entityName, commandName) into a camelCase method name.
 * Example: ("Order", "CreateOrder") → "orderCreateOrder"
 */
function toMethodName(entityName: string, commandName: string): string {
  return (
    entityName.charAt(0).toLowerCase() +
    entityName.slice(1) +
    commandName.charAt(0).toUpperCase() +
    commandName.slice(1)
  );
}

/**
 * Convert a serviceId to PascalCase for class names.
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}
