/**
 * Contract-test projection — emits Vitest suites that assert Convex query/
 * mutation export names match IR (schema/query/mutation contract).
 *
 * Surface: `contract-tests.convex`
 */

import type { IR } from '../../ir';
import type {
  ProjectionArtifact,
  ProjectionDiagnostic,
  ProjectionRequest,
  ProjectionResult,
  ProjectionTarget,
} from '../interface';
import { isPersistentEntity } from '../convex/persist.js';
import { hasReadPolicies } from '../convex/read-policies.js';
import { CONTRACT_TESTS_DESCRIPTOR_META } from './descriptor-meta.js';

const SURFACE_CONVEX = 'contract-tests.convex' as const;
const SURFACES = [SURFACE_CONVEX] as const;

function generateConvexContractTests(ir: IR): {
  code: string;
  diagnostics: ProjectionDiagnostic[];
} {
  const diagnostics: ProjectionDiagnostic[] = [];
  const lines: string[] = [];
  lines.push(`/** Generated by Manifest contract-tests.convex — do not edit by hand. */`);
  lines.push(`import { describe, it, expect } from "vitest";`);
  lines.push(`import * as queries from "../convex/queries";`);
  lines.push(`import * as mutations from "../convex/mutations";`);
  lines.push('');
  lines.push(`describe("Manifest Convex contract", () => {`);

  let assertionCount = 0;
  for (const entity of ir.entities.filter((e) => isPersistentEntity(e, ir))) {
    const gated = hasReadPolicies(ir, entity.name);
    if (!gated) {
      lines.push(`  it("exports list${entity.name} / get${entity.name}", () => {`);
      lines.push(`    expect(typeof (queries as any).list${entity.name}).toBe("function");`);
      lines.push(`    expect(typeof (queries as any).get${entity.name}).toBe("function");`);
      lines.push(`  });`);
      assertionCount += 1;
    } else {
      diagnostics.push({
        severity: 'info',
        code: 'CONTRACT_TESTS_SKIP_INTERNAL_QUERY',
        entity: entity.name,
        message: `Skipped list/get assertions for '${entity.name}' (internalQuery / read policy).`,
      });
    }

    for (const cmd of ir.commands.filter((c) => c.entity === entity.name)) {
      const exportName = `${entity.name}_${cmd.name}`;
      lines.push(`  it("exports mutation ${exportName}", () => {`);
      lines.push(`    expect(typeof (mutations as any).${exportName}).toBe("function");`);
      lines.push(`  });`);
      assertionCount += 1;
    }
  }

  if (assertionCount === 0) {
    lines.push(`  it("has no persistent command/query contract (empty IR)", () => {`);
    lines.push(`    expect(true).toBe(true);`);
    lines.push(`  });`);
    diagnostics.push({
      severity: 'warning',
      code: 'CONTRACT_TESTS_EMPTY',
      message: 'No persistent entities/commands — emitted placeholder contract suite.',
    });
  }

  lines.push(`});`);
  lines.push('');
  lines.push(`export const MANIFEST_CONTRACT_TEST_COUNT = ${assertionCount} as const;`);
  lines.push('');

  return { code: lines.join('\n'), diagnostics };
}

export class ContractTestsProjection implements ProjectionTarget {
  readonly name = 'contract-tests';
  readonly description =
    'Generated Vitest contract suites for projection surfaces (Convex query/mutation export parity).';
  readonly surfaces = SURFACES;
  readonly descriptorMeta = CONTRACT_TESTS_DESCRIPTOR_META;

  generate(ir: IR, request: ProjectionRequest): ProjectionResult {
    if (request.surface !== SURFACE_CONVEX) {
      return {
        artifacts: [],
        diagnostics: [
          {
            severity: 'info',
            code: 'CONTRACT_TESTS_UNSUPPORTED_SURFACE',
            message: `contract-tests does not support surface '${request.surface}'. Supported: ${SURFACES.join(', ')}.`,
          },
        ],
      };
    }

    const { code, diagnostics } = generateConvexContractTests(ir);
    const artifact: ProjectionArtifact = {
      id: SURFACE_CONVEX,
      pathHint: 'tests/manifest-convex.contract.test.ts',
      contentType: 'typescript',
      code,
    };
    return { artifacts: [artifact], diagnostics };
  }
}
